#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(CLOSE_COMBAT) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HEAT_WAVE) \
    F(ZEN_HEADBUTT) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUPERCELL_SLAM) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(DARK_PULSE) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(AIR_SLASH) \
    F(GIGA_DRAIN) \
    F(HYPER_VOICE) \
    F(ICY_WIND) \
    F(VENOSHOCK) \
    F(IRON_HEAD) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(BULLDOZE) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(LOW_KICK) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(HIGH_HORSEPOWER) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(LIQUIDATION) \
    F(MYSTICAL_FIRE) \
    F(DEFOG) \
    F(REST) \
    F(DRAINING_KISS) \
    F(SNARL) \
    F(STEEL_WING) \
    F(ELECTROWEB) \
    F(HURRICANE) \
    F(OVERHEAT) \
    F(WILD_CHARGE) \
    F(U_TURN) \
    F(VOLT_SWITCH) \
    F(FLIP_TURN) \
    F(FOCUS_BLAST) \
    F(DAZZLING_GLEAM) \
    F(LOW_SWEEP) \
    F(THUNDER_PUNCH) \
    F(FIRE_PUNCH) \
    F(ICE_PUNCH) \
    F(DUAL_WINGBEAT) \
    F(ROCK_SLIDE) \
    F(DRAIN_PUNCH) \
    F(DRAGON_TAIL) \
    F(FLASH_CANNON) \
    F(WILL_O_WISP) \
    F(THUNDER_WAVE) \
    F(BODY_PRESS) \
    F(FUTURE_SIGHT) \
    F(SCORCHING_SANDS) \
    F(TRICK_ROOM) \
    F(SEED_BOMB) \
    F(HEAT_CRASH) \
    F(PLAY_ROUGH) \
    F(HYDRO_PUMP) \
    F(EARTH_POWER) \
    F(WEATHER_BALL) \
    F(DRAGON_PULSE) \
    F(SHADOW_CLAW) \
    F(SCALD) \
    F(SUPERPOWER) \
    F(AURA_SPHERE) \
    F(TRIPLE_AXEL) \
    F(ICE_SPINNER) \
    F(KNOCK_OFF)
    
#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
