Route4_Frlg_MapScripts::
	.byte 0

Route4_EventScript_Unused::
	end

Route4_EventScript_Woman::
	msgbox Route4_Text_TrippedOverGeodude, MSGBOX_NPC
	end

Route4_EventScript_MtMoonSign::
	msgbox Route4_Text_MtMoonEntrance, MSGBOX_SIGN
	end

Route4_EventScript_RouteSign::
	msgbox Route4_Text_RouteSign, MSGBOX_SIGN
	end

Route4_Text_TrippedOverGeodude::
    .string "Ouch! I tripped over a rocky\n"
    .string "Pokémon, GEODUDE!$"

Route4_Text_CrissyIntro::
    .string "I came to MT. MOON in search of\n"
    .string "mushroom Pokémon.$"

Route4_Text_CrissyDefeat::
    .string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"

Route4_Text_MtMoonEntrance::
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"

Route4_Text_RouteSign::
    .string "Route 4\n"
    .string "MT. MOON - Cerulean City$"

Text_BlackBeltGuy_BitFeisty::
    .string "Sorry, my partner can be a bit feisty.\p"
    .string "But, if you're serious about training,\n"
    .string "take this.$"

Text_BlackBeltTaught::
    .string "That'll give your Pokémon a better\n"
    .string "fighting chance!$"

Text_LowKickTeach::
    .string "A kick of brutal ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When you get right down to it,\n"
    .string "Low Kick is the ultimate attack!\l"
    .string "Don't you agree?$"

Text_LowKickDeclined::
    .string "You'll come crawling back when you\n"
    .string "realize the value of Low Kick.$"

Text_LowKickHereYouGo::
    .string "I like your spirit!\n"
    .string "Take the TM!$"

Text_LowKickTaught::
    .string "Now, we are soul mates in the way\n"
    .string "of kicking!$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You got it from BROCK, didn't you?\p"
    .string "BROCK is cool. He's not just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a GYM LEADER\n"
    .string "like him.$"
