Route21_North_Frlg_MapScripts::
	.byte 0

EventScript_PalletTown_Lass::
	lock
	msgbox Route21_North_Text_Lass
	release
	end

EventScript_PalletTown_Stufful::
	lock
	waitse
	playmoncry SPECIES_STUFFUL, CRY_MODE_NORMAL
	msgbox Route21_North_Text_Stufful
	waitmoncry
	release
	end

Route21_North_Text_Lass::
  .string "{COLOR GREEN}Stufful…\n"
  .string "{COLOR RED}Do you really have to lay down\l"
  .string "here of all places?\p"
  .string "We're blocking the way to Route 21!$"

Route21_North_Text_Stufful::
  .string "Stufful!$"

Route21_North_Text_RonaldIntro::
	.string "You want to know if the fish are\n"
	.string "biting?$"

Route21_North_Text_RonaldDefeat::
	.string "Dang!$"

Route21_North_Text_RonaldPostBattle::
	.string "I can't catch anything good.\n"
	.string "Not one good Pokémon to be had!$"

Route21_North_Text_WadeIntro::
	.string "I got a big haul!\n"
	.string "Wanna go for it?$"

Route21_North_Text_WadeDefeat::
	.string "Heheh, MAGIKARP just don't make\n"
	.string "the grade, do they?$"

Route21_North_Text_WadePostBattle::
	.string "I seem to only catch MAGIKARP!$"

Route21_North_Text_SpencerIntro::
	.string "The sea cleanses my body and soul!$"

Route21_North_Text_SpencerDefeat::
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
	.string "The sea is great and all, but I\n"
	.string "like the mountains, too.$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
