CapeBrink_Text_DH0::
  .string "{COLOR RED}Hello... I am able to teach a\n"
  .string "very powerful forbidden move.\p"
  .string "It's called {COLOR GREEN}Dark Hole.\n"
  .string "{COLOR RED}I'm sure you're familiar with it.\p"
  .string "I can teach it only once, but...\p"
  .string "You'll have to best me in battle.\p"
  .string "Will you entertain me?$"


CapeBrinkDH0_Text_1::
  .string "Very well, let us begin.$"


CapeBrink_Text_DHNoBattle::
  .string "{COLOR RED}Perhaps another day...$"


DHTutor_Text_Defeat::
  .string "Heh, forbidden but still very\n"
  .string "flawed...$"


CapeBrinkDH0_Text_2::
  .string "It feels silly, spending years\n"
  .string "learning this prohibited technique, yet\l"
  .string "being such a powerless trainer.\p"
  .string "But, I don't mean to detract from\n"
  .string "your abilities. You are clearly\l"
  .string "very skilled.$"


CapeBrink_Text_DH1::
  .string "Would you like me to teach {COLOR GREEN}Dark Hole?\n"
  .string "{COLOR RED}This can only be taught once.$"


CapeBrink_Text_DH2::
  .string "Who should I teach it to?$"


CapeBrink_Text_DH3::
  .string "It is done. I hope you find this\n"
  .string "move valuable.$"


CapeBrink_Text_DHDone::
  .string "Hmm, I'm unable to teach {COLOR GREEN}Dark Hole{COLOR RED}\n"
  .string "again if that's what you're looking\l"
  .string "for.\p"
  .string "Apologies...$"


