RandomPika_Text_1::
  .string "I'm a {COLOR GREEN}Yellow Shard{COLOR BLUE} collector!\p"
  .string "If you hand me one, I can\n"
  .string "exchange give a random costume\l"
  .string "{COLOR GREEN}Pikachu.$"


RandomPika_Text_2::
  .string "Ah! I see a {COLOR GREEN}Yellow Shard{COLOR BLUE}!\p"
  .string "Would you like to exchange it?$"


RandomPika_Text_AwOkay::
  .string "Well, come back if you change\n"
  .string "your mind.$"


RandomPika_Text_ReceivedPika::
  .string "{COLOR BLACK}{PLAYER} received a Pikachu!{COLOR BLUE}$"


Celadon_Text_ErikaCheck::
  .string "{COLOR BLACK}It appears to be closed...$"


Celadon_Text_IronHead1::
  .string "Have any hardheaded Pokémon?\p"
  .string "Perhaps you ought to teach them\n"
  .string "Iron Head!\p"
  .string "You're down, yeah?$"


Celadon_Text_IronHead2::
  .string "I hope you land a lot of flinches!$"


playrough_Text_1::
  .string "Oh, hi!\n"
  .string "I finally finished Pokémon.\p"
  .string "Not done yet? How about I teach\n"
  .string "you a good move?\p"
  .string "The move I have in mind is Play\n"
  .string "Rough.\p"
  .string "Kinda like your mom in bed!$"


playrough_Text_2::
  .string "It'll cost ya \$5000 though.$"


playrough_Text_3::
  .string "Which Pokémon should I teach\n"
  .string "Play Rough to?$"


playrough_Text_4::
  .string "Get rough and rowdy with these\n"
  .string "fellas.$"


playrough_Text_No::
  .string "You're not interested? Come see\n"
  .string "me if you change your mind.$"


playrough_Text_Wait::
  .string "...$"


playrough_Text_Poor::
  .string "...You don't have enough money.$"


coincasenugget_Text_3::
  .string "I used to give out{COLOR GREEN} Coin Cases{COLOR BLUE} to\n"
  .string "minors that approached me,\l"
  .string "but then it became illegal.\p"
  .string "You can have these instead.$"


coincasenugget_Text_4::
  .string "I can't stay a gambling addict...\p"
  .string "Take my money so I don't do it\n"
  .string "anymore...$"


coincasenugget_Text_5::
  .string "Game Corner fueled my gambling\n"
  .string "addiction in quarantine.\p"
  .string "It's been stuck with me ever\n"
  .string "since.$"


ivseller_Text_1::
  .string "Psst... I have a crazy proposition.\p"
  .string "I can max one of your Pokémon's\n"
  .string "IVs for \$350000.\p"
  .string "Or I can do a single stat for\n"
  .string "\$70000.\p"
  .string "It's crazy expensive, but this is\n"
  .string "technically illegal!\p"
  .string "How about it?$"


ivseller_Text_1_Hard::
  .string "Psst... I have a crazy proposition.\p"
  .string "I can max one of your Pokémon's\n"
  .string "IVs for free.\p"
  .string "Normally I charge money, but\n"
  .string "this service isn't as useful in\l"
  .string "{COLOR GREEN}Minimal Grinding Mode.{COLOR BLUE}\p"
  .string "How about it?$"


ivseller_Text_2::
  .string "Boo. You don't have enough money.\p"
  .string "Come back when you got stacks.$"


ivseller_Text_Op::
  .string "Don't you want OP Pokémon?\p"
  .string "Especially in a screwed up ROM hack\n"
  .string "like this?\p"
  .string "You can't get this anywhere else.$"


ivseller_Text_3::
  .string "Sweet. Who wants it?$"


ivseller_Text_4::
  .string "So, {STR_VAR_1} will have its IVs\n"
  .string "maxed. \$350000.$"


ivseller_Text_4_min::
  .string "So, {STR_VAR_1} will have its IVs\n"
  .string "maxed.$"


ivseller_Text_4_1::
  .string "So, {STR_VAR_1} will have its HP IVs\n"
  .string "maxed. It currently has {STR_VAR_2} HP\l"
  .string "IVs. It'll be \$70000.$"


ivseller_Text_4_1_min::
  .string "So, {STR_VAR_1} will have its HP IVs\n"
  .string "maxed. It currently has {STR_VAR_2} HP\l"
  .string "IVs.$"


ivseller_Text_4_2::
  .string "So, {STR_VAR_1} will have its Atk IVs\n"
  .string "maxed. It currently has {STR_VAR_2} Atk\l"
  .string "IVs. It'll be \$70000.$"


ivseller_Text_4_2_min::
  .string "So, {STR_VAR_1} will have its Atk IVs\n"
  .string "maxed. It currently has {STR_VAR_2} Atk\l"
  .string "IVs.$"


ivseller_Text_4_3::
  .string "So, {STR_VAR_1} will have its Def IVs\n"
  .string "maxed. It currently has {STR_VAR_2}Def\l"
  .string "IVs. It'll be \$70000.$"


ivseller_Text_4_3_min::
  .string "So, {STR_VAR_1} will have its Def IVs\n"
  .string "maxed. It currently has {STR_VAR_2}Def\l"
  .string "IVs.$"


ivseller_Text_4_4::
  .string "So, {STR_VAR_1} will have its Sp. Atk\n"
  .string "IVs maxed. It currently has {STR_VAR_2}\l"
  .string "Sp. Atk IVs. It'll be \$70000.$"


ivseller_Text_4_4_min::
  .string "So, {STR_VAR_1} will have its Sp. Atk\n"
  .string "IVs maxed. It currently has {STR_VAR_2}\l"
  .string "Sp. Atk IVs.$"


ivseller_Text_4_5::
  .string "So, {STR_VAR_1} will have its Sp. Def\n"
  .string "IVs maxed. It currently has {STR_VAR_2}\l"
  .string "Sp. Def IVs. It'll be \$70000.$"


ivseller_Text_4_5_min::
  .string "So, {STR_VAR_1} will have its Sp. Def\n"
  .string "IVs maxed. It currently has {STR_VAR_2}\l"
  .string "Sp. Def IVs.$"


ivseller_Text_4_6::
  .string "So, {STR_VAR_1} will have its Speed\n"
  .string "IVs maxed. It currently has {STR_VAR_2}\l"
  .string "Speed IVs. It'll be \$70000.$"


ivseller_Text_4_6_min::
  .string "So, {STR_VAR_1} will have its Speed\n"
  .string "IVs maxed. It currently has {STR_VAR_2}\l"
  .string "Speed IVs.$"


ivseller_Text_5::
  .string "Is that correct?$"


ivseller_Text_bust_1 ::
  .string "Heyyo welcome back Champ...$"


ivseller_Text_bust_2::
  .string "Uhh... whachu doing with that\n"
  .string "tracker?\p"
  .string "{COLOR BLACK}Reach for your Locater?$"


ivseller_Text_bust_3::
  .string "Yee, I knew we were good!\n"
  .string "Let's get started with ya...$"


ivseller_Text_bust_4::
  .string "GUYS, HE'S REACHING FOR IT!\n"
  .string "GET HIM!$"


ivseller_Text_bust_5::
  .string "{COLOR BLUE}Really now?\n"
  .string "We don't gotta do this, but fine.$"


Thug2DefeatTxt_Text::
  .string "Tsk, screw this!$"


Thug1DefeatTxt_Text::
  .string "But... why though...$"


ivseller_Text_bust_6::
  .string "{COLOR BLUE}You damn scumbag...\n"
  .string "We got a harmless business going on\n"
  .string "here, and you ruin it. For what?\p"
  .string "Being champion wasn't enough?\p"
  .string "Fine. You get what you deserve.$"


ThugBossDefeatTxt_Text::
  .string "What the hell...\n"
  .string "Betrayed... by you?$"


ivseller_Text_bust_call::
  .string "{COLOR BLACK}You free yourself from the thugs,\n"
  .string "and use the Locater to alert Officer Jenny!\p"
  .string "{COLOR BLUE}Whatever, kiddo.\p"
  .string "We were practically born in jail.$"


ivseller_Text_Wtf::
  .string "Yo, I don't operate on eggs.$"


ivseller_Text_Wait::
  .string "...$"


ivseller_Text_Done::
  .string "All done. Hope you enjoy pal.$"


ivseller_Text_Grind::
  .string "The grind don't stop, right?$"


amuletcoin_Text_3::
  .string "Life sure is tough in the city...\n"
  .string "I learned it the hard way,\n"
  .string "nothing is free!$"


amuletcoin_Text_4::
  .string "...You came from {COLOR GREEN}Pallet Town{COLOR BLUE}?!\p"
  .string "Holy cow!\p"
  .string "You'd make better use of this than\n"
  .string "me.$"


amuletcoin_Text_5::
  .string "The {COLOR GREEN}Amulet Coin{COLOR BLUE} ain't a money tree,\n"
  .string "but it's the next closest thing.$"


coinstory_Text_6::
  .string "Way back in the day, me and my\n"
  .string "squad here hustled money using the\l"
  .string "{COLOR GREEN}Amulet Coin{COLOR BLUE}.\p"
  .string "We'd keep note of all the weak train-\n"
  .string "ers that paid well, and repeatedly\l"
  .string "battled them with the {COLOR GREEN}VS Seeker{COLOR BLUE}.$"


coinstory_Text_7::
  .string "It was a scummy way of making money,\n"
  .string "taking money from weak children and\l"
  .string "what not.\p"
  .string "But, it was a business nonetheless.$"


coinstory_Text_8::
  .string "Eventually, the League caught wind\n"
  .string "of it, and rather than banning the\l"
  .string "{COLOR GREEN}Amulet Coin{COLOR BLUE}, they banned the {COLOR GREEN}VS\l"
  .string "Seeker{COLOR BLUE}.$"


coinstory_Text_9::
  .string "Funny, isn't it?\p"
  .string "Us chumps caused an item to be\n"
  .string "outlawed!\p"
  .string "It was a big hit for us at the time,\n"
  .string "but now we're making bank thanks to\l"
  .string "our new services.$"


coinstory_Text_10::
  .string "Just keep quiet what we're doing\n"
  .string "here, fam.$"


gamecornertms_Text_Hello::
  .string "May I help you?$"


gamecornertms_Text_Comeagain::
  .string "Please come again!$"


gamecornermons_Text_1::
  .string "We sell exclusive Pokémon!\p"
  .string "These Pokémon can be upgraded to\n"
  .string "their shiny forms for a steep\l"
  .string "price as well.\p"
  .string "Interested?$"


gamecornermons_Text_Text1::
  .string "Dratini$"


gamecornermons_Text_Text2::
  .string "Larvitar$"


gamecornermons_Text_Text3::
  .string "Beldum$"


gamecornermons_Text_Text4::
  .string "Bagon$"


gamecornermons_Text_Text5::
  .string "Riolu$"


gamecornermons_Text_Text6::
  .string "Rotom$"


gamecornermons_Text_Text7::
  .string "View More$"


gamecornermons_Text_Itllbe::
  .string "That'll be \$100000.$"


gamecornermons_Text_Itllberotom::
  .string "That'll be \$100000.$"


gamecornermons_Text_Whichpkmn::
  .string "Which Pokémon would you like?$"


gamecornermons_Text_Upgrade::
  .string "Would you like to upgrade it to\n"
  .string "its Shiny form?\p"
  .string "It'll double the price.$"


gamecornermons_Text_Haupgrade::
  .string "Would you like its Hidden Ability?$"


gamecornermons_Text_Shinytxt::
  .string "With a shiny upgrade, making it\n"
  .string "another \$100000...\p"
  .string "\$200000 total.$"


gamecornermons_Text_Rotomtxt::
  .string "With a shiny upgrade, making it\n"
  .string "another \$100000...\p"
  .string "\$200000 total.$"


gamecornermons_Text_Withha::
  .string "With its Hidden Ability...$"


gamecornermons_Text_Isitok::
  .string "This is default Rotom.\p"
  .string "Is that okay?$"


gamecornermons_Text_Correct::
  .string "Is this correct?$"


gamecornermons_Text_4::
  .string "Thank you partner!\p"
  .string "Enjoy!$"


gamecornermons_Text_Wait::
  .string "...$"


gamecornermons_Text_Poor::
  .string "...You don't have enough money.$"


gamecornermons_Text_Gotdratini::
  .string "You received a {COLOR GREEN}Dratini!$"


gamecornermons_Text_Gotlarvitar::
  .string "You received a {COLOR GREEN}Larvitar!$"


gamecornermons_Text_Gotbeldum::
  .string "You received a {COLOR GREEN}Beldum!$"


gamecornermons_Text_Gotbagon::
  .string "You received a {COLOR GREEN}Bagon!$"


gamecornermons_Text_Gotriolu::
  .string "You received a {COLOR GREEN}Riolu!$"


gamecornermons_Text_Gotrotom::
  .string "You received a {COLOR GREEN}Rotom!$"


gamecornermons_Text_GotToxel::
  .string "You received a {COLOR GREEN}Toxel!$"


giveNickname _Text::
  .string "Give it a Nickname?$"


gamecornermons2_Text_Text1::
  .string "Gible$"


gamecornermons2_Text_Text2::
  .string "Larvesta$"


gamecornermons2_Text_Text3::
  .string "Deino$"


gamecornermons2_Text_Text4::
  .string "Goomy$"


gamecornermons2_Text_Text5::
  .string "Jangmo-o$"


gamecornermons2_Text_Text6::
  .string "Dreepy$"


gamecornermons2_Text_Text7::
  .string "Floette-Eternal$"


gamecornermons3_Text_Text1::
  .string "Honedge$"


gamecornermons3_Text_Text2::
  .string "Toxel$"


gamecornermons3_Text_Text3::
  .string "Frigibax$"


gamecornermons3_Text_Text4::
  .string "Exit$"


gamecornermons2_Text_Itllbefloette::
  .string "That'll be \$50000.$"


gamecornermons2_Text_Whichpkmn::
  .string "Which Pokémon would you like?$"


gamecornermons2_Text_Shinytxt::
  .string "With a shiny upgrade, making it\n"
  .string "another \$100000...\p"
  .string "\$200000 total.$"


gamecornermons2_Text_Floettetxt::
  .string "With a shiny upgrade, making it\n"
  .string "another \$50000...\p"
  .string "\$100000 total.$"


gamecornermons2_Text_Isitok::
  .string "Floette-Eternal can't evolve.\p"
  .string "Is that okay?$"


gamecornermons2_Text_Correct::
  .string "Is this correct?$"


gamecornermons2_Text_4::
  .string "Thank you partner!\p"
  .string "Enjoy!$"


gamecornermons2_Text_Wait::
  .string "...$"


gamecornermons2_Text_Poor::
  .string "...You don't have enough money.$"


gamecornermons2_Text_Gotgible::
  .string "You received a {COLOR GREEN}Gible!$"


gamecornermons2_Text_GotLarvesta::
  .string "You received a {COLOR GREEN}Larvesta!$"


gamecornermons2_Text_GotDeino::
  .string "You received a {COLOR GREEN}Deino!$"


gamecornermons2_Text_GotGoomy::
  .string "You received a {COLOR GREEN}Goomy!$"


gamecornermons2_Text_Gotjangmo::
  .string "You received a {COLOR GREEN}Jangmo-o!$"


gamecornermons2_Text_Gotfloette::
  .string "You received a {COLOR GREEN}Floette-Eternal!$"


gamecornermons2_Text_GotDreepy::
  .string "You received a {COLOR GREEN}Dreepy!$"


gamecornermons2_Text_GotHonedge::
  .string "You received a {COLOR GREEN}Honedge!$"


gamecornermons2_Text_GotToxel::
  .string "You received a {COLOR GREEN}Toxel!$"


gamecornermons2_Text_GotFrigibax::
  .string "You received a {COLOR GREEN}Frigibax!$"


gardevoirite_Text_1::
  .string "Hey, you came to see me!\p"
  .string "I'm not thirsty like I was in\n"
  .string "the old games though.\p"
  .string "You can have this instead!$"


gardevoirite_Text_2::
  .string "That item Mega Evolves {COLOR GREEN}Alakazam{COLOR RED}!\p"
  .string "You'll need a {COLOR GREEN}Mega Ring{COLOR RED} for it\n"
  .string "to work though.$"


erika_Text_EncounterText::
  .string "{COLOR RED}Hello...\n"
  .string "Lovely weather, isn't it?\l"
  .string "It's so pleasant...\p"
  .string "...Oh, dear...\n"
  .string "I must have dozed off. Welcome.\p"
  .string "My name is Erika.\n"
  .string "I am the Leader of Celadon Gym.\p"
  .string "I am a student of the art of\n"
  .string "flower arranging.\p"
  .string "My Pokémon are solely of the\n"
  .string "Grass type.\p"
  .string "...Oh, I'm sorry, I had no idea that\n"
  .string "you wished to challenge me.\p"
  .string "Very well, but I shall not lose.$"


erika_Text_DefeatText::
  .string "Oh!\n"
  .string "I concede defeat.\l"
  .string "You are remarkably strong.\p"
  .string "I must confer on you the\n"
  .string "Rainbow Badge.$"


erika_Text_Givetm::
  .string "The Rainbow Badge allows\n"
  .string "you to use Strength outside\l"
  .string "of battle.\p"
  .string "Please also take this with you.$"


erika_Text_TMInfomsg::
  .string "TM19 contains Giga Drain.\p"
  .string "Half the damage it inflicts is\n"
  .string "drained to heal your Pokémon.\p"
  .string "Wouldn't you agree that it's a\n"
  .string "wonderful move?$"


erika_Text_Helloagain::
  .string "Oh hello there.\p"
  .string "...I see you've obtained the {COLOR GREEN}Mega Ring{COLOR RED}.\p"
  .string "Unfortunately, my Pokémon aren't look-\n"
  .string "ing to battle at the moment.\p"
  .string "You see, this {COLOR GREEN}Gloom{COLOR RED} I've been caring for\n"
  .string "has become terribly sick.$"


erika_Text_Helloend::
  .string "If you could bring me something\n"
  .string "that could help my {COLOR GREEN}Gloom{COLOR RED}, that would\l"
  .string "help tremendously.$"


erika_Text_Isit::
  .string "Oh my...\p"
  .string "This {COLOR GREEN}Medicine{COLOR RED}... is it for {COLOR GREEN}Gloom{COLOR RED}?!$"


erika_Text_Thankutext::
  .string "Oh my goodness!\p"
  .string "Thank you!\p"
  .string "Let me see if it helps {COLOR GREEN}Gloom{COLOR RED}.$"


erika_Text_Nothing::
  .string "...$"


erika_Text_Itworks::
  .string "{COLOR GREEN}Gloom{COLOR RED} is feeling great now!\p"
  .string "I couldn't thank you enough!\p"
  .string "Well, I'm up for a battle now!\p"
  .string "Are you ready?$"


erika_Text_No::
  .string "Oh, never mind then...$"


erika_Text_Info::
  .string "I hope your travels go safely, dear\n"
  .string "friend.$"


erika_Text_Snivy::
  .string "You received a {COLOR GREEN}Snivy{COLOR RED}!$"


erika_Text_StartBattle::
  .string "Very well, let's begin!$"


Erika_Text_DefeatText2::
  .string "Ah, you've got me again.$"


PostRematch _Text::
  .string "Thank you for the lovely\n"
  .string "battle, and for helping {COLOR GREEN}Gloom!{COLOR RED}\p"
  .string "Please, have this.$"


checkerikasabrina_Text_1::
  .string "{COLOR BLACK}I think I'd better get {COLOR GREEN}Erika{COLOR BLACK} and\n"
  .string "{COLOR GREEN}Sabrina's{COLOR BLACK} badge before proceeding.$"


FossilPokemon_Text_1::
  .string "Hi there. I'm just a huge fan\n"
  .string "of old Pokémon.\p"
  .string "So I collect fossil Pokémon!\n"
  .string "I'll exchange them for shards.\p"
  .string "Interested?$"


FossilPokemon_Text_Which::
  .string "Which fossil Pokémon would you\n"
  .string "like?$"


FossilPokemon_Text_Dont::
  .string "Hm, you don't have enough\n"
  .string "{COLOR GREEN}{STR_VAR_1}s{COLOR BLUE}.\p"
  .string "Come back with some {COLOR GREEN}{STR_VAR_1}s{COLOR BLUE}\n"
  .string "if you'd like a {COLOR GREEN}{STR_VAR_2}{COLOR BLUE}.$"


FossilPokemon_Text_Confirm ::
  .string "Okay, you'd like to exchange\n"
  .string "{COLOR GREEN}{STR_VAR_1}s{COLOR BLUE} for {COLOR GREEN}{STR_VAR_2}{COLOR BLUE},\l"
  .string "correct?$"


FossilReceive_Text::
  .string "You received a {COLOR GREEN}{STR_VAR_2}{COLOR BLUE}!$"


FossilThanks_Text::
  .string "Thank ya! Enjoy.$"


Celadon_Text_Frisk::
  .string "Are you looking to farm rare items?$"


Celadon_Text_Frisk2 ::
  .string "Leading with a Pokémon that has either\n"
  .string "Super Luck, Frisk, or Compound-eyes\l"
  .string "as their ability will boost the\l"
  .string "chance of wild Pokémon holding\l"
  .string "items!$"


IVPerfecterPreparemsg_Text_1::
  .string "Which stat should I perfect?$"


CeladonFlappleTrainers_Text_1::
  .string "Jeez... who would've thought a\n"
  .string "trip to Celadon would be so boring!$"


CeladonFlappleTrainers_Text_1_1::
  .string "Yeah... I didn't expect our dates\n"
  .string "to flake on us...\p"
  .string "It's quite unfortunate.$"


CeladonFlappleTrainers_Text_2::
  .string "For real... This is disappointing...$"


CeladonFlappleTrainers_Text_3::
  .string "That item in your bag...\n"
  .string "You got a Mega Ring don't you?\p"
  .string "Say... help us out here!\p"
  .string "We're just two super bored gals...\p"
  .string "Could you entertain us with a battle?$"


CeladonFlappleTrainers_Text_4::
  .string "Alright, no holding back!$"


CeladonFlappleTrainers_Text_Boring::
  .string "An uneventful vacation it is...$"


CeladonFlappleTrainers_Text_5::
  .string "{COLOR RED}Okay, I'll go next I'll go next!$"


flappletrainer1_Text_loss::
  .string "Woah, how unexpected!$"


flappletrainer2_Text_loss::
  .string "Heh, I guess I deserved that.$"


CeladonFlappleTrainers_Text_6::
  .string "{COLOR RED}Those were some battles!\n"
  .string "Sorry if it felt like we ganged\l"
  .string "up on you. We were just very\l"
  .string "eager to battle, sitting here doing\l"
  .string "nothing.\p"
  .string "Please, have one of our signature\n"
  .string "items!$"


CeladonFlappleTrainers_Text_7::
  .string "The {COLOR GREEN}Applite{COLOR RED} can actually Mega Evolve\n"
  .string "both Flapple and Appletun!\p"
  .string "Although they both have the same\n"
  .string "appearance, their stats and abilities\l"
  .string "are quite distinct!$"


CeladonFlappleTrainers8_Text::
  .string "And if that wasn't enough, you can\n"
  .string "have our favorite TM as well!$"


CeladonFlappleTrainers_Text_9::
  .string "I personally prefer {COLOR GREEN}Mega Appletun.\p"
  .string "{COLOR RED}Contrary Draco Meteor is so satisfy-\n"
  .string "ing!$"


CeladonSeviiEgg_Text_1::
  .string "{COLOR BLUE}Ah, {COLOR GREEN}{PLAYER}!$"


CeladonSeviiEgg_Text_2::
  .string "{COLOR BLUE}We've received an eggs that likely\n"
  .string "evolve to regional variants exclusive\l"
  .string "to the Sevii Islands!\p"
  .string "It's been reported that these variants\n"
  .string "can be quite powerful.\p"
  .string "Since you're quite the potent trainer,\n"
  .string "the professor thought it'd be good\l"
  .string "in your hands!\p"
  .string "Please, take it.$"


CeladonSeviiEgg_Text_3::
  .string "{COLOR BLUE}Well, it seems you don't have room.\p"
  .string "I'll be here until you make space.\p"
  .string "See you around!$"


Celadon_Text_ReceivedEgg::
  .string "{COLOR BLACK}You received an Egg!$"


CeladonSeviiEgg_Text_4::
  .string "{COLOR BLUE}Well, take care, {COLOR GREEN}{PLAYER}!$"


CeladonSeviiEgg_Text_5::
  .string "Ah, have you made room for the\n"
  .string "Seviian Egg?$"


CeladonSeviiEgg_Text_6::
  .string "...Hmm, seems like you still don't\n"
  .string "have room.\p"
  .string "I'll be here until you make space.\p"
  .string "See you around!$"


CeladonSeviiEgg_Text_7::
  .string "...Great! Please, take it.$"


Celadon_Text_Gambler1::
  .string "{COLOR BLUE}Hah! A minor! Disappointed you\n"
  .string "can't gamble? Lucky you, I've\l"
  .string "got quite the proposition.\p"
  .string "Slots here just don't really\n"
  .string "do it for me now.$"


Celadon_Text_Gambler2::
  .string "I love betting on Pokémon\n"
  .string "Battles!\p"
  .string "If you'd like, we can bet on a\n"
  .string "battle with a team of Metronome\l"
  .string "only Pokémon.\p"
  .string "What do you say?$"


Celadon_Text_10000::
  .string "\$10000$"


Celadon_Text_25000::
  .string "\$50000$"


Celadon_Text_50000::
  .string "\$100000$"


Celadon_Text_GamblerNo::
  .string "Not feeling lucky today eh?\p"
  .string "Well, just know I'm always ready\n"
  .string "to gamble!$"


Celadon_Text_Gambler_LetsGo::
  .string "Haha! Let's see who's side\n"
  .string "lady luck is on!$"


BetHowMuch_Text::
  .string "How much would you like to\n"
  .string "bet?$"


Gamble_Text_NotEnough::
  .string "Woah! Don't gamble more than you have,\n"
  .string "kid!\p"
  .string "You're something else!$"


Celadon_Text_YouLost::
  .string "Well, I'll be keeping your money!\p"
  .string "Although you're probably going\n"
  .string "to reset to your last save\l"
  .string "like a little cheater, so this\l"
  .string "basically never happened.$"


Celadon_Text_YouWin::
  .string "Agh, you got me you got me!\p"
  .string "... lucky bastard...$"


Celadon_Text_Here::
  .string "Here's your dang money...$"


CeladonLoseBattle_Text::
  .string "Hah! Outplayed!$"


CeladonWinbattle_Text::
  .string "Tch, call it beginner's luck...$"


ImAlwaysHere_Text::
  .string "I'll be here if you\n"
  .string "still want to go.$"


Celadon_Text_LucarioMan1 ::
  .string "This is my trusted pal, {COLOR GREEN}Lucario.\p"
  .string "{COLOR BLUE}I got it from the Game Corner\n"
  .string "as a {COLOR GREEN}Riolu {COLOR BLUE}when I was little.\p"
  .string "After growing together through\n"
  .string "tough times, he evolved.$"


Celadon_Text_Lucario::
  .string "Lucario!$"


Celadon_Text_Azumarill::
  .string "Azu!$"


Celadon_Text_Empoleon::
  .string "Empoleon!$"


Celadon_Text_Togekiss::
  .string "Togekiss!$"


giovanni1_Text_Giovannitxt1::
  .string "So! I must say, I am impressed you\n"
  .string "got here.\p"
  .string "Team Rocket captures Pokémon from\n"
  .string "around the world.\p"
  .string "They're important tools for keeping\n"
  .string "our criminal enterprise going.\p"
  .string "I am the leader, {COLOR GREEN}Giovanni!{COLOR BLUE}\p"
  .string "For your insolence, you will feel a\n"
  .string "world of pain!$"


giovanni1_Text_Giovanniloss::
  .string "What!\n"
  .string "This can't be!$"


giovanni1_Text_Giovannitxt2::
  .string "I see that you raise Pokémon with\n"
  .string "utmost care.\p"
  .string "A child like you would never\n"
  .string "understand what I hope to achieve.\p"
  .string "I shall step aside this time!\p"
  .string "I hope we meet again...$"


Celadon_Text_RotomChanger::
  .string "{COLOR BLACK}...Your {COLOR GREEN}Rotom{COLOR BLACK} is reacting to this\n"
  .string "mysterious machine!\p"
  .string "It seems like it wants to change\n"
  .string "form...$"


WhichRotomForm_Text::
  .string "Which form should {COLOR GREEN}Rotom{COLOR BLACK} change to?$"


Celadon_Text_NotRotom::
  .string "{COLOR BLACK}That's not a {COLOR GREEN}Rotom...$"


Celadon_Text_SameForm::
  .string "...That's the same {COLOR GREEN}Rotom{COLOR BLACK} form.$"


RotomNorm_Text::
  .string "Rotom$"


RotomWash_Text::
  .string "Rotom-Wash$"


RotomMow_Text::
  .string "Rotom-Mow$"


RotomFrost_Text::
  .string "Rotom-Frost$"


RotomHeat_Text::
  .string "Rotom-Heat$"


RotomFan_Text::
  .string "Rotom-Fan$"


Celadon_Text_RotomChange_Down::
  .string "...{COLOR GREEN}Rotom{COLOR BLACK} form change complete!$"


MysteriousMachine_Text_Text::
  .string "{COLOR BLACK}What is this machine?\n"
  .string "Better not mess around with it!$"


Kangakshan_Text::
  .string "Kangakshan!$"


Celadon_Text_LucarioMan2::
  .string "Ah, a fellow {COLOR GREEN}Lucario{COLOR BLUE} enjoyer.$"


Celadon_Text_LucarioMan2_1::
  .string "Tell me, what is your favorite\n"
  .string "{COLOR GREEN}Lucario {COLOR BLUE}set?$"


Physical_Text_Lucario::
  .string "Physical Sweeper$"


Special_Text_Lucario::
  .string "Special Sweeper$"


gText_Text_Mixed_Lucario::
  .string "Mixed Attacker$"


Lucario_Text_PickedPhysical::
  .string "Mmm... Physical sweeping Lucario\n"
  .string "is excellent with Swords Dance and a\l"
  .string "strong 120 Base Power Move in\l"
  .string "Close Combat.\p"
  .string "A fine choice.$"


Lucario_Text_PickedSpecial::
  .string "Mmm... Special sweeping Lucario\n"
  .string "is great with Nasty Plot and\l"
  .string "is an effective use of its iconic\l"
  .string "move, Aura Sphere. A decent choice.$"


Lucario_Text_PickedMixed::
  .string "Mmm... Mixed attacking Lucario\n"
  .string "is useful for hitting the\l"
  .string "enemy at its weakest point.\p"
  .string "Not my preference, but I can\n"
  .string "get behind it.$"


Lucario_Text_Flaws::
  .string "With that being said,\n"
  .string "base {COLOR GREEN}Lucario {COLOR BLUE}has its flaws.$"


Lucario_Text_Flaws2::
  .string "What would you say its biggest\n"
  .string "flaw is?$"


PowerCreep_Text::
  .string "Power Creep$"


4MSS_Text::
  .string "4 Move Slot Syndrome$"


SpeedTier_Text::
  .string "Bad Speed Tier$"


Lucario_Text_PickedPowerCreep::
  .string "Yes... with the power levels\n"
  .string "rising each Generation Lucario\l"
  .string "found itself outclassed...$"


Lucario_Text_4mss::
  .string "Yes... {COLOR GREEN}Lucario{COLOR BLUE} sometimes struggles\n"
  .string "to get what it wants with 4\l"
  .string "move slots...$"


Lucario_Text_SpeedTier::
  .string "Mm... even with its strong priority\n"
  .string "moves, a 90 Base Speed isn't the\l"
  .string "most desirable for a sweeper.$"


Lucario_Text_DoYouThink::
  .string "Tell me then, do you think\n"
  .string "{COLOR GREEN}Mega Lucario{COLOR BLUE} is busted?$"


Lucario_Text_NeverMind::
  .string "Oh, never mind then...$"


Lucario_Text_Yeppers::
  .string "Of course!\n"
  .string "Here, I noticed yours is missing\l"
  .string "a Mega Stone.$"


Lucario_Text_amazingMega::
  .string "{COLOR GREEN}Mega Lucario{COLOR BLUE} is a really\n"
  .string "amazing Mega.\p"
  .string "It gets higher base Speed and\n"
  .string "an insane ability Adaptability$"


