ceruleancavelevelscript_Text_1::
  .string "{COLOR BLUE}Hm, nothing suspicious so far...$"


ceruleancavelevelscript_Text_2::
  .string "{COLOR RED}Well well, if it isn't the two scrubs\n"
  .string "back in Silph Co.$"


ceruleancavelevelscript_Text_3::
  .string "{COLOR BLUE}Agh! Team Rocket!\p"
  .string "I knew it!\p"
  .string "What do you think you're doing?!$"


ceruleancavelevelscript_Text_4::
  .string "{COLOR RED}Ariana: It doesn't concern you.\p"
  .string "I'll have you taken care of.$"


ceruleancavelevelscript_Text_5::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}, go on\n"
  .string "ahead!\p"
  .string "I'll catch up with you later!$"


ceruleancavelevelscript_Text_6::
  .string "{COLOR RED}Tsk, whatever.\p"
  .string "You won't be able to stop the boss\n"
  .string "anyway.$"


arianaceruelancave_Text_1::
  .string "{COLOR GREEN}Mawile, {COLOR RED}use Play Rough!$"


arianaceruelancave_Text_2::
  .string "What the hell are you looking at?\p"
  .string "I'll take care of you after.$"


brendanceruleancave_Text_1::
  .string "{COLOR GREEN}Sceptile, {COLOR BLUE}use Focus Blast!$"


brendanceruleancave_Text_2::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}, go on\n"
  .string "ahead!\p"
  .string "I'll catch up with you later!$"


ceruleangrunt4_Text_EncounterText::
  .string "The boss's plan?\p"
  .string "My guess is as good as yours.$"


ceruleangrunt4_Text_DefeatText::
  .string "Being a good trainer...\n"
  .string "Couldn't be me.$"


ceruleangrunt4_Text_AfterBattle::
  .string "The boss's plan?\p"
  .string "My guess is as good as yours.$"


ceruleangrunt3_Text_EncounterText::
  .string "Aw, jeez.\p"
  .string "I remember you...$"


ceruleangrunt3_Text_DefeatText::
  .string "Must be nice being strong.$"


ceruleangrunt3_Text_AfterBattle::
  .string "Must be nice being the protag-\n"
  .string "onist.$"


ceruleangrunt2_Text_EncounterText::
  .string "I'm just following orders.$"


ceruleangrunt2_Text_DefeatText::
  .string "Well, no surprise there.$"


ceruleangrunt2_Text_AfterBattle::
  .string "I'm just here as I was promised\n"
  .string "some speedb.$"


ceruleangrunt1_Text_EncounterText::
  .string "Hey, you ought to turn back.$"


ceruleangrunt1_Text_DefeatText::
  .string "Crushed by a kid,\n"
  .string "as usual.$"


ceruleangrunt1_Text_AfterBattle::
  .string "Most Team Rocket members left\n"
  .string "after the latest ordeal.\p"
  .string "I have no idea why I'm still\n"
  .string "here to be honest.$"


ceruleanarcherariana_Text_1::
  .string "{COLOR BLUE}Hey, looks like we caught up.$"


ceruleanarcherariana_Text_2::
  .string "{COLOR RED}There's no escape.\p"
  .string "Your friend isn't here to stop us\n"
  .string "this time.$"


ceruleanarcherariana_Text_3::
  .string "{COLOR BLUE}Don't worry, he's safe.\p"
  .string "He's gone to the Pokémon center after\n"
  .string "our skirmish.$"


ceruleanarcherariana_Text_4::
  .string "{COLOR RED}You know...$"


ceruleanarcherariana_Text_5::
  .string "{COLOR RED}We're gonna cut the crap.\p"
  .string "We honestly don't know what the boss\n"
  .string "is up to ourselves.\p"
  .string "After his last defeat against you...\p$"


ceruleanarcherariana_Text_6::
  .string "{COLOR BLUE}He's definitely become unhinged.\p"
  .string "Anyway...$"


ceruleanarcherariana_Text_7::
  .string "{COLOR BLUE}He's never been one to tell us\n"
  .string "much, so we're basically in the dark\l"
  .string "about what this mission is...$"


ceruleanarcherariana_Text_8::
  .string "{COLOR RED}But... orders are orders.$"


ceruleanarcherariana_Text_10::
  .string "{COLOR BLUE}We're loyal to the boss,\n"
  .string "perhaps to a fault.\p"
  .string "You aren't getting to him.$"


ceruleanarcherariana_Text_11::
  .string "{COLOR RED}Well... here goes.$"


ceruleanarcherariana_Text_12::
  .string "{COLOR BLUE}You might be the strongest trainer\n"
  .string "I've ever faced.\p"
  .string "Perhaps you may be able to\n"
  .string "talk some sense into our boss...\p"
  .string "It'd be nice if he could have some\n"
  .string "faith in us, but he won't listen to\l"
  .string "me.$"


ceruleanarcherariana_Text_13::
  .string "{COLOR RED}Not me, either.\p"
  .string "But, we're still concerned for him.\p"
  .string "We're really sorry for the trouble.\p"
  .string "And please, have this.$"


ceruleanarcherariana_Text_14::
  .string "{COLOR BLUE}I would apologize too,\n"
  .string "but I know we were always just\l"
  .string "pushovers for you...\p"
  .string "...Hah! You're smiling.\p"
  .string "I knew it.\p"
  .string "From me, then.$"


ceruleanarcherariana_Text_15::
  .string "{COLOR BLUE}If he's doing what I think\n"
  .string "he's doing, you may be in trouble...\p"
  .string "But, we have faith in you.\p"
  .string "Please, stop our boss...$"


ceruleanarcherariana_Text_16::
  .string "{COLOR RED}Good luck.$"


ceruleanarcherariana_Text_Archerloss::
  .string "That's how it be...$"


ceruleanarcherariana_Text_Arianaloss::
  .string "Heh...\n"
  .string "I'm actually impressed.$"


healstoptheboss_Text_1::
  .string "Please... stop the boss.$"


ceruleangiovanni_Text_1::
  .string "{COLOR BLUE}I see you've come to stop me\n"
  .string "yet again...$"


ceruleangiovanni_Text_2::
  .string "{COLOR BLUE}Unfortunately, you won't be the hero\n"
  .string "this time.\p"
  .string "You're too late.$"


ceruleangiovanni_Text_3::
  .string "{COLOR GREEN}Mewtwo!{COLOR BLUE} You're mine!$"


ceruleangiovanni_Text_4::
  .string "{COLOR BLACK}Mew!$"


ceruleangiovanni_Text_5::
  .string "{COLOR BLUE}Master Ball, go!$"


ceruleangiovanni_Text_6::
  .string "...$"


ceruleangiovanni_Text_Defeated::
  .string "W-what?!\n"
  .string "Impossible...$"


ceruleangiovanni_Text_7::
  .string "{COLOR BLUE}Aha! The Master Ball my scientists\n"
  .string "made works!\p"
  .string "And attaching this Mega Stone that\n"
  .string "we've worked hard on...\p"
  .string "I'm practically invincible!$"


ceruleangiovanni_Text_8::
  .string "{COLOR BLUE}You still dare to stop me\n"
  .string "knowing I have {COLOR GREEN}Mega Mewtwo{COLOR BLUE}?\p"
  .string "Well, the honor is mine, you insolent\n"
  .string "child!$"


ceruleangiovanni_Text_8_2 ::
  .string "{COLOR GREEN}???{COLOR BLUE}: Woah, things are getting out\n"
  .string "of hand here...$"


ceruleangiovanni_Text_8_3 ::
  .string "{COLOR GREEN}Lance{COLOR BLUE}: Hi there, just the champion\n"
  .string "stopping by to help put an end\l"
  .string "to this mess.$"


ceruleangiovanni_Text_8_4 ::
  .string "{COLOR GREEN}Giovanni{COLOR BLUE}: Hm, no matter.\n"
  .string "I can't possibly be stopped with\l"
  .string "Mega Mewtwo.$"


ceruleangiovanni_Text_8_5 ::
  .string "{COLOR GREEN}Lance{COLOR BLUE}: Sorry, {PLAYER}, was it?\n"
  .string "I came here rather short of notice,\l"
  .string "so I don't have my best Pokémon on me.\p"
  .string "You'll have to help me out here.$"


ceruleangiovanni_Text_8_6 ::
  .string "{COLOR GREEN}Giovanni{COLOR BLUE}: Have at me then, you fools!$"


ceruleangiovanni_Text_9::
  .string "{COLOR BLUE}Even with {COLOR GREEN}Mega Mewtwo{COLOR BLUE},\n"
  .string "I've fallen by your hands.\p"
  .string "I...$"


ceruleangiovanni_Text_Awaydialogue::
  .string "{COLOR BLUE}I am truly humbled.\p"
  .string "My plan for world domination is\n"
  .string "but a dream.$"


ceruleangiovanni_Text_10::
  .string "{COLOR BLUE}I threw aside family for this...\p"
  .string "Abandoned my wife,\n"
  .string "even my own son...\p"
  .string "Despite my defeat at Silph Co,\n"
  .string "I couldn't give up on my plan.$"


ceruleangiovanni_Text_11::
  .string "{COLOR BLUE}I admit, I was a victim of the\n"
  .string "sunk-cost fallacy...\p"
  .string "But, I've given up literally every-\n"
  .string "thing for this...$"


ceruleangiovanni_Text_12::
  .string "{COLOR GREEN}Archer and Ariana{COLOR BLUE}: Boss!$"


ceruleangiovanni_Text_13::
  .string "{COLOR GREEN}Giovanni{COLOR BLUE}: Wha...\n"
  .string "Archer, Ariana?$"


ceruleangiovanni_Text_14::
  .string "{COLOR GREEN}Archer{COLOR BLUE}: Not everything, sir.$"


ceruleangiovanni_Text_15::
  .string "{COLOR RED}You still have us!\p"
  .string "Please, sir, have faith in us...$"


ceruleangiovanni_Text_16::
  .string "{COLOR GREEN}Archer{COLOR BLUE}: We've stuck with you\n"
  .string "through thick and thin boss, you\l"
  .string "could learn to rely on us,\l"
  .string "even if just a little...$"


ceruleangiovanni_Text_17::
  .string "{COLOR RED}Could you have any doubt\n"
  .string "on our loyalty?\p"
  .string "Ever since you took us in\n"
  .string "when we were lowly children, with\l"
  .string "no home to go to...$"


ceruleangiovanni_Text_18::
  .string "{COLOR BLUE}You're truly family to us!\p"
  .string "More than just our boss!$"


ceruleangiovanni_Text_19::
  .string "{COLOR RED}Although we don't agree with\n"
  .string "everything you do, we will stand by\l"
  .string "you no matter what.$"


ceruleangiovanni_Text_20::
  .string "{COLOR GREEN}Giovanni{COLOR BLUE}: You two...$"


ceruleangiovanni_Text_21::
  .string "{COLOR BLUE}I'm sorry...\p"
  .string "My crude ambitions have blinded\n"
  .string "me...$"


ceruleangiovanni_Text_22::
  .string "{COLOR BLUE}You guys are more than family.\p"
  .string "We sh-$"


ceruleangiovanni_Text_23::
  .string "{COLOR BLUE}Wha?!\p"
  .string "Mewtwo escaped out of my Master\n"
  .string "Ball!$"


ceruleangiovanni_Text_24::
  .string "{COLOR BLACK}Mewtwo: {PLAYER}...\p"
  .string "When you are worthy,\n"
  .string "please return to me.$"


e4check_Text_1::
  .string "{COLOR BLACK}Mewtwo: No {PLAYER}...\p"
  .string "You are not worthy yet.$"


MewtwoBattle_Text::
  .string "I see you've returned,\n"
  .string "even more capable.\p"
  .string "Fine, let me unleash my full\n"
  .string "potential to see if you're truly\l"
  .string "worthy!$"


KubfuMaster_Text_1 ::
  .string "Hi there. I've been training here\n"
  .string "to try and chase the glory my grand-\l"
  .string "father {COLOR GREEN}Mustard{COLOR BLUE} once held.\p"
  .string "A while ago in the Galar region he\n"
  .string "held his status as Champion for\l"
  .string "over 15 years.\p"
  .string "As his greatest prodigy I've always\n"
  .string "wanted to live up his standards...\p"
  .string "Yet, I'm still so far away.$"


KubfuMaster_Text_2::
  .string "I saw you completely dismantle a\n"
  .string "formidable foe with the help of the\l"
  .string "one-and-only,{COLOR GREEN} Lance!\p"
  .string "{COLOR BLUE}You must be a worthy training\n"
  .string "partner!\p"
  .string "So, what do you say?\p"
  .string "Can you help me in my quest?$"


KubfuMaster_Text_3::
  .string "No worries.\p"
  .string "I shall continue my training.$"


KubfuMaster_Text_PreFight::
  .string "Very well then.\n"
  .string "I'm giving it my all!$"


KubfuMaster_Text_FightLoss::
  .string "Hm, I guess that's a wrap.$"


KubfuMaster_Text_4::
  .string "That was a well fought battle.\p"
  .string "Please, have my Grandpa's sig-\n"
  .string "nature Pokémon.$"


ReceivedKubfu_Text::
  .string "You received a {COLOR GREEN}Kubfu!{COLOR BLUE}$"


KubfuMaster_Text_GoodLuck::
  .string "{COLOR GREEN}Kubfu{COLOR BLUE} can evolve into two separate\n"
  .string "forms using either the Water or\l"
  .string "Dusk Stone.\p"
  .string "Both are very capable Pokémon,\n"
  .string "even in the hands of the most\l"
  .string "irresponsible trainer.$"


KubfuMaster_Text_DoneForToday::
  .string "Well, that's it from me for today.\p"
  .string "Talk to me again tomorrow,\n"
  .string "and I may be ready to spar again.$"


KubfuMaster_Text_DownAgain::
  .string "Hello again! Are you here to spar?\p"
  .string "I do have one last {COLOR GREEN}Kubfu\n"
  .string "to offer if you end up victorious.\p"
  .string "What do you say?$"


KubfuMaster_Text_5::
  .string "Impressive, I never stood a chance!\p"
  .string "Yet, I do feel new know-\n"
  .string "ledge coming to light.\p"
  .string "Please take one, yet again!$"


KubfuMaster_Text_DownAgain2::
  .string "Welcome back, partner!\n"
  .string "Are you here to spar?\p"
  .string "Unfortunately, I have no {COLOR GREEN}Kubfus{COLOR BLUE}\n"
  .string "left to offer.\p"
  .string "Still, I hope you find value in\n"
  .string "battling with me!\p"
  .string "What do you say?$"


KubfuMaster_Text_5_2::
  .string "Ha ha ha! As expected!\n"
  .string "But, i still find losing to you\l"
  .string "worthwhile.\p"
  .string "Well, I at least have these\l"
  .string "to give.$"


