Cerulean_Text_Haircut1::
  .string "Hi, I can groom one of your\n"
  .string "Pokémon.\l"
  .string "For only \$500!\p"
  .string "Does that sound good?$"


Cerulean_Text_Haircut2::
  .string "Great! Who shall I groom?$"


Cerulean_Text_Haircut3 ::
  .string "Alright, let's get {STR_VAR_1}\n"
  .string "looking nice and spiffy.$"


Cerulean_Text_Haircut4::
  .string "I'm done grooming for today.\p"
  .string "Come back tomorrow though!$"


Cerulean_Text_Haircut5::
  .string "There you go!\p"
  .string "{STR_VAR_1} seems pleased.\p"
  .string "As for the payment...$"


Cerulean_Text_Haircut6::
  .string "Thank you!\p"
  .string "Please, come back tomorrow!$"


Cerulean_Text_Haircut7::
  .string "That's not enough money...$"


Cerulean_Text_Happiness1::
  .string "Hello. I can evaluate your\n"
  .string "Pokémon's happiness.$"


Cerulean_Text_Happiness2::
  .string "Your {STR_VAR_1}'s happiness\n"
  .string "value is {STR_VAR_2}.$"


misty_Text_EncounterText::
  .string "Hi, you're a new face!\p"
  .string "Only those trainers who have a\n"
  .string "policy about Pokémon can turn pro.\p"
  .string "What is your approach when you\n"
  .string "catch and train Pokémon?\p"
  .string "My policy is an all-out offensive\n"
  .string "with Water-type Pokémon!$"


misty_Text_DefeatText::
  .string "Wow!\n"
  .string "You're too much!\p"
  .string "All right!\p"
  .string "You can have the Cascade Badge to\n"
  .string "show you beat me.$"


misty_Text_Givetm::
  .string "The Cascade Badge allows you\n"
  .string "to use Cut anytime,\l"
  .string "even out of battle.\p"
  .string "You can Cut down small trees to\n"
  .string "open new pathways.\p"
  .string "You can also have my favorite TM.$"


misty_Text_TMInfomsg::
  .string "TM03 teaches Flip Turn.\p"
  .string "Use it on an aquatic Pokémon!$"


misty_Text_Helloagain::
  .string "Oh hey! Welcome back!\p"
  .string "You've returned at the nick of time!\p"
  .string "My Pokémon and I have actually been\n"
  .string "dying for a rematch.\p"
  .string "Although you already have my badge,\n"
  .string "I have special items to give as a\l"
  .string "reward.\p"
  .string "What do you say?$"


misty_Text_Comeback::
  .string "Oh... alright then.\p"
  .string "When you're ready, please do come\n"
  .string "back.$"


misty_Text_PostGame1::
  .string "Well, well. You're back again!\p"
  .string "You know what they say, third\n"
  .string "time's the charm.\p"
  .string "You up for another battle?$"


misty_Text_PostGame2::
  .string "This time there's no holding back!$"


misty_Text_ThirdDefeat::
  .string "Okay, okay.\n"
  .string "You're the real deal!$"


misty_Text_PostGame3::
  .string "You're a tough cookie alright.\p"
  .string "Thanks for entertaining me,\n"
  .string "I'm sure you knew I'd be a\l"
  .string "pushover.\p"
  .string "To thank you for your time,\n"
  .string "please, have this!$"


misty_Text_PostGame4::
  .string "Did you notice?\n"
  .string "My {COLOR GREEN}Drednaw{COLOR RED} has special access\l"
  .string "to Shell Smash!\p"
  .string "In its Mega Form, it rivals {COLOR GREEN}Mega\n"
  .string "Blastoise{COLOR RED} as one of the best Shell\l"
  .string "Smash users.\p"
  .string "You'd be silly not to try it,\n"
  .string "here!$"


Misty_Text_Drednaw::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Drednaw!{COLOR BLACK}$"


misty_Text_Battle::
  .string "Cool! We're going all out this time!\p"
  .string "Prepare yourself!$"


Misty_Text_RematchDoneDone::
  .string "You've inspired me to keep training.\p"
  .string "When I'm satisfied, I'd love\n"
  .string "to hit the road and travel...$"


misty_Text_Seconddefeat::
  .string "Washed again...$"


misty_Text_Won2text::
  .string "As I thought, you're a super talent-\n"
  .string "ed trainer! As promised, here you go.$"


misty_Text_Info::
  .string "{COLOR GREEN}Mega Gyarados{COLOR RED} is a huge threat.\p"
  .string "It changes from Flying to Dark type,\n"
  .string "and boasts an even higher Attack\l"
  .string "stat!\p"
  .string "The Pokémon I've given is {COLOR GREEN}Finizen,\n"
  .string "{COLOR RED}a seemingly weak Water-type with\l"
  .string "a powerful evolved form.\p"
  .string "With these, you should be able to\n"
  .string "reach greater heights!$"


misty_Text_Finizen::
  .string "You received a {COLOR GREEN}Finizen!$"


WhatPokemonItIs_Text::
  .string "{STR_VAR_1}, {STR_VAR_2},\n"
  .string "[BUFFER3].$"


newdaycare_Text_Intro::
  .string "I'm the Day-Care Man.\p"
  .string "I help take care of the precious\n"
  .string "Pokémon of trainers.\p"
  .string "If you'd like me to raise your\n"
  .string "Pokémon, have a word with my wife.$"


newdaycare_Text_Ahitsyou::
  .string "Ah, it's you!\p"
  .string "We were raising your Pokémon, and\n"
  .string "my goodness, were we surprised!\p"
  .string "Your Pokémon had an egg!\p"
  .string "We don't know how it got there,\n"
  .string "but your Pokémon had it.\p"
  .string "You do want it, yes?$"


newdaycare_Text_Ireallywill::
  .string "I really will keep it.\n"
  .string "You do want this, yes?$"


newdaycare_Text_Illkeepit::
  .string "Well then, I'll keep it.\n"
  .string "Thanks!$"


newdaycare_Text_Singlemonmsg::
  .string "Ah, it's you! Good to see you.\n"
  .string "Your {STR_VAR_1}'s doing fine.$"


newdaycare_Text_Twodoingfine::
  .string "Ah, it's you! Your {STR_VAR_1} and\n"
  .string "{STR_VAR_2} are doing fine.$"


newdaycare_Text_Noroom::
  .string "You have no room for it...\n"
  .string "Come back when you've made room.$"


newdaycare_Text_Receiveeggmsg::
  .string "{PLAYER} received the Egg from\n"
  .string "the Day-Care Man.$"


newdaycare_Text_Takegoodcare::
  .string "Take good care of it.$"


Cerulean_Text_NewThiefInfo::
  .string "The move Thief automatically adds\n"
  .string "the stolen item to the bag.\p"
  .string "Convenient, right?$"


Cerulean_Text_RedShardInfo::
  .string "I caught a Slugma earlier and it \n"
  .string "was holding a {COLOR GREEN}Red Shard{COLOR BLUE}!\n"
  .string "Not sure what to do with this, though...$"


redogaryrival_Text_Startmsg::
  .string "{RIVAL}: Yo! {COLOR GREEN}{PLAYER}{COLOR BLUE}!\p"
  .string "You're still struggling along back\n"
  .string "here?\p"
  .string "I'm doing great! I caught a bunch\n"
  .string "of strong and smart Pokémon!\p"
  .string "Here, let me see what you caught,\n"
  .string "{PLAYER}!$"


redogaryrival_Text_Billmsg::
  .string "{RIVAL}: Hey, guess what?\p"
  .string "I went to Bill's and got him to\n"
  .string "show me his rare Pokémon.\p"
  .string "That added a lot of pages to my\n"
  .string "Pokédex!\p"
  .string "After all, Bill's world famous as a\n"
  .string "Pokémaniac.\p"
  .string "He invented the Pokémon Storage\n"
  .string "System on PC, too.\p"
  .string "Since you're using his system,\n"
  .string "you should go thank him.\p"
  .string "Well, I better get rolling!\n"
  .string "Smell ya later!$"


redogaryrival_Text_Apresent::
  .string "Oh, yeah, right.\p"
  .string "I feel sorry for you. No, really.\n"
  .string "You're always plodding behind me.\p"
  .string "So here, I'll give you a little\n"
  .string "present as a favor.$"


redogaryrival_Text_Chattygossip::
  .string "A slow little slob like you...\p"
  .string "This item will help you travel to\n"
  .string "cities instantly so you'll finally be\l"
  .string "able catch up to me.\p"
  .string "I have an extra, so take it as a\n"
  .string "consolation prize.\p"
  .string "All right, this time I really am\n"
  .string "gone. Smell ya!$"


redogaryrival_Text_Uwonalready::
  .string "Hey!\n"
  .string "Take it easy!\l"
  .string "You won already!$"


trdigredo_Text_TRMessage1::
  .string "Hey! Stay out!\n"
  .string "It's not your yard!\p"
  .string "...Huh?\n"
  .string "Me?\p"
  .string "I'm an innocent bystander!\n"
  .string "Don't you believe me?$"


trdigredo_Text_PostTRBattle::
  .string "Grunt: Stop! I give up!\n"
  .string "I'll leave quietly!$"


trdigredo_Text_OkIgiveback::
  .string "...Okay.\n"
  .string "I'll return the TM I stole.$"


trdigredo_Text_RecoveredTM::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLACK} recovered TM28 from\n"
  .string "the Team Rocket Grunt.$"


trdigredo_Text_ILeave::
  .string "{COLOR BLUE}I better get moving!\n"
  .string "Bye!$"


cerulean_Text_Hello::
  .string "{COLOR BLUE}May I help you?$"


ceruleantms_Text_Comeagain::
  .string "Come again!$"


TM87Exchange_Text::
  .string "TM87 Swagger - Tiny Mushroom$"


TM88Exchange_Text::
  .string "TM88 Pluck   - Blue Shard$"


TM108Exchange_Text::
  .string "TM108 Snarl  - Red Shard$"


TM111Exchange_Text::
  .string "TM111 Smack Down - Yellow Shard$"


TM119Exchange_Text::
  .string "TM1119 Coaching - Big Mushroom$"


TM87ExchangeSOLD_Text::
  .string "TM87 Swagger - {COLOR RED}SOLD$"


TM88ExchangeSOLD_Text::
  .string "TM88 Pluck   - {COLOR RED}SOLD$"


TM108ExchangeSOLD_Text::
  .string "TM108 Snarl  - {COLOR RED}SOLD$"


TM111ExchangeSOLD_Text::
  .string "TM111 Smack Down - {COLOR RED}Yellow Shard$"


TM119ExchangeSOLD_Text::
  .string "TM1119 Coaching - {COLOR RED}SOLD$"


GaveClerkOneItem_Text::
  .string "{COLOR BLACK}You gave the clerk a {COLOR GREEN}{STR_VAR_1}...$"


ThisIsTM87_Text::
  .string "This is {COLOR GREEN}TM87 Swagger.\n"
  .string "{COLOR BLUE}I'll need a {COLOR GREEN}Tiny Mushroom{COLOR BLUE} for\l"
  .string "that.\p"
  .string "Would you like to exchange?$"


ThankyouComeAgain_Text::
  .string "Thank you come again!$"


ThisIsTM88_Text::
  .string "This is {COLOR GREEN}TM88 Pluck.\n"
  .string "{COLOR BLUE}I'll need a {COLOR GREEN}Blue Shard{COLOR BLUE} for that.\p"
  .string "Would you like to exchange?$"


ThisIsTM108_Text::
  .string "This is {COLOR GREEN}TM108 Snarl.\n"
  .string "{COLOR BLUE}I'll need a {COLOR GREEN}Red Shard{COLOR BLUE} for that.\p"
  .string "Would you like to exchange?$"


ThisIsTM111_Text::
  .string "This is {COLOR GREEN}TM111 Smack Down.\n"
  .string "{COLOR BLUE}I'll need a {COLOR GREEN}Yellow Shard{COLOR BLUE} for that.\p"
  .string "Would you like to exchange?$"


ThisIsTM119_Text::
  .string "This is {COLOR GREEN}TM119 Coaching.\n"
  .string "{COLOR BLUE}I'll need a {COLOR GREEN}Big Mushroom{COLOR BLUE} for that.\p"
  .string "Would you like to exchange?$"


ISellTmsForStuff_Text::
  .string "Hello, I exchange TMs for\n"
  .string "specific items!$"


WhichItemWouldYouLike_Text::
  .string "What can I get for you?$"


ThatItemsSoldOut_Text::
  .string "...That's sold out$"


