CinnabarMay1_Text::
  .string "Sorry, excuse me...$"


CinnabarMay2_Text::
  .string "All those Gym badges...$"


CinnabarMay3_Text::
  .string "...I knew it, you're\n"
  .string "{COLOR GREEN}{PLAYER}{COLOR RED}!\p"
  .string "{COLOR GREEN}Brendan{COLOR RED} talks about you very often;\n"
  .string "you seem to be a big motivator\l"
  .string "for him.\p"
  .string "Oh right! I'm {COLOR GREEN}May{COLOR RED}.\n"
  .string "{COLOR GREEN}Brendan{COLOR RED} and I both come from Hoenn.\p"
  .string "Well, I could use a warm-up before I\n"
  .string "face {COLOR GREEN}Blaine{COLOR RED}.$"


CinnabarMay4_Text::
  .string "I may as well see how skilled you\n"
  .string "are myself!$"


CinnabarMayDefeat_Text::
  .string "Woah, that was great!\n"
  .string "You lived up to the hype!$"


CinnabarMay5_Text::
  .string "I see why {COLOR GREEN}Brendan{COLOR RED} looks up\n"
  .string "to you now.\p"
  .string "I don't know if we'll bump into each\n"
  .string "other again, so please, have this.$"


CinnabarMay7_Text::
  .string "Take care!$"


Cinnabar_Text_FossilGuy1::
  .string "I'm a fossil collector!\p"
  .string "Here, have one.$"


Cinnabar_Text_FossilGuy2 ::
  .string "{COLOR BLACK}You received a {COLOR GREEN}{STR_VAR_1}{COLOR BLACK}.$"


Cinnabar_Text_FossilGuy3::
  .string "Hmm... I'm out of fossils today.\n"
  .string "Come back tomorrow!$"


CinnabarLatis1 _Text::
  .string "Hmm... My colleague says these\n"
  .string "stones correspond to certain\l"
  .string "legendary Pokémon, but I'm unsure\l"
  .string "which ones he may be referring\l"
  .string "to.$"


CinnabarLatis2 _Text::
  .string "Yeah...$"


CinnabarLatis3 _Text::
  .string "That doesn't seem to be it.\n"
  .string "Thank you though!$"


CinnabarLatis4_Text::
  .string "Ah yes, you already showed\n"
  .string "me that one!$"


CinnabarLatis5_Text::
  .string "Thank you for helping me\n"
  .string "complete my research!\p"
  .string "You must be a strong trainer!$"


CinnabarLatis6_Text::
  .string "Yes! It's for {COLOR GREEN}{STR_VAR_1}{COLOR BLACK}!\p"
  .string "Thank you for helping me with\n"
  .string "this discovery!\p"
  .string "Please, have them!$"


Normal _Text::
  .string "Normal$"


Fighting_Text::
  .string "Fighting$"


Flying_Text::
  .string "Flying$"


Poison_Text::
  .string "Poison$"


Ground _Text::
  .string "Ground$"


Rock_Text::
  .string "Rock$"


Bug_Text::
  .string "Bug$"


Ghost_Text::
  .string "Ghost$"


Steel_Text::
  .string "Steel$"


Fire_Text::
  .string "Fire$"


Water_Text::
  .string "Water$"


Grass_Text::
  .string "Grass$"


Electric_Text::
  .string "Electric$"


Psychic_Text::
  .string "Psychic$"


Ice_Text::
  .string "Ice$"


Dragon_Text::
  .string "Dragon$"


Dark_Text::
  .string "Dark$"


Fairy_Text::
  .string "Fairy$"


NoSilvally_Text::
  .string "Hm, that's not a {COLOR GREEN}Silvally{COLOR BLUE}.$"


SilvallyChanger1_Text::
  .string "I can switch your Silvally's\n"
  .string "form! Is that something you're\l"
  .string "interested in?$"


WhichForm_Text::
  .string "Which {COLOR GREEN}Silvally{COLOR BLUE} form do you want?$"


SilvallyChanger2 _Text::
  .string "And...\p"
  .string "Yup, the form has been changed!\p"
  .string "Let me know if you're in need\n"
  .string "of my services again!$"


SilvallyChanger3_Text::
  .string "Ah yes! A {COLOR GREEN}Silvally{COLOR BLUE}!$"


blaine_Text_EncounterText::
  .string "{COLOR BLUE}Hah!\p"
  .string "I am {COLOR GREEN}Blaine{COLOR BLUE}, the red-hot Leader\n"
  .string "of Cinnabar Gym!\p"
  .string "My fiery Pokémon are all rough\n"
  .string "and ready with intense heat!\p"
  .string "They incinerate all challengers!\p"
  .string "Hah!\n"
  .string "You better have Burn Heal!$"


blaine_Text_DefeatText::
  .string "I have burned down to nothing!\n"
  .string "Not even ashes remain!\p"
  .string "You have earned the Volcano Badge.$"


blaine_Text_Givetm::
  .string "TM38 contains Fire Blast.\n"
  .string "Teach it to Fire-type Pokémon.\p"
  .string "Special Attackers would be ideal\n"
  .string "for that move.$"


blaine_Text_TMInfomsg::
  .string "Hah! What a fight.\p"
  .string "Here, you can have this, too!$"


blaine_Text_Helloagain::
  .string "...You looking for a {COLOR GREEN}Charizardite Y{COLOR BLUE}?$"


blaine_Text_Perfectpokemon::
  .string "Show me a Pokémon with hefty\n"
  .string "Special Attack.\p"
  .string "Then, you'll earn a {COLOR GREEN}Charizardite Y{COLOR BLUE}!$"


blaine_Text_Helloagain2::
  .string "...You looking for a {COLOR GREEN}Charizardite X{COLOR BLUE}?$"


blaine_Text_Perfectpokemon2::
  .string "Show me a Pokémon with hefty\n"
  .string "Special Attack.\p"
  .string "Then, you'll earn a {COLOR GREEN}Charizardite X{COLOR BLUE}!$"


blaine_Text_Thepokemon::
  .string "Your {STR_VAR_1}...$"


blaine_Text_Notquite::
  .string "It's not enough, I'm afraid.$"


blaine_Text_Perfect::
  .string "Hah!\n"
  .string "That's what I wanna see!\p"
  .string "Well then, here it is.$"


blaine_Text_Donemsg::
  .string "Fire-types are to be used with\n"
  .string "utmost respect.\p"
  .string "Don't waste them on Water-types.$"


blaine_Text_Charmmsg::
  .string "This item makes special attacks\n"
  .string "even more fearsome.\p"
  .string "Take it as well.$"


jasmine_Text_1::
  .string "Hmm...{COLOR GREEN} Mega Aggron{COLOR RED} or {COLOR GREEN}Mega Steelix{COLOR RED}...$"


jasmine_Text_2::
  .string "Ah, hello.\p"
  .string "I've only recently acquainted myself\n"
  .string "with Mega Evolution, so I'm still\l"
  .string "figuring things out.$"


jasmine_Text_3::
  .string "Um, I'd like to practice, if you don't\n"
  .string "mind...$"


jasmine_Text_4::
  .string "Although I'm shy...\n"
  .string "Please don't take me lightly.$"


jasmine_Text_Defeat::
  .string "Well done...$"


jasmine_Text_6::
  .string "You have both skill and fortitude.\p"
  .string "Um... I think you'd like this.$"


jasmine_Text_7::
  .string "This item has helped me in count-\n"
  .string "less battles, although it can be a\l"
  .string "bit tricky to use.\p"
  .string "Try it for yourself.$"


jasmine_Text_Take::
  .string "I do have more to give, but...\p"
  .string "You'll have to show me a Pokémon\n"
  .string "forged in Defense.$"


jasmine_Text_8::
  .string "I think it could use more\n"
  .string "protection.\p"
  .string "No... I don't mean that kind...$"


jasmine_Text_Firstmon::
  .string "Your {STR_VAR_1}...$"


jasmine_Text_9::
  .string "Yes, this Pokémon is quite a\n"
  .string "worthy shield.\p"
  .string "As promised, here you go.$"


jasmine_Text_10::
  .string "{COLOR RED}The{COLOR GREEN} Assault Vest{COLOR RED} complements a high\n"
  .string "defense Pokémon well, making it an\l"
  .string "impenetrable wall.$"


metatutor_Text_1::
  .string "I teach some sick moves, but it's\n"
  .string "going to cost \$10000.\p"
  .string "You in?$"


metatutor_Text_Text1::
  .string "Aura Sphere$"


metatutor_Text_Text2::
  .string "Heat Wave$"


metatutor_Text_Text3::
  .string "Hurricane$"


metatutor_Text_Text4::
  .string "Power Whip$"


metatutor_Text_Text5::
  .string "High Horsepower$"


metatutor_Text_Text6::
  .string "Bug Buzz$"


metatutor_Text_Text7::
  .string "Phantom Force$"


metatutor_Text_Text8::
  .string "Flare Blitz$"


metatutor_Text_Text9::
  .string "Stored Power$"


metatutor_Text_Text10::
  .string "Gunk Shot$"


metatutor_Text_Text11::
  .string "Power Gem$"


metatutor_Text_Tailwind::
  .string "Tailwind$"


metatutor_Text_Megahorn::
  .string "Megahorn$"


metatutor_Text_TextViewMore::
  .string "View More$"


metatutor_Text_Exit::
  .string "Exit$"


metatutor_Text_Msg::
  .string "\$10000. Which move should I teach?$"


metatutor_Text_3::
  .string "Alright, who's getting it?$"


metatutor_Text_4::
  .string "Come back for more.$"


metatutor_Text_Wait::
  .string "...$"


metatutor_Text_Poor::
  .string "...You don't have enough money.$"


therianforms_Text_2::
  .string "I have items that are said to change\n"
  .string "forms of certain Pokémon.$"


therianforms_Text_2_1::
  .string "I already gave you the item\n"
  .string "for that Pokémon.$"


therianforms_Text_3::
  .string "If you show me one that's compatible,\n"
  .string "I'll gladly hand it over!$"


therianforms_Text_5::
  .string "That ain't it.$"


therianforms_Text_7::
  .string "Yes, that's it!\n"
  .string "Here you go!$"


therianforms_Text_4::
  .string "{STR_VAR_1}...$"


therianforms_Text_8::
  .string "I hope you're wreaking havoc\n"
  .string "with the alternate forms.$"


Cinnabar_Text_Eevee::
  .string "{COLOR GREEN}Eevee{COLOR BLUE} can evolve into one of eight\n"
  .string "kinds of Pokémon.$"


jasminere_Text_1::
  .string "{COLOR RED}Ah, welcome back.\n"
  .string "I hope you haven't returned\l"
  .string "hoping to destroy me in battle again.\p"
  .string "I've polished and learned a few new\n"
  .string "skills of my own.\p"
  .string "So, is that what you'd like?$"


jasminere_Text_2::
  .string "{COLOR RED}Hm, another loss, although it hurts\n"
  .string "less knowing you're the champion.\p"
  .string "I do feel like my battling prowess\n"
  .string "has improved, so thank you.\p"
  .string "This may assist you.$"


jasminere_Text_3::
  .string "{COLOR RED}And, if you'd like me to teach the move\n"
  .string "Steel Beam, talk to me!\p"
  .string "Keep it going, {COLOR GREEN}{PLAYER}.$"


CinnabarGym_Text_AceTrainer1_1::
  .string "I know why {COLOR GREEN}Blaine{COLOR BLUE} became a\n"
  .string "Trainer.$"


CinnabarGym_Text_AceTrainer1_2::
  .string "Ow!$"


CinnabarGym_Text_AceTrainer1_3::
  .string "Our Leader, {COLOR GREEN}Blaine{COLOR BLUE}, became lost\n"
  .string "in the mountains but good.\p"
  .string "Night fell when a fiery bird\n"
  .string "Pokémon appeared.\p"
  .string "Its light allowed Blaine to find\n"
  .string "his way down safely.$"


CinnabarGym_Text_AceTrainer2_1::
  .string "I've been to many Gyms, but this\n"
  .string "one best suits my style.$"


CinnabarGym_Text_AceTrainer2_2::
  .string "Yowza!\n"
  .string "Too hot!$"


CinnabarGym_Text_AceTrainer2_3::
  .string "{COLOR GREEN}Blaziken, Cinderace...\n"
  .string "{COLOR RED}Those are popular Fire Pokémon.$"


CinnabarGym_Text_AceTrainer3_1::
  .string "Fire is weak against H2O.$"


CinnabarGym_Text_AceTrainer3_2::
  .string "Oh!\n"
  .string "Snuffed out!$"


CinnabarGym_Text_AceTrainer3_3::
  .string "Water beats fire, of course.\p"
  .string "But fire melts ice, so the Fire\n"
  .string "type beats Ice-type Pokémon.$"


