Jotard_Text_1 ::
  .string "Oh? You're approaching me...?$"


Jotard_Text_2::
  .string "Instead of running away,\n"
  .string "you're coming right to me?$"


Jotard_Text_3 ::
  .string "Oh ho!\n"
  .string "Then come as close as you like!$"


Jotard_Text_Defeat::
  .string "N-nani?!$"


Jotard_Text_4::
  .string "Damn you, how could my team of\n"
  .string "Jojo references lose?\p"
  .string "Fine, you can take these.$"


Jotard_Text_5::
  .string "I'll prevail next time...\p"
  .string "Us Jojo fans are ubiquitous...\p"
  .string "There is no escape.$"


