lorelei_Text_Postbattlemsg::
  .string "You're better than I thought.\n"
  .string "Go on ahead.\p"
  .string "You only got a taste of the\n"
  .string "Pokémon League's power.$"


lorelei_Text_Firstmsg::
  .string "Welcome to the Pokémon League.\p"
  .string "I am {COLOR GREEN}Lorelei{COLOR RED} of the Elite Four.\p"
  .string "No one can best me when it comes\n"
  .string "to icy Pokémon.\p"
  .string "Freezing moves are powerful.\p"
  .string "Your Pokémon will be at my mercy\n"
  .string "when they are frozen solid.\p"
  .string "Hahaha!\n"
  .string "Are you ready?$"


lorelei_Text_Rematchmsg::
  .string "Welcome to the Pokémon League.\p"
  .string "I, {COLOR GREEN}Lorelei{COLOR RED} of the Elite Four,\n"
  .string "have returned!\p"
  .string "You know how it goes.\n"
  .string "No one can best me when it comes\l"
  .string "to icy Pokémon.\p"
  .string "Freezing moves are powerful.\p"
  .string "Your Pokémon will be at my mercy\n"
  .string "when they are frozen solid.\p"
  .string "Hahaha!\n"
  .string "Are you ready?$"


lorelei_Text_Defeatmsg::
  .string "...Things shouldn't be this way!$"


LetMeHeal_Text::
  .string "Would you like me to heal\n"
  .string "your team for the next match?$"


bruno_Text_Postdefeatmsg::
  .string "My job is done.\n"
  .string "Go face your next challenge.$"


bruno_Text_Prebattlemsg::
  .string "I am {COLOR GREEN} Bruno{COLOR BLUE} of the Elite Four!\p"
  .string "Through rigorous training, people\n"
  .string "and Pokémon can become stronger\l"
  .string "without limit.\p"
  .string "I've lived and trained with my\n"
  .string "fighting Pokémon!\l"
  .string "And that will never change!\p"
  .string "{PLAYER}!\p"
  .string "We will grind you down with our\n"
  .string "superior power!\p"
  .string "Hoo hah!$"


bruno_Text_Defeatmsg::
  .string "Why?\n"
  .string "How could I lose?$"


agatha_Text_Postdefeatmsg::
  .string "You win!\p"
  .string "I see what the old duff sees in\n"
  .string "you now.\p"
  .string "I have nothing else to say.\n"
  .string "Run along now, child!$"


agatha_Text_Prebattlemsg::
  .string "I am {COLOR GREEN}Agatha{COLOR RED} of the Elite Four.\p"
  .string "I hear {COLOR GREEN}Oak{COLOR RED}'s taken a lot of\n"
  .string "interest in you, child.\p"
  .string "That old duff was once tough and\n"
  .string "handsome.\p"
  .string "But that was decades ago.\n"
  .string "He's a shadow of his former self.\p"
  .string "Now he just wants to fiddle with\n"
  .string "his Pokédex.\p"
  .string "He's wrong.\n"
  .string "Pokémon are for battling!\p"
  .string "{PLAYER}! I'll show you how a real\n"
  .string "trainer battles!$"


agatha_Text_Defeatmsg::
  .string "Oh, my!\n"
  .string "You're something special, child!$"


lance_Text_Postdefeatmsg::
  .string "I still can't believe my dragons\n"
  .string "lost to you, {COLOR GREEN}{PLAYER}{COLOR BLUE}.\p"
  .string "You are now the Pokémon League\n"
  .string "Champion!\p"
  .string "...Or, you would have been, but\n"
  .string "you have one more challenge left.\p"
  .string "There is one more trainer to face!\n"
  .string "His name is...\p"
  .string "{COLOR GREEN}{RIVAL}{COLOR BLUE}!\p"
  .string "He beat the Elite Four before\n"
  .string "you.\p"
  .string "He is the real Pokémon League\n"
  .string "Champion.$"


lance_Text_Prebattlemsg::
  .string "Ah! Nice to see you,\n"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}!\p"
  .string "I lead the Elite Four.\p"
  .string "I'll cut to the chase.\p"
  .string "You know that dragons are\n"
  .string "mythical Pokémon.\p"
  .string "They're hard to catch and raise,\n"
  .string "but their powers are superior.\p"
  .string "They're virtually indestructible.\n"
  .string "There's no being clever with them.\p"
  .string "Well, are you ready to lose?\p"
  .string "Your League challenge ends with\n"
  .string "me, {COLOR GREEN}{PLAYER}{COLOR BLUE}!$"


lance_Text_Prebattlemsg2::
  .string "Ah!\n"
  .string "So, you've returned, {COLOR GREEN}{PLAYER}{COLOR BLUE}!\p"
  .string "I lead the Elite Four.\p"
  .string "You can call me {COLOR GREEN} Lance{COLOR BLUE} the dragon\n"
  .string "trainer.\p"
  .string "You know that dragons are\n"
  .string "mythical Pokémon.\p"
  .string "They're hard to catch and raise,\n"
  .string "but their powers are superior.\p"
  .string "They're virtually indestructible.\n"
  .string "There's no being clever with them.\p"
  .string "Well, are you ready to lose?\p"
  .string "Your League challenge ends with\n"
  .string "me, {COLOR GREEN}{PLAYER}{COLOR BLUE}!$"


lance_Text_Defeatmsg::
  .string "That's it!\p"
  .string "I hate to admit it, but you are a\n"
  .string "Pokémon master!$"


E4nurse_Text_1::
  .string "Now go get your ass beat lmao$"


E4LanceInfo_Text::
  .string "Maybe becoming an Elite Four\n"
  .string "member is in the blood.\p"
  .string "From what I've heard, Lance has\n"
  .string "a cousin who's become a Gym Leader\l"
  .string "here recently.$"


hof_Text_Oaktalk::
  .string "{COLOR GREEN}Oak:{COLOR BLUE} Er-hem!\n"
  .string "Congratulations, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\p"
  .string "This floor is the Pokémon Hall Of\n"
  .string "Fame.\p"
  .string "Pokémon League Champions are\n"
  .string "honored for their exploits here.\p"
  .string "Their Pokémon are also recorded in\n"
  .string "the Hall Of Fame.\p"
  .string "{COLOR GREEN}{PLAYER}!{COLOR BLUE}\p"
  .string "You have worked hard to become\n"
  .string "the new League Champion.\p"
  .string "Congratulations, {COLOR GREEN}{PLAYER},{COLOR BLUE} you and\n"
  .string "your Pokémon are Hall Of Famers!$"


champion_Text_LossMsgWhy::
  .string "Why?\n"
  .string "Why did I lose?\p"
  .string "I never made any mistakes raising\n"
  .string "my Pokémon...\p"
  .string "Darn it! You're the new Pokémon\n"
  .string "League Champion!\p"
  .string "Although I don't like to admit it...$"


champion_Text_OakPlayer::
  .string "{COLOR GREEN}Oak: {PLAYER}!{COLOR BLUE}$"


champion_Text_SoYouWon::
  .string "{COLOR GREEN}Oak:{COLOR BLUE} So, you've won!\n"
  .string "Sincerely, congratulations!\p"
  .string "You're the new Pokémon League\n"
  .string "Champion!\p"
  .string "You've grown up so much since you\n"
  .string "first left with your starter to\l"
  .string "work on the Pokédex.\p"
  .string "{COLOR GREEN}{PLAYER},{COLOR BLUE} you have come of age!$"


champion_Text_OakDisappointed::
  .string "{COLOR GREEN}Oak: {RIVAL}...{COLOR BLUE}\n"
  .string "I'm disappointed in you.\p"
  .string "I came when I heard you'd beaten\n"
  .string "the Elite Four.\p"
  .string "But, when I got here, you had\n"
  .string "already lost!\p"
  .string "{COLOR GREEN}{RIVAL},{COLOR BLUE} do you understand why\n"
  .string "you lost?\p"
  .string "You have forgotten to treat your\n"
  .string "Pokémon with love and trust.\p"
  .string "Without them, you will never\n"
  .string "become a Champ again!$"


champion_Text_OakURChampion::
  .string "{COLOR GREEN}Oak: {PLAYER}.{COLOR BLUE}\p"
  .string "You understand that your victory\n"
  .string "was not just your own doing.\p"
  .string "The bond you share with your\n"
  .string "Pokémon is marvelous.\p"
  .string "{COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "Come with me!$"


champion_Text_FirstMsgTxtHardcore::
  .string "{COLOR GREEN}{RIVAL}:{COLOR BLUE} Hey, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\p"
  .string "I was looking forward to seeing\n"
  .string "you, {COLOR GREEN}{PLAYER}.{COLOR BLUE}\p"
  .string "My rival should be strong to keep\n"
  .string "me sharp.\p"
  .string "While working on my Pokédex, I\n"
  .string "looked all over for Pokémon.\p"
  .string "Not only that, I unlocked the abi-\n"
  .string "lity to Mega Evolve multiple times.\p"
  .string "And now...\p"
  .string "I'm the Pokémon League Champion!\p"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}!\n"
  .string "Do you know what that means?\p"
  .string "I'll tell you.\p"
  .string "I am the most powerful Trainer in\n"
  .string "the world!$"


champion_Text_SecondMsgTextHardcore::
  .string "{COLOR GREEN}{RIVAL}:{COLOR BLUE} Hey, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\p"
  .string "You came back, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "Hahah, that is so great!\p"
  .string "My rival should be strong to keep\n"
  .string "me sharp.\p"
  .string "While working on my Pokédex, I\n"
  .string "looked all over for Pokémon.\p"
  .string "Not only that, I unlocked the abi-\n"
  .string "lity to Mega Evolve multiple times.\p"
  .string "And now...\p"
  .string "I'm the Pokémon League Champion!\p"
  .string "{COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "Do you know what that means?\p"
  .string "I'll tell you.\p"
  .string "I am the most powerful Trainer in\n"
  .string "the world!$"


champion_Text_FirstMsgTxt::
  .string "{COLOR GREEN}{RIVAL}:{COLOR BLUE} Hey, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\p"
  .string "I was looking forward to seeing\n"
  .string "you, {COLOR GREEN}{PLAYER}.{COLOR BLUE}\p"
  .string "My rival should be strong to keep\n"
  .string "me sharp.\p"
  .string "While working on my Pokédex, I\n"
  .string "looked all over for Pokémon.\p"
  .string "Not only that, I assembled teams\n"
  .string "that would beat any Pokémon type.\p"
  .string "And now...\p"
  .string "I'm the Pokémon League Champion!\p"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}!\n"
  .string "Do you know what that means?\p"
  .string "I'll tell you.\p"
  .string "I am the most powerful Trainer in\n"
  .string "the world!$"


champion_Text_SecondMsgText::
  .string "{COLOR GREEN}{RIVAL}:{COLOR BLUE} Hey, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\p"
  .string "You came back, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "Hahah, that is so great!\p"
  .string "My rival should be strong to keep\n"
  .string "me sharp.\p"
  .string "While working on my Pokédex, I\n"
  .string "looked all over for Pokémon.\p"
  .string "Not only that, I assembled teams\n"
  .string "that would beat any Pokémon type.\p"
  .string "And now...\p"
  .string "I'm the Pokémon League Champion!\p"
  .string "{COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "Do you know what that means?\p"
  .string "I'll tell you.\p"
  .string "I am the most powerful Trainer in\n"
  .string "the world!$"


champion_Text_LossMsg::
  .string "No!\n"
  .string "That can't be!\l"
  .string "You beat me at my best!\p"
  .string "After all that work to become\n"
  .string "the League Champ?\p"
  .string "My reign is over already?\n"
  .string "It's not fair!$"


