Rules_Text::
  .string "Rules$"


WhatYouWant _Text::
  .string "Would you like to hear the rules\n"
  .string "again?$"


TurnOnExpert_Text::
  .string "Okay, it's been turned on!$"


TurnOffExpert_Text::
  .string "Okay, it's been turned off!$"


ExpertMode1_Text::
  .string "Yo, champ in the making!\p"
  .string "It seems this is your first Gym\n"
  .string "challenge, so I'm responsible for\l"
  .string "informing you of the rules.$"


ExpertMode2 _Text::
  .string "1: Accuracy reducing moves and\n"
  .string "evasion raising effects have been\l"
  .string "removed from this game.\p"
  .string "2: Baton Pass is removed from this\n"
  .string "game.\p"
  .string "3: Sleep Clause is in effect,\n"
  .string "meaning only one Pokémon per team\l"
  .string "can be put to sleep at a time.\p"
  .string "4: OHKO moves are removed from the\n"
  .string "game.\p"
  .string "5: The bag is inaccessible during\n"
  .string "boss battles.\p"
  .string "6: There is a soft level cap before\n"
  .string "each boss, which reduces EXP gain\l"
  .string "significantly when the level cap is\l"
  .string "reached.\p"
  .string "7: Pokémon will disobey when levelled\n"
  .string "too far above the level cap.\p"
  .string "8: Consumable held items come back\n"
  .string "after trainer battles.\p"
  .string "9. Battle Style is forced to Set.\p"
  .string "10. You cannot Thief items from\n"
  .string "trainers.\p"
  .string "11. You are automatically healed to\n"
  .string "full in most boss battles to prevent\l"
  .string "certain exploits.$"


ExpertMode3 _Text::
  .string "If you ever want me to reiterate\n"
  .string "the rules, just talk to me again!$"


ExpertModeEasy_Text::
  .string "1: Accuracy reducing moves and\n"
  .string "evasion raising effects have been\l"
  .string "removed from this game.\p"
  .string "2: Baton Pass is removed from this\n"
  .string "game.\p"
  .string "3: Sleep Clause is in effect,\n"
  .string "meaning only one Pokémon per team\l"
  .string "can be put to sleep at a time.\p"
  .string "4: OHKO moves are removed from the\n"
  .string "game.\p"
  .string "5: There is a soft level cap before\n"
  .string "each boss, which reduces EXP gain\l"
  .string "significantly when the level cap is\l"
  .string "reached.\p"
  .string "6: Pokémon will disobey when levelled\n"
  .string "too far above the level cap.\p"
  .string "7: Consumable held items come back\n"
  .string "after trainer battles.\p"
  .string "8. You cannot Thief items from\n"
  .string "trainers.\p"
  .string "9. You are automatically healed to\n"
  .string "full in most boss battles to prevent\l"
  .string "certain exploits.$"


ExpertMode5_Text::
  .string "Good luck challenger!$"


