FollowMePkmn1_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} is happy!$"


FollowMePkmnAmpedUp_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} looks amped up!$"


FollowerPokemon_Text_EjectButton::
  .string "{COLOR BLACK}It's so excited it found you an\n"
  .string "item!$"


FollowMePkmnComfyRockTunnel_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} feels right at home!$"


FollowMePkmn2_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} gave you an item!$"


FollowMePkmn3_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} looks pleased!$"


FollowMePkmn4_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} looks cute.$"


FollowMePkmn5_Text::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} doesn't look too\n"
  .string "happy...$"


PkmnFoundSomething_Text::
  .string "{COLOR BLACK}It seems {COLOR GREEN}{STR_VAR_1}{COLOR BLACK}\n"
  .string "found something...$"


Follower_Text_Mewtwo_Ask::
  .string "Hmm... While being created I overheard\n"
  .string "from scientists that I was created\l"
  .string "from a Pokémon named {COLOR GREEN}Mew...\p"
  .string "{COLOR BLUE}You stumbled upon {COLOR GREEN}Mew{COLOR BLUE} in this\n"
  .string "forest earlier.\p"
  .string "If possible, I would like to meet\n"
  .string "my original...\p"
  .string "Will you allow me to take us to\n"
  .string "{COLOR GREEN}Mew?{COLOR BLUE}$"


Follower_Text_Mewtwo_Reject::
  .string "Hm. I respectfully ask you to\n"
  .string "reconsider, {COLOR GREEN}{PLAYER}.$"


FollowMePkmn_Text_OranBerry::
  .string "{COLOR BLACK}Would you like to give your\n"
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} an {COLOR GREEN}Oran Berry?{COLOR BLACK}$"


FollowMePkmn_Text_AteBerry::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} ate the {COLOR GREEN}Oran Berry...$"


FollowMePkmn_Text_AteBerry2::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} is pleased!$"


Follower_Text_UnhappySurfer::
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLACK} looks uncomfortable...$"


