Fuschia_Text_OakAid1::
  .string "Hi! Remember me?\n"
  .string "I'm one of Prof. Oak's Aides.\p"
  .string "He entrusted me to give you these\n"
  .string "items.$"


Fuschia_Text_OakAid2::
  .string "It may seem counterintuitive to\n"
  .string "inflict status on your own Poké-\l"
  .string "mon, but some of them greatly\l"
  .string "benefit from it.$"


Fuschia_Text_NastyPlot1::
  .string "Hehehe... how shall I go about\n"
  .string "my plan for world domination...\p"
  .string "Sorry, I was just mumbling to\n"
  .string "myself. But...\p"
  .string "Would you like me to teach\n"
  .string "Nasty Plot?$"


Fuschia_Text_NastyPlot2::
  .string "May your suspicious schemes go\n"
  .string "by smoothly.$"


Fuschia_Text_NastyPlot3::
  .string "Hmm... perhaps I'm too sus.$"


Fuschia_Text_Egg1::
  .string "Hi...I'm a special move tutor.\p"
  .string "I teach Egg moves, so you don't have\n"
  .string "to go through the trouble of\l"
  .string "breeding.\p"
  .string "I'll need a {COLOR GREEN}Heart Scale{COLOR BLUE} though.$"


Fuschia_Text_Egg2::
  .string "Would you like me to teach\n"
  .string "an egg move?$"


Fuschia_Text_Egg3::
  .string "Alright, who wants it?$"


Fuschia_Text_Egg4::
  .string "{COLOR BLUE}Thank you, enjoy!$"


Fuschia_Text_EggNo::
  .string "Well then...$"


Fuschia_Text_EggNo2::
  .string "Sorry...\p"
  .string "It doesn't appear as if I have a\n"
  .string "move I can teach that Pokémon.$"


Fuschia_Text_EggNo3::
  .string "Sorry... that's an egg.$"


Fuschia_Text_EggNew1::
  .string "Would you like me to teach\n"
  .string "an egg move?$"


Fuschia_Text_EggWhichMove::
  .string "Which move should I teach?$"


Fuschia_Text_GuessCry1::
  .string "Hi there, I have a valuable\n"
  .string "service!\p"
  .string "I teach Egg moves, so you don't have\n"
  .string "to go through the trouble of\l"
  .string "breeding.$"


Fuschia_Text_GuessCry1_1::
  .string "However, I'll only do it for\n"
  .string "a true Pokémon trainer.\p"
  .string "So, I'll play 4 Pokémon cries\n"
  .string "and you'll have to guess\l"
  .string "the Pokémon the cry corresponds\l"
  .string "to.\p"
  .string "You up for it?$"


Fuschia_Text_GuessCry2::
  .string "Alright, here's one.\p"
  .string "This one's from Generation 1!$"


Fuschia_Text_GuessCry3::
  .string "Nice! That's correct.\p"
  .string "This one's from Generation 3.$"


Fuschia_Text_GuessCry3_1::
  .string "Yup, {COLOR GREEN}Magmar!{COLOR BLUE}$"


Fuschia_Text_GuessCry4::
  .string "Hmm... Unfortunately that's\n"
  .string "incorrect.$"


FuschiaGuessCry5_Text::
  .string "Would you like to guess again?$"


Fuschia_Text_GuessCry6_1::
  .string "That's {COLOR GREEN}Nincada{COLOR BLUE} alright.$"


Fuschia_Text_GuessCry6::
  .string "Nice. Correct again!\p"
  .string "You got 2 so far!\p"
  .string "The next one's from Generation\n"
  .string "4.$"


Fuschia_Text_GuessCry7_1::
  .string "You guessed it, {COLOR GREEN}Gallade!{COLOR BLUE}$"


Fuschia_Text_GuessCry7::
  .string "You're on a roll!\p"
  .string "Only one more cry to go!\p"
  .string "No hints for this one,\n"
  .string "you're too good!$"


Fuschia_Text_GuessGulpin::
  .string "Gulpin?\n"
  .string "Gulpin these nuts!\p"
  .string "Gottem!\p"
  .string "Haha, unfortunately that's not\n"
  .string "even the right answer.\p"
  .string "You'll have to try again!$"


Fuschia_Text_GuessRhydon::
  .string "Rhydon?\n"
  .string "Rhydon these nuts!\p"
  .string "Gottem!\p"
  .string "Haha, unfortunately that's not\n"
  .string "even the right answer.\p"
  .string "You'll have to try again!$"


Fuschia_Text_GuessSlugma::
  .string "Slugma? Slugma nuts!\p"
  .string "Gottem!\p"
  .string "...Wait, actually, don't do that.\p"
  .string "Either way, that's not even\n"
  .string "the right answer.\p"
  .string "You'll have to try again!$"


TryAgainNextTime_Text::
  .string "Try again next time then.$"


Fuschia_Text_GuessCryFinal::
  .string "Right on, it's {COLOR GREEN}Komala!{COLOR BLUE}$"


Fuschia_Text_YouGotIt::
  .string "Woah, you're one gigantic\n"
  .string "nerd bro!\p"
  .string "That's all four of them.\p"
  .string "Nicely done. As promised, I\n"
  .string "can teach your Pokémon egg\l"
  .string "moves.$"


Fuschia_Text_DotDotDot::
  .string "...$"


Fuschia_Text_WhichOne::
  .string "Alright, what's your guess?$"


Venomoth_Text::
  .string "Venomoth$"


Magmar_Text::
  .string "Magmar$"


Nincada_Text::
  .string "Nincada$"


Gallade_Text::
  .string "Gallade$"


Komala_Text::
  .string "Komala$"


Gulpin_Text::
  .string "Gulpin$"


Rhydon_Text::
  .string "Rhydon$"


FuschiaHandOver_Text::
  .string "{PLAYER} handed over a\n"
  .string "{COLOR GREEN}Heart Scale{COLOR BLACK} in exchange.$"


FuschiaDouble1 _Text::
  .string "Hey, I can turn on wild double\n"
  .string "battles for you!\p"
  .string "This is especially useful for\n"
  .string "faster EV training.\p"
  .string "Do you want to proceed?$"


FuschiaDouble2_Text::
  .string "Wild double battles are turned\n"
  .string "on! Talk to me again if you want to\l"
  .string "turn them off.$"


FuschiaDouble3 _Text::
  .string "Do you want to turn off\n"
  .string "wild double battles?$"


FuschiaDouble4_Text::
  .string "Wild double battles are turned\n"
  .string "off!$"


FuschiaDouble5_Text::
  .string "I'll be here if my service\n"
  .string "will ever be of use!$"


brendanfuschia_Text_1::
  .string "Oh hey {COLOR GREEN}{PLAYER}{COLOR BLUE}!\p"
  .string "Fancy meeting you here.\p"
  .string "...You took down the boss, huh?\p"
  .string "I'm really sorry I couldn't be there\n"
  .string "for it, but I was never really worried\l"
  .string "about you.\p"
  .string "I've recently obtained the {COLOR GREEN}Mega Ring{COLOR BLUE},\n"
  .string "so I'd like to put myself to the test!\p"
  .string "...I see you've got one too!\p"
  .string "Let's not hold back then!$"


brendanfuschia_Text_Defeat::
  .string "Heh... not bad...\n$"


brendanfuschia_Text_2::
  .string "I feel the gap between us shrinking\n"
  .string "each time.\p"
  .string "I know I can do it!\p"
  .string "But, thanks for being a sport as\n"
  .string "always.\p"
  .string "With {COLOR GREEN}Sabrina's{COLOR BLUE} badge, you should be\n"
  .string "able to use this.$"


brendanfuschia_Text_3::
  .string "Safe travels pal!$"


nursegivemedicine_Text_3::
  .string "{COLOR RED}I'm a nurse caring for Pokémon\n"
  .string "here at the Safari Zone.$"


nursegivemedicine_Text_4::
  .string "...Oh? Erika has a sick Pokémon?\p"
  .string "Perhaps this will help!$"


nursegivemedicine_Text_5::
  .string "Give Erika my best wishes.$"


nursegivemedicine_Text_6::
  .string "Ah? Erika's {COLOR GREEN}Gloom{COLOR RED} is better?\p"
  .string "That's fantastic news.$"


substitute_Text_3::
  .string "Aww, I wish I was a Kangaskhan\n"
  .string "baby.\p"
  .string "I'd love to be a substitute for the\n"
  .string "baby...\p"
  .string "And snuggle in the mother\n"
  .string "Kangaskhan's belly pouch.\p"
  .string "But only Pokémon can use the\n"
  .string "technique Substitute...\p"
  .string "Want me to teach Substitute to\n"
  .string "one of your Pokémon?$"


substitute_Text_4::
  .string "Well, here you go.$"


substitute_Text_5::
  .string "Boy, what I'd give to crawl inside\n"
  .string "a Kangaskhan belly pouch...$"


substitute_Text_6::
  .string "Oh, really?\n"
  .string "Substitute seems so fun...$"


earthpower_Text::
  .string "Make foes shudder with the\n"
  .string "force of Earth Power!\p"
  .string "How about it?$"


earthpower_Text_Which::
  .string "Which Pokémon should I teach\n"
  .string "Earth Power to?$"


earthpower_Text_gogetem::
  .string "Go get em bud.$"


earthpower_Text_Cost::
  .string "It'll cost \$10000 now.$"


earthpower_Text_dot::
  .string "...$"


earthpower_Text_essential::
  .string "No?\p"
  .string "It's an essential move.$"


earthpower_Text_notenough::
  .string "...You don't have enough money.$"


koga_Text_EncounterText::
  .string "{COLOR BLUE}Fwahahaha!\p"
  .string "A mere child like you dares to\n"
  .string "challenge me?\p"
  .string "The very idea makes me shiver\n"
  .string "with mirth!\p"
  .string "Very well, I shall show you true\n"
  .string "terror as a ninja master.\p"
  .string "Swiftness brings abrupt doom.\p"
  .string "Being outran can render foes\n"
  .string "helpless.\p"
  .string "Despair to the frightening horror of\n"
  .string "my speed demons!$"


koga_Text_DefeatText::
  .string "Humph!\n"
  .string "You have proven your worth!\p"
  .string "Here!\n"
  .string "Take the Soul Badge!$"


koga_Text_Givetm::
  .string "TM36 is Sludge Bomb.\p"
  .string "The foe is drenched in toxins,\n"
  .string "inflicting damage with a chance of\l"
  .string "poison.$"


koga_Text_TMInfomsg::
  .string "Now that you have the Soul Badge,\n"
  .string "you can Surf outside of battle.\p"
  .string "Ah!\n"
  .string "Take this, too!$"


koga_Text_Helloagain::
  .string "...You want a {COLOR GREEN}Toxtricitite{COLOR BLUE}?$"


koga_Text_Perfectpokemon::
  .string "Show me a Pokémon you've invested\n"
  .string "in Speed.\p"
  .string "I'll gladly hand one over.$"


koga_Text_PerfectpokemonMinimal::
  .string "Show me a speedy Pokémon.\p"
  .string "I'll gladly hand one over.$"


koga_Text_Thepokemon::
  .string "Your {STR_VAR_1}...$"


koga_Text_Notquite::
  .string "Not fast enough, child.$"


koga_Text_Perfect::
  .string "Ohoho! This one is quick!\p"
  .string "Please, have it.$"


koga_Text_Donemsg::
  .string "Continue terrorizing foes, child.\p"
  .string "You have the capacity to do so.$"


koga_Text_Charmmsg::
  .string "Have one of my favorite items as\n"
  .string "well.$"


FuschiaDoubleOof_Text::
  .string "Sorry, double battles aren't\n"
  .string "working at the moment.$"


Fuschia_Text_Sandaconda1::
  .string "Hey! I've recently learned of a new\n"
  .string "powerful strategy!\p"
  .string "It's such a blast using it!\p"
  .string "Would you like to help me test it\n"
  .string "out?$"


Fuschia_Text_Sandaconda2::
  .string "Woohoo, exciting! Let's begin.$"


Fuschia_Text_SandacondaReject::
  .string "Hm, see you later then.$"


Fuschia_Text_SandacondaDefeat::
  .string "Wow, you withstood my onslaught!$"


Fuschia_Text_Sandaconda3::
  .string "Hmm, perhaps I'm a bit tunnel-visioned\n"
  .string "with my new strategy...\p"
  .string "I'll do some more practice!\p"
  .string "Thanks for the help!\p"
  .string "Take the {COLOR GREEN}Sandacondite!$"


Fuschia_Text_Sandaconda4::
  .string "{COLOR RED}... ah, you want the item I've been\n"
  .string "playing around with too?\p"
  .string "Alright, fine.$"


Fuschia_Text_Sandaconda5::
  .string "{COLOR GREEN}Power Herb Meteor Beam!\n"
  .string "{COLOR RED}Watch your foes cower in terror as\l"
  .string "the stars fall!$"


Fuschia_Text_Closed ::
  .string "{COLOR BLACK}The gym appears to be closed...\p"
  .string "Perhaps it'd be wise to rematch\n"
  .string "some of the Gym Leaders?$"


Safari_Text_WhereMyBf::
  .string "{COLOR GREEN}Sara: {COLOR RED}Where did my boyfriend,\n"
  .string "{COLOR GREEN}Erik{COLOR RED}, go?$"


Safari_Text_WouldveGaveToErik::
  .string "Oh, you have the care package\n"
  .string "cheat.\p"
  .string "I would've gave these to my boyfriend,\n"
  .string "but he stood me up!\p"
  .string "So, take them.$"


Fuschia_Text_Dracovish::
  .string "Name: Dracovish\n"
  .string "It may not appear powerful at\l"
  .string "first glance, but this fearsome\l"
  .string "Pokémon is notorious for OHKO-ing\l"
  .string "all sorts of foes.$"


Fuschia_Text_Milotic::
  .string "Name: Milotic\n"
  .string "This beautiful and elegant Pokémon\l"
  .string "evolves from quite the hideous\l"
  .string "Pokémon.$"


Fuschia_Text_Slowbro::
  .string "Name: Slowbro\n"
  .string "Friendly and very slow moving.$"


Fuschia_Text_GuyZoo1::
  .string "That monstrosity there...\p"
  .string "You want it too right?\p"
  .string "I've heard they can show up at\n"
  .string "{COLOR GREEN}Route 18.$"


FuschiaSeviiEgg_Text_1::
  .string "{COLOR BLUE}Hey {COLOR GREEN}{PLAYER}!$"


FuschiaSeviiEgg_Text_2::
  .string "{COLOR BLUE}Just another one of Oak's aides with\n"
  .string "another Seviian Egg.\p"
  .string "Oak figured you might want\n"
  .string "another one of these.\p"
  .string "Take it!$"


FuschiaSeviiEgg_Text_3::
  .string "{COLOR BLUE}Mm... seems you don't have space.\p"
  .string "I can wait around until you\n"
  .string "make room.$"


FuschiaSeviiEgg_Text_4::
  .string "{COLOR BLUE}Farewell {COLOR GREEN}{PLAYER}!$"


FuschiaSeviiEgg_Text_5::
  .string "Hey! Have you made room for the\n"
  .string "Seviian Egg?$"


FuschiaSeviiEgg_Text_6::
  .string "...Hmm, seems like you still don't\n"
  .string "have space.\p"
  .string "I'll be here until you do.$"


FuschiaSeviiEgg_Text_7::
  .string "...Yep! Here, take it$"


