KindleRoadBugsy_Text_1::
  .string "{COLOR GREEN}Bugsy:{COLOR BLUE} Perhaps I've reached my ceiling\n"
  .string "as a Bug-type specialist...$"


KindleRoadBugsy_Text_2::
  .string "{COLOR BLUE}...Oh! Ahem...\n"
  .string "If it isn't {COLOR GREEN}{PLAYER}!{COLOR BLUE}\l"
  .string "Huge congrats on becoming Champion!\p"
  .string "I've gone out and captured some\n"
  .string "of the best Bug types the world\l"
  .string "has to offer, but I feel as\l"
  .string "if I'm nearing my limit.$"


KindleRoadBugsy_Text_3::
  .string "{COLOR BLUE}Perhaps you can help me find\n"
  .string "my path...$"


KindleRoadBugsy_Text_4::
  .string "{COLOR BLUE}Heh, even with {COLOR GREEN}Arceus{COLOR BLUE} I stood no\n"
  .string "chance.\p"
  .string "Perhaps adding in more Pokémon to co-\n"
  .string "ver my bugs' weaknesses could go a\l"
  .string "long way.\p"
  .string "But I wouldn't feel true to myself\n"
  .string "doing that!\p"
  .string "It's such a conundrum...\p"
  .string "But, for that fight, I want you to\n"
  .string "have this.$"


KindleRoadBugsy_Text_5::
  .string "{COLOR BLUE}Z-Moves are powerful, but I doubt\n"
  .string "you'll find too much use out of\l"
  .string "Buginium Z.\p"
  .string "Even I'm aware Bug isn't really\n"
  .string "the greatest offensive typing.\p"
  .string "I'm sure you'll find a way to\n"
  .string "make it work.$"


KindleRoadBugsy_Text_6::
  .string "{COLOR BLUE}My {COLOR GREEN}Pinsir{COLOR BLUE} I have is a specially\n"
  .string "trained one with {COLOR GREEN}Extreme Speed.\p"
  .string "{COLOR BLUE}It's pretty insane with Aerilate.\n"
  .string "Here, you can try it too.$"


KindleRoadBugsy_Text_6_2::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Pinsir!{COLOR BLACK}$"


KindleRoadBugsy_Text_7::
  .string "{COLOR BLUE}Well, I'll be doing more soul\n"
  .string "searching elsewhere, see you later!$"


KindleRoadBugsy_Text_Defeat::
  .string "Hmm, it's to be expected I\n"
  .string "guess...$"


