rockslide_Text_3::
  .string "When you're up on a rocky mountain\n"
  .string "like this, rockslides are a threat.\p"
  .string "Can you imagine?\n"
  .string "Boulders tumbling down on you?\p"
  .string "That'd be, like, waaaaaaaaaaah!\n"
  .string "Total terror!\p"
  .string "You don't seem to be scared.$"


rockslide_Text_4::
  .string "Want to try it?$"


rockslide_Text_5::
  .string "Here you go!$"


rockslide_Text_7::
  .string "It might be scary to use it in this\n"
  .string "tunnel...$"


rockslide_Text_6::
  .string "Oh, so you are scared after all.$"


morty_Text_1::
  .string "{COLOR BLUE}Hello there. I'm {COLOR GREEN}Morty{COLOR BLUE} from the\n"
  .string "Johto region.\p"
  .string "My initial reason for coming here was\n"
  .string "to further reach my limits as a Gym\l"
  .string "Leader, but I've found myself a place\l"
  .string "I'd like to call home along the\l"
  .string "way.$"


morty_Text_3::
  .string "{COLOR BLUE}Perhaps a battle with a Johto Gym\n"
  .string "Leader interests you?$"


morty_Text_4::
  .string "{COLOR BLUE}Another time, I suppose.$"


morty_Text_5::
  .string "{COLOR BLUE}Fantastic.\p"
  .string "Help me reach my full potential!$"


morty_Text_Defeat::
  .string "I'm still not good enough yet...$"


morty_Text_6::
  .string "You have a striking resemblance of a\n"
  .string "fierce challenger I faced a long\l"
  .string "time ago.\p"
  .string "His name was {COLOR GREEN}Ethan{COLOR BLUE}, and he eventu-\n"
  .string "ally went on to become the Johto\l"
  .string "champion.\p"
  .string "...{COLOR GREEN}{PLAYER}, {COLOR BLUE} right?\p"
  .string "I have high hopes for you,\n"
  .string "{COLOR GREEN}{PLAYER}.{COLOR BLUE}\p"
  .string "Please, have my signature TM.$"


morty_Text_8::
  .string "I think you'd find this useful as\n"
  .string "well.$"


morty_Text_9::
  .string "Becoming the best is an admirable\n"
  .string "dream, no doubt.\p"
  .string "But, always remember to cherish\n"
  .string "your Pokémon.$"


morty_Text_10::
  .string "...Oh wow, you even got your own {COLOR GREEN}Mega\n"
  .string "Ring{COLOR BLUE}.\p"
  .string "If you show me a Pokémon with max\n"
  .string "happiness, I'll gladly give you a\l"
  .string "{COLOR GREEN}Gengarite{COLOR BLUE}.$"


morty_Text_11::
  .string "Your {STR_VAR_1}...$"


morty_Text_12::
  .string "It clearly adores you!\p"
  .string "I'm impressed.\p"
  .string "As promised, here you go.$"


morty_Text_13::
  .string "Hmm... it could still use some work...$"


aideverstone_Text_Msg::
  .string "Hi! Remember me?\n"
  .string "I'm one of Prof. Oak's Aides.\p"
  .string "He entrusted me to give you this\n"
  .string "{COLOR GREEN}Everstone.{COLOR BLUE}$"


aideverstone_Text_1::
  .string "Making Pokémon evolve certainly\n"
  .string "can add to the Pokédex.\p"
  .string "However, at times, you may not\n"
  .string "want a certain Pokémon to evolve.\p"
  .string "In that case, give the Everstone\n"
  .string "to that Pokémon.\p"
  .string "It will prevent evolution according\n"
  .string "to the Professor.$"


amarowak_Text_Begone::
  .string "Be gone...\n"
  .string "Intruders...$"


amarowak_Text_Ghostwas::
  .string "The ghost was the restless spirit\n"
  .string "of Cubone's mother!$"


amarowak_Text_Calmdown::
  .string "The mother's spirit was calmed.\p"
  .string "It departed to the afterlife...\p"
  .string "An item remains in its faint residue...$"


AudinoSlayer_Text_1::
  .string "Hi there! I offer a very special\n"
  .string "service.\p"
  .string "For a measly \$10000, you can slaugh-\n"
  .string "ter a family of Audinos!\p"
  .string "Or \$2000 for my EV training services.\p"
  .string "How about it?$"


AudinoSlayer_Text_1_Hard::
  .string "Hi there! I offer a very special\n"
  .string "service.\p"
  .string "For a measly \$10000, you can slaugh-\n"
  .string "ter a family of Audinos!\p"
  .string "How about it?$"


AudinoSlayer_Text_Choose::
  .string "Which service would you like?$"


AudinoSlayer_Text_EXP::
  .string "Exp$"


AudinoSlayer_Text_2::
  .string "Very well. Let's begin.$"


AudinoSlayer_Text_3::
  .string "Yeah, I feel you.\n"
  .string "It do seem kinda unethical.$"


AudinoSlayer_Text_Defeat::
  .string "What a lovely massacre!$"


AudinoSlayer_Text_4::
  .string "Well, it appears these Audinos will\n"
  .string "live to see another day!\p"
  .string "You don't have enough money!$"


AudinoSlayer_Text_EV_4::
  .string "Well, it appears these Pokémon will\n"
  .string "live to see another day!\p"
  .string "You don't have enough money!$"


AudinoSlayer_Text_5::
  .string "Come back any time.$"


AudniSlayer_Text_Wait::
  .string "...$"


morty_Text_Rematch_1::
  .string "{COLOR BLUE}Oh, hello {COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "Nice of you to visit me!\p"
  .string "I've actually travelled a bit\n"
  .string "and honed my skills since we've last\l"
  .string "battled.\p"
  .string "How about another go at it?$"


morty_Text_Rematch_2::
  .string "{COLOR BLUE}Brilliant.\n"
  .string "Push me to my limits, champion!$"


morty_Text_Rematch_3::
  .string "{COLOR BLUE}Ah, I really expected nothing less\n"
  .string "from you. How impressive!\p"
  .string "I'd like to thank you for taking\n"
  .string "your time to visit me; you must be\l"
  .string "quite the busy bee now.\p"
  .string "For a well-fought battle, have this.$"


morty_Text_Rematch_4::
  .string "{COLOR BLUE}Your discipline is admirable.\p"
  .string "Keep being you, {COLOR GREEN}{PLAYER}{COLOR BLUE}.$"


Lavender_Text_Furret::
  .string "Furr furr!$"


Lavender_Text_Gengar::
  .string "Gar gar!$"


