mistyexplode_Text_3::
  .string "Can you imagine?\n"
  .string "If this volcano were to erupt?\p"
  .string "The explosion would be the end of\n"
  .string "us. How terrifying is that?\p"
  .string "While we're terrified, would you\n"
  .string "like to learn {COLOR GREEN}Misty Explosion?{COLOR BLUE}$"


mistyexplode_Text_4::
  .string "You're terribly brave!\p"
  .string "Go, have at it!$"


mistyexplode_Text_5::
  .string "Using {COLOR GREEN}Misty Explosion{COLOR BLUE} while on this\n"
  .string "volcano...\p"
  .string "What a terrifying thrill!$"


mistyexplode_Text_6::
  .string "Yeah, you're right.\n"
  .string "It is too terrifying.$"


mtember_Text_grunt1_1::
  .string "Call us an active volcano,\n"
  .string "'cause Team Magma is about to erupt!$"


mtember_Text_grunt1_2::
  .string "Well... Only thing that's erupting from\n"
  .string "me is my sweat...$"


mtember_Text_grunt1_3::
  .string "They say there're over 1,500\n"
  .string "active volcanoes in the world.\p"
  .string "Just thinking about them makes me\n"
  .string "feel all hot and gooey inside!$"


mtember_Text_grunt2_1::
  .string "I've been in Team Magma so I can mend\n"
  .string "my broken heart...\p"
  .string "...ya calling me a simp?\n"
  .string "Come here, kid!$"


mtember_Text_grunt2_2::
  .string "J-just leave me alone...$"


mtember_Text_grunt2_3::
  .string "The way you battle, it reminds me\n"
  .string "of the girl who dumped me...\p"
  .string "I felt so lost afterwards, and joined\n"
  .string "Team Magma. The brotherhood\l"
  .string "makes me feel less lonely.$"


mtember_Text_grunt3_1::
  .string "Do you know how caves form inside\n"
  .string "volcanoes?$"


mtember_Text_grunt3_2::
  .string "Tsk. You wanna know more\n"
  .string "about volcanoes or what?$"


mtember_Text_grunt3_3::
  .string "When lava at the surface of magma\n"
  .string "hardens, and the magma inside flows\l"
  .string "out, caverns are left behind.$"


mtember_Text_ariana_1::
  .string "Hmm, so {COLOR GREEN}Moltres{COLOR RED} used to be\n"
  .string "found here...\p"
  .string "Now, it's found back in its\n"
  .string "original location at Victory Road.$"


mtember_Text_ariana_22::
  .string "Now it's been replaced with...$"


mtember_Text_ariana_2::
  .string "{COLOR RED}... oh? Well, I did say I'd hope to\n"
  .string "see you as Champion if we met again!\p"
  .string "What a pleasant surprise.\p"
  .string "Well, there's no way I'd pass up\n"
  .string "a battle against you.\p"
  .string "Sorry, you're on!$"


MtEmber_Text_arianaLoss::
  .string "Hah, if only I had Archer to\n"
  .string "back me up like last time.$"


mtember_Text_ariana_3::
  .string "{COLOR GREEN}Archer {COLOR RED}and I have been checking\n"
  .string "out the Seviis since our last scuffle.\p"
  .string "There's quite a few interesting things\n"
  .string "here, like Pokémon having the potential\l"
  .string "to evolve into their Hisuian forms\l"
  .string "here.\p"
  .string "Not only that, there are some\n"
  .string "exclusive Seviian forms found here too.\p"
  .string "Here, follow me so {COLOR GREEN}Archer{COLOR RED} could\n"
  .string "tell you some more.$"


mtember_Text_archer1::
  .string "{COLOR GREEN}Archer: {COLOR BLUE}Hmm, so Heatran's here\n"
  .string "instead eh...$"


mtember_Text_archer2::
  .string "{COLOR GREEN}Ariana: {COLOR RED}Hey {COLOR GREEN}Archer, {PLAYER}{COLOR RED}\n"
  .string "happened to be here.$"


mtember_Text_archer3::
  .string "{COLOR GREEN}Archer:{COLOR BLUE} Oh hey!\n"
  .string "Good to see you, {COLOR GREEN}{PLAYER}!\p"
  .string "{COLOR BLUE}Have you given him the run-down\n"
  .string "of the Sevii Islands?$"


mtember_Text_archer4::
  .string "{COLOR GREEN}Ariana: {COLOR RED}I've told him a bit,\n"
  .string "you can tell him of your findings\l"
  .string "though.$"


mtember_Text_archer5::
  .string "{COLOR BLUE}Well, I'll give you the full rundown\n"
  .string "shortly. Let's put this {COLOR GREEN}Heatran{COLOR BLUE}\l"
  .string "to the test!$"


MtEmber_Text_MaxieLoss::
  .string "Some things never change.$"


mtember_Text_archer6::
  .string "{COLOR BLUE}I'm mostly here to investigate\n"
  .string "the different Legendaries that\l"
  .string "have appeared here in the Seviis.\p"
  .string "Supposedly, legendaries from other\n"
  .string "regions have made their home in some\l"
  .string "existing areas even in Kanto.\p"
  .string "How they've come here, I'm not\n"
  .string "sure.$"


mtember_Text_archer7::
  .string "{COLOR BLUE}But, I do know the boss ran into\n"
  .string "his kid here.\p"
  .string "I think last I heard they\n"
  .string "travelled to Navel Rock to see\l"
  .string "if Ho-Oh and Lugia are still present\l"
  .string "there.$"


mtember_Text_archer8::
  .string "{COLOR BLUE}Well, let us know if your findings\n"
  .string "if we see each other again.\p"
  .string "Here, have this.$"


mtember_Text_archer9::
  .string "You received an {COLOR GREEN}Aerodactyl!$"


mtember_Text_archer10::
  .string "{COLOR BLUE}This is a special {COLOR GREEN}Aerodactyl{COLOR BLUE}\n"
  .string "with exclusive moves Brave Bird\l"
  .string "and Headlong Rush.\p"
  .string "Brave Bird's a cool combo with Rock\n"
  .string "Head, and a potent STAB for its Mega,\l"
  .string "while Headlong Rush also gets boosted\l"
  .string "by Tough Claws.\p"
  .string "Unfortunate I couldn't find one\n"
  .string "with Head Smash!\p"
  .string "Well, until next time.\p"
  .string "Oh, and if you'd like {COLOR GREEN}Heatran,{COLOR BLUE}\n"
  .string "he's all yours!$"


MtEmber_Text_Heatran1::
  .string "Gwogobo gwobobobo!$"


