MtMoon_Text_MuscleBand1::
  .string "Hi, I'm excavating for fossils here\n"
  .string "under {COLOR GREEN}Mt. Moon{COLOR BLUE}.\p"
  .string "Sometimes, {COLOR GREEN}Brock{COLOR BLUE} of {COLOR GREEN}Pewter Gym{COLOR BLUE} lends\n"
  .string "me a hand.$"


MtMoon_Text_MuscleBand2::
  .string "...Oh? You beat him?!\n"
  .string "That's admirable!\p"
  .string "Perhaps you could make use out of\n"
  .string "this.$"


adminmtmoonleft_Text_1::
  .string "HEY YOU! Wait right there!$"


adminmtmoonleft_Text_2::
  .string "Are you the twerp messing with my\n"
  .string "grunts?\p"
  .string "...Little kid, you think you're brave,\n"
  .string "eh?\p"
  .string "I'll teach you a valuable lesson.$"


adminmtmoonleft_Text_Defeat::
  .string "What a shameful blunder...$"


adminmtmoonleft_Text_4::
  .string "Whatever, we've done everything we\n"
  .string "needed.\p"
  .string "I won't be as nice to you next\n"
  .string "time.\p"
  .string "...I'll be seeing you, {COLOR GREEN}{PLAYER}.$"


cobalion_Text_12::
  .string "Kawbraa$"


