newcut_Text_Nocut::
  .string "This tree looks like it can be Cut\n"
  .string "down!$"


newstrength_Text_Cantpush::
  .string "It's a big boulder, but you may learn\n"
  .string "to push it aside...$"


newstrength_Text_Madeitpossible::
  .string "Strength made it possible to move\n"
  .string "boulders around.$"


newstrength_Text_Strengthtxt::
  .string "HM Strength made it possible to\n"
  .string "move boulders around!$"


newrocksmash_Text_Nosmash::
  .string "It's a rugged rock, but a Pokémon\n"
  .string "may be able to smash it$"


