TeleportToKanto_Text::
  .string "Do you want me to Teleport you\n"
  .string "to Kanto?$"


OneIslandJotard_Text_1::
  .string "{COLOR BLUE}Well well, if it isn't the Jojo\n"
  .string "hater. Became champion, did ya?$"


OneIslandJotard_Text_2::
  .string "{COLOR BLUE}...why the long look on your face?$"


OneIslandJotard_Text_3::
  .string "{COLOR BLUE}Ah, I get it!\p"
  .string "You were expecting {COLOR GREEN}Silver{COLOR BLUE} to be\n"
  .string "your post-game rival, but it was me,\l"
  .string "{COLOR GREEN}Jojo Fan!$"


OneIslandJotard_Text_4::
  .string "{COLOR BLUE}I'll add to your disappointment\n"
  .string "with a crushing defeat by the hands\l"
  .string "of my Stand powers.$"


OneIslandJotard_Text_Defeated::
  .string "Kuso...$"


OneIslandJotard_Text_5::
  .string "{COLOR BLUE}Alright, fine.\n"
  .string "I acknowledge your strength,\l"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}.\p"
  .string "I'll share my Stand technique with you.$"


OneIslandJotard_Text_6::
  .string "{COLOR BLUE}That enables you to use Z-Moves,\n"
  .string "which allows you to release a strong\l"
  .string "move once per battle.\p"
  .string "Of course, you must have the right\n"
  .string "Z-Crystal to go along with it.\p"
  .string "And to go along with that,\n"
  .string "have some ORA ORA ORA!$"


OneIslandJotard_Text_6_2::
  .string "{COLOR BLUE}...Oh? Is that not the stand tech-\n"
  .string "nique you're interested in?\p"
  .string "You'd like to know how to Mega\n"
  .string "Evolve twice in a battle?\p"
  .string "That's difficult to be taught.\n"
  .string "In time you might learn about\n"
  .string "it.\p"
  .string "Anyway...$"


OneIslandJotard_Text_7::
  .string "{COLOR BLUE}I think I've seen some Team Rocket\n"
  .string "members around here, although they\l"
  .string "didn't seem to be posing\l"
  .string "problems or anything.\p"
  .string "No idea what they're up to, but I fi-\n"
  .string "gured our main protagonist ought\l"
  .string "to know!\p"
  .string "Anyway, catch you later!$"


OneIslandJotard_Text_8::
  .string "{COLOR BLACK}Jojo fan walked away, menacingly...$"


waterfallhm_Text_Handinhand::
  .string "Hot springs go hand-in-hand with\n"
  .string "volcanoes.\p"
  .string "The Ember Spa here, well,\n"
  .string "I made it years ago.\p"
  .string "I hewed the pool right out of a\n"
  .string "gigantic boulder by hand.\p"
  .string "I was using this at the time.\n"
  .string "I suppose I can part with it.\p"
  .string "...Huh, you already have this!\p"
  .string "Well, perhaps you'd find this useful\n"
  .string "instead.$"


waterfallhm_Text_Shatterstxt::
  .string "That allows you to traverse waterfalls\n"
  .string "with ease.$"


TreasureBeach_Text_Red1::
  .string "...$"


TreasureBeach_Text_Red2::
  .string "{COLOR BLACK}It seems Red wants you to have these...$"


TreasureBeach_Text_Red3::
  .string "{COLOR BLACK}Red also wants you to have a special\n"
  .string "Pikachu Libre, with Aura Wheel and\l"
  .string "252 EVs in all its stats.\p"
  .string "It's amazing Red is able to\n"
  .string "convey so much information with his gaze!$"


TreasureBeach_Text_Red4::
  .string "{COLOR BLACK}You received a Pikachu!$"


TreasureBeach_Text_Red5::
  .string "{COLOR BLUE}...$"


TreasureBeach_Text_Red3_2::
  .string "{COLOR BLACK}Red also wants you to have a special\n"
  .string "Pikachu Libre, with Aura Wheel. It\l"
  .string "also has 100 EVs in its offensive\l"
  .string "stats, and maxed out Speed EVs.\p"
  .string "Seems like he cheated to stay\n"
  .string "on top!$"


OneIsland_Text_RandomBattler1::
  .string "{COLOR BLACK}Hello, welcome to the One Island\n"
  .string "Battle Simulator.\p"
  .string "You can fight various random boss\n"
  .string "trainers from this region to hone\l"
  .string "your skills, and potentially receive\l"
  .string "prizes.$"


OneIsland_Text_NormalTrainerHiScore::
  .string "Your current high score for Normal\n"
  .string "Mode is {STR_VAR_1}.\p"
  .string "Would you like to start the battle\n"
  .string "simulator on Normal Mode?$"


OneIsland_Text_HCTrainerHiScore::
  .string "Your current high score for Hardcore\n"
  .string "Mode is {STR_VAR_1}.\p"
  .string "Would you like to start the battle\n"
  .string "simulator on Hardcore Mode?$"


OneIsland_Text_RandomBattler1_1::
  .string "Would you like to battle?$"


OneIsland_Text_BattleStart::
  .string "{COLOR BLACK}Random trainer generated.\n"
  .string "Battle commencing.$"


RandomBattlerWon_Text::
  .string "Battle won.$"


RandomBattlerLost_Text::
  .string "Battle lost.$"


WouldYouLikeToContinue_Text::
  .string "Well played trainer.\n"
  .string "Your current win streak is {STR_VAR_1}.\p"
  .string "Would you like to continue?$"


RandomBattlerEnd_Text::
  .string "You ended with a win streak of {STR_VAR_1}.\n"
  .string "Your high score is {STR_VAR_2}.$"


RandomBattler_Text_NewHighScore::
  .string "You ended with a win streak of {STR_VAR_1},\n"
  .string "a new high score.\p"
  .string "Congratulations!$"


TeamHasBeenHealed_Text::
  .string "Your team has been healed.$"


WouldYouLikeToHeal_Text::
  .string "Would you like to heal your team?$"


HealTeam _Text::
  .string "...$"


RandomBattler_Text_RedIsHere::
  .string "{COLOR BLACK}A powerful trainer has sensed your\n"
  .string "presence, and awaits you in Treasure\l"
  .string "Beach.$"


BattleSim_Text_Normal::
  .string "Normal$"


BattleSim_Text_Hardcore::
  .string "Hardcore$"


Info_Text::
  .string "Info$"


BattleSim_Text_MasterBall::
  .string "Here is a reward for receiving a win\n"
  .string "streak of {STR_VAR_1}.$"


BattleSim_Text_Info::
  .string "{COLOR BLACK}Normal option allows you to fight\n"
  .string "various boss battles from Normal\l"
  .string "Mode.\p"
  .string "Hardcore option allows you to fight\n"
  .string "various boss battles from\l"
  .string "Hardcore Mode.\p"
  .string "You stop receiving heals after\n"
  .string "a win streak of 10.$"


OneIsland_Text_EnamorusRoaming::
  .string "A new legendary Pokémon may be found\n"
  .string "roaming the Kanto Region.$"


OneIsland_Text_CosmogPrize::
  .string "As a reward for your impressive\n"
  .string "win streak, you have been awarded\l"
  .string "this rare Pokémon.$"


OneIsland_Text_PkmnReceived::
  .string "You received a {COLOR GREEN}{STR_VAR_1}!{COLOR BLACK}$"


AddBattlePoints_Text::
  .string "You received {COLOR GREEN}{STR_VAR_1} BP.{COLOR GREEN}\n"
  .string "{COLOR BLACK}You now have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


ExchangeItems_Text::
  .string "Exchange BP$"


MasterBall_Text::
  .string "{COLOR BLACK}Master Ball          {COLOR GREEN}3 BP$"


TapuniumZ_Text::
  .string "{COLOR BLACK}Tapunium Z           {COLOR GREEN}3 BP$"


SnorliumZ_Text::
  .string "{COLOR BLACK}Snorlium Z           {COLOR GREEN}3 BP$"


PikaniumZ_Text::
  .string "{COLOR BLACK}Pikanium Z           {COLOR GREEN}3 BP$"


PikashuniumZ_Text::
  .string "{COLOR BLACK}Pikashunium Z        {COLOR GREEN}3 BP$"


AloRachiumZ_Text::
  .string "{COLOR BLACK}Aloraichium Z        {COLOR GREEN}5 BP$"


InciniumZ_Text::
  .string "{COLOR BLACK}Incinium Z           {COLOR GREEN}5 BP$"


DecidiumZ_Text::
  .string "{COLOR BLACK}Decidium Z           {COLOR GREEN}5 BP$"


PrimariumZ_Text::
  .string "{COLOR BLACK}Primarium Z          {COLOR GREEN}5 BP$"


LycaniumZ_Text::
  .string "{COLOR BLACK}Lycanium Z           {COLOR GREEN}5 BP$"


FlyingGem_Text::
  .string "{COLOR BLACK}Flying Gem           {COLOR GREEN}15 BP$"


Diancite_Text::
  .string "{COLOR BLACK}Diancite             {COLOR GREEN}20 BP$"


KommoniumZ_Text::
  .string "{COLOR BLACK}Kommonium Z          {COLOR GREEN}25 BP$"


NLunarizer_Text::
  .string "{COLOR BLACK}Necrozmizer          {COLOR GREEN}25 BP$"


NLunarizerSold_Text::
  .string "{COLOR BLACK}Necrozmizer          {COLOR RED}SOLD$"


NSolarizer_Text::
  .string "{COLOR BLACK}N-Solarizer          {COLOR GREEN}25 BP$"


CosmogBP_Text::
  .string "{COLOR BLACK}Cosmog                  {COLOR GREEN}50 BP$"


CosmogSoldOut_Text::
  .string "{COLOR BLACK}Cosmog               {COLOR RED}SOLD$"


UltraNecroziumZ_Text::
  .string "{COLOR BLACK}Ultranecrozium Z     {COLOR GREEN}50 BP$"


Zygarde10Per_Text::
  .string "{COLOR BLACK}Booster Energy       {COLOR GREEN}15 BP$"


MoreBPStuff_Text::
  .string "More$"


BpExit_Text::
  .string "Exit$"


WhichBPItemYouWant_Text::
  .string "Which item would you like?\n"
  .string "You have {COLOR GREEN}{STR_VAR_1} BP.{COLOR BLACK}$"


NotEnoughBP_Text::
  .string "...Unfortunately you don't have\n"
  .string "enough BP.$"


WouldYoulike3BP_Text::
  .string "You want {STR_VAR_1} for {COLOR GREEN}3 BP?\n"
  .string "{COLOR BLACK}You have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


WouldYoulike5BP_Text::
  .string "You want {STR_VAR_1} for {COLOR GREEN}5 BP?\n"
  .string "{COLOR BLACK}You have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


WouldYoulike15BP_Text::
  .string "You want {STR_VAR_1} for {COLOR GREEN}15 BP?\n"
  .string "{COLOR BLACK}You have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


WouldYoulike20BP_Text::
  .string "You want {STR_VAR_1} for {COLOR GREEN}20 BP?\n"
  .string "{COLOR BLACK}You have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


WouldYoulike25BP_Text::
  .string "You want {STR_VAR_1} for {COLOR GREEN}25 BP?\n"
  .string "{COLOR BLACK}You have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


WouldYoulike50BP_Text::
  .string "You want {STR_VAR_1} for {COLOR GREEN}50 BP?\n"
  .string "{COLOR BLACK}You have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


TransactionCompleted_Text::
  .string "Transaction completed.\n"
  .string "You now have {COLOR GREEN}{STR_VAR_2} BP.{COLOR BLACK}$"


TransactionDotDotDot_Text::
  .string "...$"


AlreadyBoughtCosmog_Text::
  .string "...You already bought {COLOR GREEN}Cosmog.{COLOR BLACK}$"


AlreadyBoughtLunarizer_Text::
  .string "...You already bought this item.$"


ReceivedBonusPoints_Text::
  .string "You received a bonus of {COLOR GREEN}5 BP{COLOR BLACK}\n"
  .string "for this high score.$"


BonusBattlePoints10Streak_Text::
  .string "For getting above a win streak of\n"
  .string "10, you received an additional {COLOR GREEN}5 BP.{COLOR BLACK}\p"
  .string "You now have {COLOR GREEN}{STR_VAR_1} BP.{COLOR BLACK}$"


OneIsland_Text_HisuainForms::
  .string "Apparently, some Pokémon are able\n"
  .string "to evolve into their Hisuian forms\l"
  .string "here in the Sevii Islands.$"


