Pallet_Text_Technology1::
  .string "Technology is incredible!\p"
  .string "You can now sort items in the bag\n"
  .string "using the Start button!$"


Pallet_Text_AutoRunSign1 ::
  .string "It's a posted notice...\p"
  .string "Press {L_BUTTON} to bring up the skills\n"
  .string "menu!$"


Pallet_Text_Mom::
  .string "{COLOR GREEN}Mom: {COLOR RED}Hi sweetie!\p"
  .string "Congratulations on becoming champ-\n"
  .string "ion!\p"
  .string "For the first time ever, I can final-\n"
  .string "ly say I'm proud of you!\p"
  .string "Great job!$"


Pallet_Text_MomPost ::
  .string "If you're looking for more\n"
  .string "trainers to fight, I hear a seer\l"
  .string "on Route 16 gives tickets to the\l"
  .string "Sevii Islands to those worthy...\p"
  .string "Perhaps you ought to give her a\n"
  .string "visit?\p"
  .string "Also...$"


Pallet_Text_Mom2::
  .string "{COLOR RED}There are a lot of new perks after\n"
  .string "becoming Champion.\p"
  .string "The EV training gear instantly max out\n"
  .string "the EVs for the respective stat.\p"
  .string "Oh, and the prize money from trainers\n"
  .string "is doubled!\p"
  .string "The rich just get richer, am I right?\p"
  .string "Well, good luck {COLOR GREEN}{PLAYER}!$"


Pallet_Text_MomCarePackage::
  .string "{COLOR RED}Oh, also!\n"
  .string "As a part of the care package cheat,\l"
  .string "these are yours!$"


mom_Text_RestText::
  .string "{COLOR GREEN}Mom: {PLAYER}!{COLOR RED}\n"
  .string "You should take a quick rest.$"


mom_Text_LookGreat::
  .string "{COLOR GREEN}Mom{COLOR RED}: Oh, good! You and your\n"
  .string "Pokémon are looking great.\l"
  .string "Take care now!$"


mom_Text_AllBoysTxt::
  .string "{COLOR GREEN}Mom:{COLOR RED} ...Right.\n"
  .string "All boys leave home someday.\l"
  .string "It said so on TV.\p"
  .string "Oh, yes. {COLOR GREEN}Prof. Oak{COLOR RED}, next door, was\n"
  .string "looking for you.$"


mom_Text_AllGirlsTxt::
  .string "{COLOR GREEN}Mom:{COLOR RED} ...Right.\n"
  .string "All girls dream of traveling.\l"
  .string "It said so on TV.\p"
  .string "Oh, yes. {COLOR GREEN}Prof. Oak{COLOR RED}, next door, was\n"
  .string "looking for you.$"


mom_Text_RestText2::
  .string "{COLOR GREEN}Mom:{COLOR RED} My champion {COLOR GREEN}{PLAYER}!\n"
  .string "{COLOR RED}Take a quick rest.$"


mom_Text_LetsCelebrate::
  .string "{COLOR GREEN}Mom:{COLOR RED} To commemorate your fine\n"
  .string "accomplishment, shall I teach a Poké-\l"
  .string "mon Celebrate?$"


mom_Text_WhyCelebrate::
  .string "{COLOR RED}Ah. It may seem like a useless move,\n"
  .string "but it's a great stat booster when\l"
  .string "used in tandem with Normalium Z.$"


mom_Text_GreatJob::
  .string "{COLOR RED}Yay! Great job sweetie.$"


WouldYouDiffRegion_Text::
  .string "{COLOR BLACK}Would you like your starter\n"
  .string "to be a different region?$"


WhichRegion_Text::
  .string "{COLOR RED}Which region would you like your start-\n"
  .string "ers to be instead of Kanto?$"


JohtoStarter_Text::
  .string "{COLOR RED}Ooh okay! Johto it is!\n"
  .string "I'll let him know.$"


HoennStarter_Text::
  .string "{COLOR RED}Ooh okay! Hoenn it is!\n"
  .string "I'll let him know.$"


SinnohStarter_Text::
  .string "{COLOR RED}Ooh okay! Sinnoh it is!\n"
  .string "I'll let him know.$"


UnovaStarter_Text::
  .string "{COLOR RED}Ooh okay! Unova it is!\n"
  .string "I'll let him know.$"


KalosStarter_Text::
  .string "{COLOR RED}Ooh okay! Kalos it is!\n"
  .string "I'll let him know.$"


AlolaStarter_Text::
  .string "{COLOR RED}Ooh okay! Alola it is!\n"
  .string "I'll let him know.$"


GalarStarter_Text::
  .string "{COLOR RED}Ooh okay! Galar it is!\n"
  .string "I'll let him know.$"


PaldeaStarter_Text::
  .string "{COLOR RED}Ooh okay! Paldea it is!\n"
  .string "I'll let him know.$"


StarterPokemon_Text_ContainPkmn::
  .string "Those are Poké Balls.\n"
  .string "They contain Pokémon!$"


StarterPokemon_Text_MsgLastPkmn::
  .string "That's one of{COLOR GREEN} Prof. Oak's{COLOR BLACK} Pokémon.$"


StarterPokemon_Text_Bulbasaurtxt::
  .string "I see! {COLOR GREEN}{STR_VAR_2}{COLOR BLUE} is your choice.\n"
  .string "It's very easy to raise.\p"
  .string "So, {COLOR GREEN}{PLAYER}{COLOR BLUE}, you want to go with\n"
  .string "the Grass Pokémon {COLOR GREEN}{STR_VAR_2}?$"


StarterPokemon_Text_Squirtletxt::
  .string "Hm! {COLOR GREEN}{STR_VAR_2}{COLOR BLUE} is your choice.\n"
  .string "It's one worth raising.\p"
  .string "So, {COLOR GREEN}{PLAYER}{COLOR BLUE}, you've decided on the\n"
  .string "Water Pokémon {COLOR GREEN}{STR_VAR_2}?$"


StarterPokemon_Text_Charmandertxt::
  .string "Ah! {COLOR GREEN}{STR_VAR_2}{COLOR BLUE} is your choice.\n"
  .string "You should raise it patiently.\p"
  .string "So, {COLOR GREEN}{PLAYER}{COLOR BLUE}, you're claiming the\n"
  .string "Fire Pokémon {COLOR GREEN}{STR_VAR_2}?$"


StarterPokemon_Text_Energetic::
  .string "This Pokémon is really quite\n"
  .string "energetic!$"


StarterPokemon_Text_Receivedthepkmn::
  .string "{PLAYER} received the {STR_VAR_1}\n"
  .string "from Prof. Oak!$"


StarterPokemon_Text_Givenickname::
  .string "Do you want to give a nickname to\n"
  .string "this {STR_VAR_1}?$"


StarterPokemon_Text_Rivaltake::
  .string "{RIVAL}: I'll take this one, then!$"


StarterPokemon_Text_Rivalreceive::
  .string "{RIVAL} received the {STR_VAR_1}\n"
  .string "from Prof. Oak!$"


Pallet_Text_ProfAsks::
  .string "{COLOR GREEN}Mom: {COLOR RED}Hey {COLOR GREEN}{PLAYER}!\p"
  .string "{COLOR RED}The professor wanted to ask if you\n"
  .string "had a preference on which region\l"
  .string "your starter was from?$"


Pallet_Text_OkTakeCare::
  .string "{COLOR RED}Ah okay then!\n"
  .string "Take care sweetie!$"


Pallet_Text_GaryWantKanto::
  .string "{COLOR GREEN}{RIVAL}: {COLOR BLUE} Hey gramps! I thought I\n"
  .string "asked for a Kanto starter!\p"
  .string "{COLOR GREEN}Oak: {COLOR BLUE}Fine, fine.\n"
  .string "You can have this last one I still\l"
  .string "have leftover.$"


PalletGary_Text_WayCooler::
  .string "{COLOR GREEN}{RIVAL}: {COLOR BLUE}Heh!\n"
  .string "{COLOR GREEN}{STR_VAR_1}{COLOR BLUE} looks way cooler\l"
  .string "than this piece of garbage!$"


TimeChangerAide_Text_1::
  .string "{COLOR BLUE}Hey {COLOR GREEN}{PLAYER}!\p"
  .string "{COLOR BLUE}I've been working on a prototype\n"
  .string "for a time changer device.\p"
  .string "Surely, you could find this useful.\p"
  .string "I could teach it to you if\n"
  .string "you can handle some trivia.\p"
  .string "You want to give it a go?$"


TimeChangerAide_Text_2::
  .string "{COLOR BLUE}Okay, let's get started.\p"
  .string "Which of these do not have\n"
  .string "a night specific evolution?$"


TimeChangerPancham_Text::
  .string "Pancham$"


TimeChangerAurora_Text::
  .string "Amaura$"


TimeChangerEevee_Text::
  .string "Eevee$"


TimeChangercubone_Text::
  .string "Cubone$"


TimeChangerAide_Text_NotCorrect::
  .string "Oof, that doesn't seem to be correct.$"


TimeChangerAide_Text_3::
  .string "What time do night-time encounters\n"
  .string "start?$"


TimeChanger5PM_Text::
  .string "5 PM$"


TimeChanger8PM_Text::
  .string "8 PM$"


TimeChanger11PM_Text::
  .string "11 PM$"


TimeChangerAide_Text_Correct::
  .string "Correct! Next one...$"


TimeChangerAide_Text_CorrectFinal::
  .string "Nice, that's right! Final question...$"


TimeChangerAide_Text_4::
  .string "When is the final version of Radical\n"
  .string "Red coming out?$"


TimeChangerAide_Text_2023::
  .string "2023$"


TimeChangerAide_Text_2030::
  .string "2030$"


TimeChangerAide_Text_Never::
  .string "Never$"


TimeChangerAide_Text_5::
  .string "I guess you don't miss! Alright,\n"
  .string "here you go.$"


TimeChanger_Text_Unlock::
  .string "{COLOR BLACK}You unlocked the Time Changer!$"


TimeChangerAide_Text_6::
  .string "To use the Time Changer, press {L_BUTTON}\n"
  .string "to bring up your skills.\p"
  .string "Use it, and choose a time of\n"
  .string "day to change to.\p"
  .string "Note that you'll be stuck in\n"
  .string "that time of day until you\l"
  .string "click the Reset option or change\l"
  .string "to another time of day.$"


PalletTown_Text_OakFight1::
  .string "Well, {COLOR GREEN}{PLAYER}{COLOR BLUE}, I knew you had\n"
  .string "a lot in you, but I never would\l"
  .string "have guessed you'd become Champ!\p"
  .string "Not this quick!\p"
  .string "Well, I'm nowhere as strong as I was\n"
  .string "in my prime, but I could cause you\l"
  .string "some trouble.\p"
  .string "I've got a new item I've been\n"
  .string "working on that I'd like to test.\p"
  .string "How about it?$"


PalletTown_Text_OakFight2::
  .string "Alright, let's see if these old\n"
  .string "bones still got it!$"


PalletTown_Text_OakScared::
  .string "Scared of this old timer?\n"
  .string "Wahahaha!$"


PalletTown_Text_OakWarmup::
  .string "Hm, that was just a warm up.$"


PalletTown_Text_OakStillGot::
  .string "Huh, you thought we were done?\n"
  .string "This old man still has more left\l"
  .string "in him!$"


PalletTown_Text_LossForReal::
  .string "Okay, okay.\n"
  .string "You got me.$"


PalletTown_Text_OakFight3::
  .string "Heh, sorry to cheat like that,\n"
  .string "{COLOR GREEN}{PLAYER}.\p"
  .string "{COLOR BLUE}I knew I had to throw everything\n"
  .string "and the kitchen sink at you to\l"
  .string "stand a chance.\p"
  .string "Here, have the item I've been\n"
  .string "working on.\p"
  .string "The Eevium Z normally only works\n"
  .string "on Eevee, but I've polished it to\l"
  .string "work on its evolutions as well.\p"
  .string "Although on Eevee, it gives +2 to all\n"
  .string "stats, it only gives +2 to\l"
  .string "offensive stats on the Eeveelutions.\p"
  .string "You need Last Resort to proc this.\p"
  .string "Still not a bad item at all!\p"
  .string "All yours!$"


PalletTown_Text_OakFight4::
  .string "Well, get back at it, {COLOR GREEN}{PLAYER}.\p"
  .string "{COLOR BLUE}I'm sure {COLOR GREEN}{RIVAL}{COLOR BLUE} is still\n"
  .string "training to become stronger, so\l"
  .string "don't fall behind.$"


PalletTown_Text_AideStop1::
  .string "{COLOR BLUE}Hey {COLOR GREEN}{PLAYER}!\p"
  .string "Starting on your journey eh?\n"
  .string "Must be exciting!\p"
  .string "Anyway, the professor told me not to\n"
  .string "let any newbies through here.\p"
  .string "Sorry about that!$"


PalletTown_Text_AideStop2::
  .string "{COLOR BLUE}Hey {COLOR GREEN}{PLAYER},{COLOR BLUE} I can't let you\n"
  .string "through here just yet.$"


PalletTown_Text_AideBattle1::
  .string "{COLOR BLUE}Ah, I see you've got yourself\n"
  .string "a Pokédex from the professor.\p"
  .string "I suppose I could let you through\n"
  .string "now, although you'd have to prove\l"
  .string "it to me in a battle.$"


PalletTown_Text_NeedMoreThan1::
  .string "{COLOR BLUE}...I'm warning you, you might\n"
  .string "need more than 1 Pokémon to\l"
  .string "defeat me...$"


PalletTown_Text_AideBattle2::
  .string "{COLOR BLUE}How about it?$"


Pallet_Text_ProfAideDefeat::
  .string "You've got potential!$"


PalletProfAideBattle3_Text::
  .string "{COLOR BLUE}Heh, thanks for entertaining me\n"
  .string "{COLOR GREEN}{PLAYER}.\p"
  .string "Here's a parting gift from\n"
  .string "me.$"


PalletProfAideBattle4_Text::
  .string "Well, Route 21's all yours!\p"
  .string "See you around {COLOR GREEN}{PLAYER}.{COLOR BLUE}$"


Pallet_Text_ProfDoneText::
  .string "Icy Wind is a decent early game\n"
  .string "tool, and it hits both targets\l"
  .string "in doubles.$"


PalletProfAideRejected_Text::
  .string "Well, Route 21 has some Pokémon\n"
  .string "you won't find elsewhere.\p"
  .string "I wouldn't miss out on it.$"


Pallet_Text_Stufful::
  .string "{COLOR BLACK}Stufful!$"


Pallet_Text_LassStuff1::
  .string "{COLOR GREEN}Stufful...\n"
  .string "{COLOR RED}Do you really have to lay down\l"
  .string "here of all places?\p"
  .string "We're blocking the way to Route 21!$"


Pallet_Text_LassStuff2::
  .string "{COLOR RED}I'm so sorry, my {COLOR GREEN}Stufful\n"
  .string "{COLOR RED}has been in a mood lately...\p"
  .string "We'll be out of your way soon.$"


