Pewter_Text_GiveDmax1::
  .string "{COLOR BLUE}Hey, {COLOR GREEN}{PLAYER}{COLOR BLUE}!$"


Pewter_Text_GiveDmax2::
  .string "{COLOR BLUE}Ah, I'm glad I was able to\n"
  .string "find you.\p"
  .string "Normally, I'd be here to send a gift\n"
  .string "from your mother, but it appears\l"
  .string "she doesn't love you in this game.\p"
  .string "Anyway...$"


Pewter_Text_GiveDmax3::
  .string "{COLOR BLUE}The professor forgot to give you\n"
  .string "the {COLOR GREEN}Dynamax Band{COLOR BLUE}.$"


Pewter_Text_GiveDynamaxEnd::
  .string "{COLOR BLUE}It, obviously, allows you to\n"
  .string "Dynamax, although it can only be\l"
  .string "done in Raid Battles.\p"
  .string "You can find them by taking on\n"
  .string "raid dens.$"


Pewter_Text_GiveDynamaxEnd2::
  .string "{COLOR BLUE}Take these as well, these force\n"
  .string "Pokémon to respawn at Raid Dens.$"


Pewter_Text_GiveDynamaxEnd3::
  .string "{COLOR BLUE}Good luck, and take care!$"


falknercheck_Text_1::
  .string "It appears the Gym is closed...\p"
  .string "It could be wise to pay the museum\n"
  .string "a visit.$"


falkner_Text_1::
  .string "Hmm... There doesn't seem to be\n"
  .string "any information on Mega Stones...$"


falkner_Text_2::
  .string "Oh hi there! I'm {COLOR GREEN}Falkner{COLOR BLUE}, a Gym\n"
  .string "Leader from Johto.\p"
  .string "I'm travelling in Kanto looking for\n"
  .string "information on Mega Evolution,\l"
  .string "but have found nothing so far.$"


falkner_Text_3::
  .string "...A battle is what you're looking\n"
  .string "for?\p"
  .string "I guess I could spare the time.\p"
  .string "I'll demonstrate the power of the\n"
  .string "elegant bird Pokémon!$"


falkner_Text_Defeat::
  .string "Mmm... I have much to learn even\n"
  .string "before attaining the Mega Stones...$"


falkner_Text_4::
  .string "Thank you for a wonderful battle.\p"
  .string "...{COLOR GREEN}{PLAYER}{COLOR BLUE}, is it? I hope we meet again.\p"
  .string "I don't have a badge to give\n"
  .string "unfortunately, but you can have this.$"


falkner_Text_6::
  .string "Until next time, {COLOR GREEN}{PLAYER}.$"


checkbadge1_Text_1::
  .string "Don't even think about leaving until\n"
  .string "you beat {COLOR GREEN}Brock, {COLOR BLUE}you bumbo!$"


brock_Text_EncounterText::
  .string "So, you're here. I'm {COLOR GREEN}Brock.\n"
  .string "{COLOR BLUE}I'm {COLOR GREEN}Pewter's {COLOR BLUE}Gym Leader.\p"
  .string "My rock-hard willpower is evident\n"
  .string "even in my Pokémon.\p"
  .string "My Pokémon are all rock hard, and\n"
  .string "have true-grit determination.\p"
  .string "That's right - my Pokémon are all\n"
  .string "the rock type!\p"
  .string "Fuhaha! You're going to challenge\n"
  .string "me knowing that you'll lose?\p"
  .string "That's the trainer's honor that\n"
  .string "compels you to challenge me.\p"
  .string "Fine, then!\n"
  .string "Show me your best!$"


brock_Text_DefeatText::
  .string "I took you for granted, and so\n"
  .string "I lost.\p"
  .string "As proof of your victory, I confer\n"
  .string "on you this...the official Pokémon\l"
  .string "League Boulder Badge.\p"
  .string "{PLAYER} received the Boulder Badge\n"
  .string "from Brock!\p"
  .string "The badge enables the use of the\n"
  .string "move Flash outside of battle.\p"
  .string "Of course, you must have the HM in\n"
  .string "your bag along with a Pokémon that\l"
  .string "is able to learn it.$"


brock_Text_AfterBattle::
  .string "There are all kinds of trainers in\n"
  .string "this huge world of ours.\p"
  .string "You appear to be very gifted as a\n"
  .string "Pokémon trainer.\p"
  .string "So let me make a suggestion.\p"
  .string "Go to the gym in {COLOR GREEN}Cerulean{COLOR BLUE} and test\n"
  .string "your abilities.$"


brock_Text_Givetm::
  .string "Wait!\n"
  .string "Take this with you.$"


brock_Text_TMInfomsg::
  .string "A TM, Technical Machine, contains a\n"
  .string "technique for Pokémon.\p"
  .string "Using a TM teaches the move it\n"
  .string "contains to a Pokémon.\p"
  .string "A TM is good for multiple uses.\p"
  .string "So, don't hesitate to use them on\n"
  .string "your Pokémon.\p"
  .string "Anyways...\n"
  .string "TM39 contains Rock Tomb.\p"
  .string "It hurls boulders at the foe and\n"
  .string "lowers its Speed.$"


brock_Text_Helloagain::
  .string "Well, if it isn't my favorite chal-\n"
  .string "lenger from {COLOR GREEN}Pallet Town{COLOR BLUE}.\p"
  .string "I'd love to see how much stronger\n"
  .string "you've gotten.\p"
  .string "Perhaps I might impress you a little\n"
  .string "too!\p"
  .string "What do you say?$"


brock_Text_Comeback::
  .string "Hm... that's disappointing.$"


brock_Text_Battle::
  .string "I knew it.\p"
  .string "Here's to a fair fight!$"


brock_Text_Seconddefeat::
  .string "Ah, you crushed me again!\p"
  .string "But... I'm not at all surprised.$"


brock_Text_Won2text::
  .string "You've grown far greater than I\n"
  .string "could've possibly imagined.\p"
  .string "I've heard the news of a hero stop-\n"
  .string "ping Team Rocket...\p"
  .string "I was immediately reminded of you.\p"
  .string "I hope these gifts can further aid\n"
  .string "you on your journey.$"


brock_Text_Info::
  .string "Stone Edge is far stronger than Rock\n"
  .string "Slide, at the cost of less accuracy.\p"
  .string "{COLOR GREEN}Aerodactyl{COLOR BLUE} turns from a speedy ass-\n"
  .string "assin into an absolute menace with\l"
  .string "its Mega Form.\p"
  .string "You'd be wise to use him.$"


badtantrum_Text_1::
  .string "The secrets of space...\n"
  .string "The mysteries of earth...\p"
  .string "There are so many things about\n"
  .string "which we know so little.\p"
  .string "But that should spur us to study\n"
  .string "harder, not throw tantrums.\p"
  .string "Well, how about Bad Tantrum?\n"
  .string "Should I teach that to a Pokémon?$"


badtantrum_Text_2::
  .string "It'll cost \$3000 though.$"


badtantrum_Text_3::
  .string "Which Pokémon should I teach\n"
  .string "Bad Tantrum to?$"


badtantrum_Text_4::
  .string "Sometimes, Pokémon need to\n"
  .string "vent their feelings too.$"


badtantrum_Text_No::
  .string "Well, come back whenever.$"


badtantrum_Text_Wait::
  .string "...$"


badtantrum_Text_Poor::
  .string "...You don't have enough money.$"


RandomEgg2_Text_4::
  .string "I hope you took good care of\n"
  .string "the egg!$"


Pewter_Text_TalkAboutLevelCap::
  .string "This game's difficulty can seem\n"
  .string "unfair to casual players.\p"
  .string "Feel free to check out other ROM\n"
  .string "hacks that utilize an updated\l"
  .string "engine like Unbound, Dreams, GS\l"
  .string "Chronicles, Inflamed Red, or\l"
  .string "Inclement Emerald!$"


Pewter_Text_WantCarePackage::
  .string "Oh, hello there brave trainer!\p"
  .string "Would you be interested in a\n"
  .string "care package?$"


Pewter_Text_SayNoMore::
  .string "Say no more, friend!$"


Pewter_Text_TakeCare::
  .string "Take care.$"


Pewter_Text_AhThatsOkay::
  .string "Ah, okay.\n"
  .string "You don't want free handouts.\p"
  .string "Come see me if you change your\n"
  .string "mind.$"


Pewter_Text_PostBrockCarePackage::
  .string "As usual, would you like a\n"
  .string "care package?$"


Pewter_Text_RandomizerInfo::
  .string "I'm playing on randomizer, and I was\n"
  .string "stoked to see my {COLOR GREEN}Huge Power{COLOR RED} on my\l"
  .string "{COLOR GREEN}Slaking!{COLOR RED}\p"
  .string "But, the next day it turned into {COLOR GREEN}Slow\n"
  .string "Start.\p"
  .string "{COLOR RED}Turns out, the randomizer seed changes\n"
  .string "depending on the day of the week.\p"
  .string "So I gotta wait until next week for\n"
  .string "my broken{COLOR GREEN} Slaking{COLOR RED} to come back.$"


Gender_Text_SuccesfullySwapped ::
  .string "Succesfully swapped!$"


DoYouWantGenderSwap_Text::
  .string "{COLOR RED}I can swap the gender of a\n"
  .string "{COLOR GREEN}Snorunt, Ralts, Kirlia, Salandit,\l"
  .string "Burmy, Combee, Espurr,\l"
  .string "Basculin, or Lechonk.{COLOR RED}\p"
  .string "This can be necessary as they\n"
  .string "need specific genders for their\l"
  .string "evolutions.\p"
  .string "Interested?$"


GenderSwapperCantDo_Text::
  .string "{COLOR RED}That one I can't do.\n"
  .string "Sorry.$"


Gender_Text_DoYouWantTo::
  .string "{COLOR RED}Do you want to swap {COLOR GREEN}{STR_VAR_1}{COLOR RED}\n"
  .string "to a {STR_VAR_2}?$"


BrockCarePackage_Text::
  .string "Also, as part of the care packages\n"
  .string "cheat, you can have these.$"


Viridian_Text_Nidoking1::
  .string "{COLOR GREEN}Nidoking: {COLOR BLUE} Raaagh!$"


Viridian_Text_NidokingTrainer1::
  .string "{COLOR GREEN}Nidoking, {COLOR BLUE} sit!$"


Viridian_Text_NidokingParent1::
  .string "Kids nowadays are cracked!\p"
  .string "Back in my day, you'd be king of\n"
  .string "the playground if you had even\l"
  .string "a {COLOR GREEN}Nidorino{COLOR BLUE} at my son's age.\p"
  .string "My kid's running around with a\n"
  .string "{COLOR GREEN}Sheer Force Nidoking!\p"
  .string "{COLOR BLUE}Wahahah!$"


Pewter_Text_MeteoriteChanger ::
  .string "{COLOR BLACK}...Your {COLOR GREEN}Deoxys{COLOR BLACK} is reacting to this\n"
  .string "meteor!\p"
  .string "It seems like it wants to change\n"
  .string "form...$"


Pewter_Text_NotDeoxys::
  .string "{COLOR BLACK}That's not {COLOR GREEN}Deoxys...$"


Celadon_Text_DeoxysChange_Down::
  .string "...{COLOR GREEN}Deoxys{COLOR BLACK} form change complete!$"


DeoxysNormal_Text::
  .string "Default$"


DeoxysAttack_Text::
  .string "Attack$"


DeoxysDefense_Text::
  .string "Defense$"


DeoxysSpeed_Text::
  .string "Speed$"


WhichDeoxysForm_Text::
  .string "Which form should {COLOR GREEN}Deoxys{COLOR BLACK} change to?$"


Pewter_Text_Meteorite::
  .string "{COLOR BLACK}A meteorite that fell on Mt. Moon.\n"
  .string "It is thought to be a Moon Stone.$"


Giving_Text_DotDotDot::
  .string "...$"


Pewter_Text_SameForm::
  .string "{COLOR BLACK}...That's the same {COLOR GREEN}Deoxys{COLOR BLACK} form.$"


