PkmnTower_Text_Gengar::
  .string "Garr!$"


PkmnTower_Text_Gatekeeper::
  .string "Hello worthy challenger.\n"
  .string "Above are some trials that only the\l"
  .string "most talented players could\l"
  .string "complete.\p"
  .string "There may be a fine reward at the end.\n"
  .string "Or perhaps not.\p"
  .string "Do you wish to attempt this?$"


PkmnTower_Text_Gatekeeper2::
  .string "Very well challenger.\n"
  .string "Follow me.$"


PkmnTower_Text_GateKeeperReject::
  .string "Alright then.$"


PkmnTower_Text_GateKeeperRules::
  .string "{COLOR BLUE}Your Start menu and other functions\n"
  .string "have been disabled. So, you won't\l"
  .string "be able to heal.\p"
  .string "There are {COLOR GREEN}Gengars{COLOR BLUE} guarding this\n"
  .string "area that will send you back to the\l"
  .string "entrance if you get caught by them.\p"
  .string "And...other possible foes...\p"
  .string "I'll be here if you want me to\n"
  .string "escort you out.\p"
  .string "Best of luck.$"


PkmnTower_Text_AceTrainer1_1::
  .string "{COLOR BLUE}It seems you've gotten past the fear-\n"
  .string "some obstacles...\p"
  .string "I've been tasked to guard this\n"
  .string "area, and I intend to do it well.\p"
  .string "So, trainer, are you ready to\n"
  .string "battle?$"


PkmnTower_Text_AceTrainer1_2::
  .string "{COLOR BLUE}Let us begin.$"


PkmnTower_Text_AceTrainer1_3::
  .string "Hmm... Well played.$"


PkmnTower_Text_AceTrainer1_4::
  .string "{COLOR BLUE}You are extremely powerful,\n"
  .string "challenger.\p"
  .string "I will need to return\n"
  .string "to my training...\p"
  .string "Before I leave, as a courtesy, I can\n"
  .string "heal two of your Pokémon.\p"
  .string "Would that interest you?$"


PkmnTower_Text_AceTrainer1_5::
  .string "{COLOR BLUE}Huh, how brave of you.$"


PkmnTower_Text_AceTrainer1_6::
  .string "{COLOR BLUE}Well then, best of luck on\n"
  .string "the rest of your trial.$"


PkmnTower_Text_AceTrainer1_4_2::
  .string "{COLOR BLUE}Your {COLOR GREEN}{STR_VAR_1}{COLOR BLUE} has been healed.$"


PkmnTower_Text_AceTrainer2_4_2 ::
  .string "{COLOR RED}Your {COLOR GREEN}{STR_VAR_1}{COLOR RED} has been healed.$"


PkmnTower_Text_AceTrainer1_4_3::
  .string "{COLOR BLUE}Would you like another Pokémon to be\n"
  .string "healed?$"


PkmnTower_Text_AceTrainer2_1::
  .string "{COLOR RED}I don't like wasting time.\p"
  .string "You know the deal.\n"
  .string "Are you ready to fight?$"


PkmnTower_Text_AceTrainer2_2::
  .string "{COLOR RED}Very well, let's have at it.$"


PkmnTower_Text_AceTrainer2_3::
  .string "Mm... perhaps I was overconfident.$"


PkmnTower_Text_AceTrainer2_4::
  .string "{COLOR RED}Well, like the trainer who preceded\n"
  .string "me, I can heal 2 of your Pokémon.\p"
  .string "Are you in need of this service?$"


PkmnTower_Text_AceTrainer2_4_3::
  .string "{COLOR RED}Another one?$"


PkmnTower_Text_AceTrainer2_5::
  .string "Hmm... strange.\n"
  .string "No one has denied this service\l"
  .string "before.$"


PkmnTower_Text_AceTrainer2_6::
  .string "Well, this is goodbye.\n"
  .string "I'm not aware of the foe we're\l"
  .string "charged with protecting, but I hope\l"
  .string "you're able to leverage its power\l"
  .string "for good.$"


PkmnTower_Text_AceTrainer3_1::
  .string "{COLOR BLUE}It is rare for someone to make it this\n"
  .string "far.\p"
  .string "Fine, will you continue onwards?$"


PkmnTower_Text_AceTrainer3_2::
  .string "{COLOR BLUE}Let's hope this was no fluke, trainer.$"


PkmnTower_Text_AceTrainer3_3::
  .string "Well, I did my best.$"


PkmnTower_Text_AceTrainer3_4::
  .string "{COLOR BLUE}It was not by chance that you've\n"
  .string "made it this far. Congratulations.\p"
  .string "There is only one more foe ahead.\p"
  .string "Would you like me to heal\n"
  .string "two Pokémon?$"


PkmnTower_Text_AceTrainer3_5::
  .string "Not a fan of handouts?\n"
  .string "Understandable.$"


PkmnTower_Text_AceTrainer3_6::
  .string "Good luck.$"


PkmnTower_Text_GateKeeperLeave::
  .string "If you leave, all the progress you've\n"
  .string "made will be reset, including trainers\l"
  .string "defeated.\p"
  .string "Would you still like me to\n"
  .string "escort you out?$"


PkmnTower_Text_Morty_1::
  .string "{COLOR BLUE}Ah...\p"
  .string "I definitely expected you to be the\n"
  .string "one to make it here,\l"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}.$"


PkmnTower_Text_Morty_2::
  .string "{COLOR BLUE}It's quite strange. This Pokémon\n"
  .string "seems quite harmless at first glance,\l"
  .string "some could even call it cute.\p"
  .string "However, it's capable of copying and\n"
  .string "perfecting abilities it observes.\p"
  .string "Coupled with its capabilities of\n"
  .string "inflicting fear upon massive groups\l"
  .string "of people...\p"
  .string "Put it simply, it'll wreak\n"
  .string "great havoc in the wrong hands.$"


PkmnTower_Text_Morty_3::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}, it's clear to me you only\n"
  .string "have good intentions.\p"
  .string "Please, show me your strength\n"
  .string "one last time.$"


PkmnTower_Text_Morty_4::
  .string "{COLOR BLUE}With Team Rocket taken down, we\n"
  .string "must do everything possible to uphold\l"
  .string "the current status quo...\p"
  .string "So these powerful Pokémon showing up\n"
  .string "out of the blue leaves a lot of\l"
  .string "us concerned.\p"
  .string "But, you ought to take pride of\n"
  .string "the peace you created, {COLOR GREEN}{PLAYER}.{COLOR BLUE}\p"
  .string "Please, have this.$"


PkmnTower_Text_Morty_5::
  .string "{COLOR BLUE}I'm sure many more powerful foes\n"
  .string "await you.\p"
  .string "I wish you the best.$"


PkmnTower_Text_MortyLoss::
  .string "It was the expected outcome.\n"
  .string "Thank you for the opportunity$"


