poweranklet_Text_3::
  .string "Well, now that you found me,\n"
  .string "I may as well tell you that\l"
  .string "this pond is excellent for\l"
  .string "boosting Speed.\p"
  .string "This will be of use for that.$"


poweranklet_Text_3_2::
  .string "Hey, you've found me in my\n"
  .string "hidden spot.\p"
  .string "Well, I suppose you can have\n"
  .string "these.$"


poweranklet_Text_6::
  .string "{COLOR GREEN}Koga{COLOR BLUE} trains here very often,\n"
  .string "believe it or not.$"


powerlens_Text_3::
  .string "Ah, I know why you're here!\p"
  .string "You're trying to grind Special\n"
  .string "Attack EVs!\p"
  .string "No? Well, take it anyway.$"


powerlens_Text_3_2::
  .string "Ah, I know why you're here!\p"
  .string "You're trying to grind Special\n"
  .string "Attack EVs!\p"
  .string "Oh? You're playing on {COLOR GREEN}Minimal\n"
  .string "Grinding Mode?\p"
  .string "{COLOR BLUE}Well, have these instead.$"


powerlens_Text_6::
  .string "My psychic abilities are lacking\n"
  .string "in comparison to {COLOR GREEN}Sabrina{COLOR BLUE}...$"


powerbracer_Text_3::
  .string "You're here for sick gains,\n"
  .string "aren't you?\p"
  .string "Smart kid!\p"
  .string "These will help!$"


powerbracer_Text_6::
  .string "There's no better time than now!$"


powerweight_Text_3::
  .string "If you like your Pokémon thicc,\n"
  .string "this pond is a great spot to boost\l"
  .string "their HP.\p"
  .string "This item will help too!$"


powerweight_Text_3_2::
  .string "How nice of you to meet me\n"
  .string "across this pond.\p"
  .string "Take these for giving me\n"
  .string "company.$"


powerweight_Text_6::
  .string "I'm just trying to lose weight.\p"
  .string "Eventually, even I can jump over\n"
  .string "that ledge.$"


powerband_Text_3::
  .string "Keep the laps going here...\p"
  .string "You'll gain Special Defense while\n"
  .string "you're at it...\p"
  .string "Huff huff...\p"
  .string "This helps too...$"


powerband_Text_6::
  .string "Don't interrupt my laps,\n"
  .string "please.$"


