PokeVial_Text_Teacher::
  .string "Hm... you're a trainer aren't you?\p"
  .string "... I figured as much.\p"
  .string "Perhaps you don't have much to\n"
  .string "learn from me, but I have a proposal.\p"
  .string "Pass this simple trial of mine,\n"
  .string "and I'll give you a nice little prize.\p"
  .string "Are you interested?$"


PokeVial_Text_Rules::
  .string "The rules are simple.\p"
  .string "You select 3 Pokémon from 6\n"
  .string "that I provide for you.\p"
  .string "I assure you that among these choices lie\n"
  .string "a guaranteed path to victory.\p"
  .string "The order I send out my Pokémon will\n"
  .string "stay consistent, and I will not\l"
  .string "manually switch.$"


PokeVial_Text_LetsBegin::
  .string "Okay then, let's begin!$"


PokeVialPuzzle_Text_Defeat::
  .string "My, my, you're quite the clever one!$"


PokeVial_Text_OkNextTime::
  .string "Well, I promise you, the prize\n"
  .string "that awaits you is quite useful!$"


MoveReminder_Text_OkNextTime::
  .string "Aw, well, my services are quite handy.\p"
  .string "Your loss!$"


PokeVial_Text_TryAnotherTime::
  .string "Would you like to attempt this\n"
  .string "trial another time?$"


PokeVial_Text_NicelyDone::
  .string "Nicely done trainer, it does\n"
  .string "take a while for my students to\l"
  .string "pass that!\p"
  .string "As promised, here is my prize.\p"
  .string "I hope it doesn't disappoint!$"


PokeVial_Text_ReceivedPokeVial::
  .string "{COLOR BLACK}You received a PokéVial!$"


PokeVial_Text_HowToUse::
  .string "The PokéVial is essentially a portable\n"
  .string "Pokémon Center.\p"
  .string "You can access your PokéVial by\n"
  .string "clicking on {L_BUTTON} in the overworld to\l"
  .string "bring up your Skills Menu.\p"
  .string "You can use it 6 times, but getting\n"
  .string "healed by Nurse Joy refills it.\p"
  .string "It's sure to come in handy!$"


ViewMyTeam_Text::
  .string "View Your Team$"


OpponentsTeam_Text::
  .string "View Opp. Team$"


StartBattle_Text::
  .string "Start Battle$"


HearRules_Text::
  .string "Rules$"


WhatPuzzleAction_Text::
  .string "What would you like to do?$"


Puzzle_Text_MoveReminder::
  .string "Alright, alright!\n"
  .string "A deal's a deal.\p"
  .string "Here, I've unlocked it in the Pokémon\n"
  .string "menu for you.\p"
  .string "If you'd rather get me to\n"
  .string "teach them to your Pokémon,\l"
  .string "I can do that too.$"


Puzzle_Text_LossPokeVial::
  .string "Good effort.\n"
  .string "If you need a hint...\p"
  .string "Hazards are key against {COLOR GREEN}Shedinja.\p"
  .string "{COLOR RED}Passive damage may be key, too.$"


Puzzle_Text_LossMoveReminder::
  .string "Nice try.\n"
  .string "If you need a hint...\p"
  .string "Try leading with {COLOR GREEN}Buneary.\p"
  .string "{COLOR BLUE}An essential partner to it in\n"
  .string "this fight is {COLOR GREEN}Fletchling.$"


Puzzle_Text_MoveRemember::
  .string "I'm the Pokémon Move Maniac.\p"
  .string "I know every single move that\n"
  .string "Pokémon learn growing up.\p"
  .string "If you defeat me in a Puzzle Battle,\n"
  .string "I'll provide my services for you\l"
  .string "for free.\p"
  .string "How about it?$"


Puzzle_Text_IfYourPokemonNeed::
  .string "If your Pokémon need to learn a\n"
  .string "move, come back to me.$"


Puzzle_Text_YouLoseBattle::
  .string "It's not easy, huh?$"


Puzzle2_Text_YouLoseBattle::
  .string "Well, you gotta try harder\n"
  .string "than that!$"


