terrakion_Text_12::
  .string "Gurooooohhhh!$"


rocktunnelzap_Text_1::
  .string "{COLOR GREEN}Falkner: {COLOR BLUE}Gah, it's frustrating\n"
  .string "traversing through this cave.\p"
  .string "I ought to take another stab at it\n"
  .string "next time...$"


rocktunnelzap_Text_2::
  .string "{COLOR BLUE}Oh hey!$"


rocktunnelzap_Text_2_2::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE} isn't it?\p"
  .string "I've been walking aimlessly here\n"
  .string "as a new Legendary has been spotted\l"
  .string "near here.\p"
  .string "Though, I haven't seen it myself.\p"
  .string "So...$"


rocktunnelzap_Text_3::
  .string "{COLOR BLUE}You're the champ now aren't ya!\p"
  .string "You can't possibly say no to a\n"
  .string "challenge from me!$"


rocktunnelzap_Text_Defeat::
  .string "I must soar higher...$"


rocktunnelzap_Text_4::
  .string "{COLOR BLUE}I thought some of my new Pokémon\n"
  .string "could match up well against ya, but\l"
  .string "you're the champion for a reason.\p"
  .string "Take this, for allowing me to\n"
  .string "rematch you.$"


rocktunnelzap_Text_4_2::
  .string "And perhaps you're interested in\n"
  .string "{COLOR GREEN}Shaymin Sky.\p"
  .string "{COLOR BLUE}It's quite the devilish Pokémon.\n"
  .string "Using this will transform Shaymin into\l"
  .string "it.$"


rocktunnelzap_Text_5::
  .string "{COLOR BLUE}Take care, {COLOR GREEN}{PLAYER}{COLOR BLUE}.\n"
  .string "And remember, sky's the limit.$"


Magearna_Text_Cry::
  .string "Meaaargh!$"


