giveflash_Text_Msg::
  .string "Hi! Remember me?\n"
  .string "I'm one of Prof. Oak's Aides.\p"
  .string "If your Pokédex has complete data\n"
  .string "on ten species...\p"
  .string "...\p"
  .string "Eh, you know what?\p"
  .string "I don't care, just take the HM05.$"


giveflash_Text_2::
  .string "I don't get paid enough for this.$"


giveflash_Text_1::
  .string "I totally didn't do that just because\n"
  .string "the creator was too lazy to write\l"
  .string "the Pokédex evaluation script.$"


