powerbelt_Text_3::
  .string "I'm here to learn how to shield\n"
  .string "myself from bullies...\p"
  .string "My dad said this would help.\p"
  .string "Maybe it could help you too!$"


powerbelt_Text_6::
  .string "If I make myself strong enough,\n"
  .string "even bullies wouldn't mess with me...$"


powerbelt_Text_3_Nugget::
  .string "Aaaah! Get away from me!$"


powerbelt_Text_3_Nugget_2::
  .string "Oh... sorry I thought you were\n"
  .string "one of the bullies from the biker\l"
  .string "gang.\p"
  .string "Here, I'll share this with you!$"


powerbelt_Text_3_Nugget_3::
  .string "Once I get some more grinding done\n"
  .string "no one will mess with me...$"


