secondbrendantop_Text_2::
  .string "{COLOR BLUE}Oh hey {COLOR GREEN}{PLAYER}{COLOR BLUE}!\n"
  .string "It's been a while.\p"
  .string "I've snagged two badges since we\n"
  .string "first met.\p"
  .string "...You too huh? I thought so!\p"
  .string "Let's put each other to the test.$"


secondbrendantop_Text_Defeat::
  .string "Drat, wasted yet again...$"


secondbrendantop_Text_4::
  .string "{COLOR BLUE}You're seriously just a step ahead of\n"
  .string "me. It's admirable, really.\p"
  .string "I've got another useful item for you,\n"
  .string "my friend.$"


secondbrendantop_Text_6::
  .string "{COLOR BLUE}The {COLOR GREEN}Lucky Egg{COLOR BLUE} speeds up training sig-\n"
  .string "nificantly.\p"
  .string "I hope you put it to good use.\p"
  .string "Well, it's back to training for me.\p"
  .string "Thanks for that, {COLOR GREEN}{PLAYER}{COLOR BLUE}.$"


whitney_Text_1::
  .string "{COLOR RED}For the last time, I am NOT taking\n"
  .string "anymore autographs!$"


whitney_Text_2::
  .string "{COLOR RED}Oh... that's not what you're here for?\p"
  .string "I am terribly sorry!\p"
  .string "Anyway, I'm {COLOR GREEN}Whitney{COLOR RED}, the world ren-\n"
  .string "owned Miltank user. Perhaps you've\l"
  .string "heard of me?$"


whitney_Text_3::
  .string "{COLOR RED}If an intense battle is what you\n"
  .string "want, then that's what you're going\l"
  .string "to get!$"


whitney_Text_4::
  .string "{COLOR RED}Well, fine then...$"


whitney_Text_5::
  .string "{COLOR RED}I hope you don't let my cuteness lull\n"
  .string "you. You'll definitely regret it!$"


whitney_Text_Defeat::
  .string "Ah... woe is me...$"


whitney_Text_6::
  .string "In my younger days, I wouldn't take\n"
  .string "a loss like that very well.\p"
  .string "But, I'm actually quite happy with\n"
  .string "myself, as it's clear you're a strong\l"
  .string "trainer.\p"
  .string "Here, have this.$"


whitney_Text_7::
  .string "{COLOR GREEN}Normal Gem{COLOR BLUE} is a single use item\n"
  .string "that boosts the attack of your first\l"
  .string "Normal move by 1.5x.\p"
  .string "Of course, it regenerates at the end\n"
  .string "of battle.$"


whitney_Text_7_2::
  .string "{COLOR GREEN}Whitney:{COLOR RED} Have this as well.$"


whitney_Text_8::
  .string "{COLOR GREEN}Eviolite{COLOR RED} boosts the defenses of Poké-\n"
  .string "mon that can still evolve.\p"
  .string "It has an added functionality where\n"
  .string "it prevents evolution too, for your\l"
  .string "convenience.\p"
  .string "It's great if you like keeping them\n"
  .string "adorable!\p"
  .string "Anyway, I need to Bounce.\n"
  .string "Too many creeps on this Route.\p"
  .string "I hope we see each other soon.$"


itemfinder_Text_3::
  .string "Hi! Remember me?\n"
  .string "I'm one of Prof. Oak's aides.\p"
  .string "He's entrusted me to give you this.$"


itemfinder_Text_4::
  .string "There are items on the ground that\n"
  .string "may be hidden from view.\p"
  .string "Use the {COLOR GREEN}Itemfinder{COLOR BLUE} to detect any\n"
  .string "hidden items close to you.\p"
  .string "The machine is a bit limited.\n"
  .string "It can't pinpoint item locations.\p"
  .string "What it does is show the direction\n"
  .string "where the item is.\p"
  .string "Use it to get your bearings, then\n"
  .string "search the suspect area by hand.$"


Guard_Text_Evtraining::
  .string "Don't you think it's tedious to EV\n"
  .string "train Pokémon?\p"
  .string "Especially if you've caught a\n"
  .string "whole bunch?\p"
  .string "In Lavender Town, there's a man\n"
  .string "who provides services for EV\l"
  .string "training.\p"
  .string "He even provides services for\n"
  .string "experience grinding as well.$"


whitney_Text_DontWannaFight::
  .string "Eek... What am I doing here...$"


