Route13_Text_Trainer5_EncounterText ::
  .string "Do you want to battle some\n"
  .string "Pokémon with us?$"


Route13_Text_Trainer5_DefeatText::
  .string "It's over already?$"


Route13_Text_Trainer5_AfterBattle ::
  .string "I don't know much about\n"
  .string "Pokémon actually.\p"
  .string "The ones I use... I picked them\n"
  .string "for their looks!$"


Route13_Text_Trainer4_EncounterText ::
  .string "Sure, we'll play with you, sweetie.$"


Route13_Text_Trainer4_DefeatText::
  .string "Oh!\n"
  .string "You little beast!$"


Route13_Text_Trainer4_AfterBattle::
  .string "I wonder which is stronger, male or\n"
  .string "female Pokémon$"


