Route16_Text_PsychicGirlSense::
  .string "I sense that you have quite a\n"
  .string "fighting prowess; always yearning for\l"
  .string "a stronger adversary.\p"
  .string "One awaits you...$"


Route16_Text_PsychicGirlRoute25::
  .string "in Route 25.$"


Route16_Text_PsychicGirlRoute11::
  .string "in Route 11.$"


Route16_Text_PsychicGirlLavender::
  .string "in Lavender Town.$"


Route16_Text_PsychicGirlDojo::
  .string "in Fighting Dojo.$"


Route16_Text_PsychicGirlSeafoam::
  .string "outside Seafoam Islands.$"


Route16_Text_PsychicGirlCinnabar::
  .string "in Cinnabar Labs.$"


Route16_Text_PsychicGirlPewter::
  .string "in Pewter City. This one is a\n"
  .string "familiar face.$"


Route16_Text_PsychicGirlCerulean::
  .string "in Cerulean City. This one is a\n"
  .string "familiar face.$"


Route16_Text_PsychicGirlVermilion::
  .string "in Vermilion City. This one is a\n"
  .string "familiar face.$"


Route16_Text_PsychicGirlSaffron::
  .string "in Saffron City. A kid here\n"
  .string "seems to be a worthy opponent.$"


Route16_Text_PsychicGirlCeladon::
  .string "in Celadon City. This one is a\n"
  .string "familiar face.$"


Route16_Text_PsychicGirlJotard::
  .string "in the Power Plant.$"


Route16_Text_PsychicGirlChampion::
  .string "in the Pokémon League. Do you have\n"
  .string "what it takes?$"


Route16_Text_PsychicGirlWorthy::
  .string "I hope this ticket expands\n"
  .string "your horizons, finding you more\l"
  .string "worthy opponents.$"


Route16_Text_PsychicGirlFly::
  .string "In the past, the HM Fly was used\n"
  .string "to traverse to known locations, but\l"
  .string "this was made obsolte with the Poké-\l"
  .string "Rider.\p"
  .string "Perhaps you may want its teaching\n"
  .string "capabilities for some use.$"


Route16_Text_PsychicGirlStrong::
  .string "You do seem to be a capable\n"
  .string "trainer. If you need help finding\l"
  .string "other powerful trainers, feel free to\l"
  .string "visit me.$"


Route16_Text_Absol1::
  .string "{COLOR BLUE}Absoooool!$"


Route16_Text_PsychicGirlReady::
  .string "Ah. No more worthy opponents\n"
  .string "await you currently in this region.\p"
  .string "Please, take this.\n"
  .string "It allows passage to the Sevii\l"
  .string "Islands.$"


Route16_Text_PsychicGirlNoMore::
  .string "Hm, it appears there are no\n"
  .string "more worthy opponents. Perhaps you\l"
  .string "can await for more to come in a\l"
  .string "future update...$"


Route16_Text_PsychicGetMortyMega::
  .string "... in Lavender Town...\n"
  .string "Not a challenger, but retrieve\l"
  .string "a Mega Stone from Morty...$"


