MagikarpGuy_Text_1::
  .string "Man: Hello there, kid!\n"
  .string "Have I got a deal just for you!\p"
  .string "I'll let you have a secret Pokémon\n"
  .string "- a {COLOR GREEN}Magikarp{COLOR BLUE} - for just \$500!\p"
  .string "So, you'll buy it, am I right?$"


MagikarpGuy_Text_Reject::
  .string "No? You say no? I'm only doing this\n"
  .string "as a favor to you!$"


MagikarpGuy_Text_MoreMoney::
  .string "You'll need more money than that!$"


MagikarpGuy_Text_Bought1::
  .string "{COLOR BLACK}{PLAYER} paid an outrageous \$500\n"
  .string "and bought the {COLOR GREEN}Magikarp...{COLOR BLUE}$"


MagikarpGuy_Text_2::
  .string "Man: Hah! My favorite kid!\p"
  .string "Couldn't get enough of {COLOR GREEN}Magikarp{COLOR BLUE},\n"
  .string "huh?\p"
  .string "You want another one for \$75000,\n"
  .string "don't you?$"


MagikarpGuy_Text_Bought2::
  .string "{COLOR BLACK}{PLAYER}, again, paid an outrageous\n"
  .string "\$75000 and bought the {COLOR GREEN}Magikarp...{COLOR BLUE}$"


MagikarpGuy_Text_AfterBought2::
  .string "Ha ha ha! What a score!\p"
  .string "Thanks for the business, ya idiot!$"


MagikarpGuy_Text_3::
  .string "Ha ha ha! My favorite kid!\p"
  .string "I scammed you out of \$75000 with\n"
  .string "that defective {COLOR GREEN}Magikarp{COLOR BLUE}!$"


MagikarpGuy_Text_4::
  .string "...That was a Shiny?!\p"
  .string "You're kidding!\p"
  .string "...Can I have it back? Please?$"


givepoweruppunch_Text_3::
  .string "It's always important to work on self-\n"
  .string "improvement!\p"
  .string "After all, there is always\n"
  .string "room to grow stronger!$"


givepoweruppunch_Text_4::
  .string "You agree, don't you?!$"


givepoweruppunch_Text_5::
  .string "That's what I like to hear champ!\p"
  .string "I'd be happy to give you this!$"


givepoweruppunch_Text_7::
  .string "Each punch makes you stronger!\n"
  .string "Keep pushing it!$"


givepoweruppunch_Text_6::
  .string "Wimp!$"


machobrace_Text_3::
  .string "Sorry, my partner can be a bit\n"
  .string "feisty.\p"
  .string "But, if you're serious about training,\n"
  .string "take this.$"


machobrace_Text_4::
  .string "{COLOR GREEN}Macho Brace {COLOR BLUE}is great for\n"
  .string "speeding up EV training.$"


machobrace_Text_4_2::
  .string "{COLOR GREEN}PP Ups {COLOR BLUE}can be great for moves\n"
  .string "with low Power Points.$"


machobrace_Text_5::
  .string "...You don't know what EV training is?\n"
  .string "Do you even Smogon bro?$"


postgiovannilevelscript_Text_1::
  .string "{COLOR BLUE}What in the world...$"


postgiovannilevelscript_Text_Suchpower::
  .string "{COLOR BLUE}Such power!\p"
  .string "He forced us out of his domain...$"


DaycareWinbattle_Text::
postgiovannilevelscript_Text_2::
  .string "{COLOR BLUE}And he broke out of my ball!\p"
  .string "Ha ha ha!\p"
  .string "Now I've seen everything!$"


postgiovannilevelscript_Text_3::
  .string "{COLOR BLUE}Perhaps my Master Ball was\n"
  .string "defective...\p"
  .string "But, more importantly,\n"
  .string "{COLOR GREEN}Mewtwo{COLOR BLUE} deemed me unworthy.\p"
  .string "And...$"


postgiovannilevelscript_Text_4::
  .string "{COLOR BLUE}It spoke to you!\p"
  .string "Perhaps he's awaiting for you to\n"
  .string "become champion?\p"
  .string "That was truly a once in a life-\n"
  .string "time experience.$"


postgiovannilevelscript_Text_5::
  .string "{COLOR BLUE}It's time I turned it around.\p"
  .string "With the strength my loyal admins\n"
  .string "and I have, we could definitely make\l"
  .string "a legitimate living.$"


postgiovannilevelscript_Text_6::
  .string "{COLOR BLUE}I don't know if my son would\n"
  .string "ever forgive me...\p"
  .string "But it's never too late to\n"
  .string "start an honest life.$"


postgiovannilevelscript_Text_6_2 ::
  .string "{COLOR GREEN}Lance: {COLOR BLUE}Giovanni, I have no\n"
  .string "idea if it's possible for you to\l"
  .string "right your wrongs, but I do believe\l"
  .string "in giving people second chances.\p"
  .string "I hope to see better things out of\n"
  .string "you.\p"
  .string "I, on behalf of the Pokémon League,\n"
  .string "will be keeping a close eye on\l"
  .string "you...$"


postgiovannilevelscript_Text_7::
  .string "{COLOR GREEN}Giovanni:{COLOR BLUE} Right, of course...\n"
  .string "You have my word.$"


postgiovannilevelscript_Text_7_2::
  .string "{COLOR BLUE}Anyway...\p"
  .string "This feels right in your hands.$"


postgiovannilevelscript_Text_8::
  .string "{COLOR GREEN}Archer, Ariana{COLOR BLUE}...\p"
  .string "I'm indebted to both of you.\p"
  .string "To new beginnings!$"


postgiovannilevelscript_Text_9::
  .string "{COLOR BLUE}Yes sir!!$"


postgiovannilevelscript_Text_10::
  .string "{COLOR BLUE}Thank you, {COLOR GREEN}{PLAYER}{COLOR BLUE}.\p"
  .string "We hope to meet you again\n"
  .string "when you're the champion!$"


postgiovannilevelscript_Text_11::
  .string "{COLOR BLUE}I deeply apologize for everything.\p"
  .string "It's an empty apology,\n"
  .string "I know.\p"
  .string "But, take care of yourself,\n"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}.\p"
  .string "I've handed my position as Gym\n"
  .string "Leader to someone else already.\p"
  .string "And if you run into {COLOR GREEN}Silver{COLOR BLUE}...$"


postgiovannilevelscript_Text_12::
  .string "{COLOR BLUE}Tell him I'm sorry.\p"
  .string "Farewell.$"


postgiovannilevelscript_Text_13::
  .string "{COLOR BLUE}Well, wasn't that a strange turn\n"
  .string "of events. Perhaps it would've been\l"
  .string "wise to not let him go, but...\p"
  .string "I do get the feel he came to\n"
  .string "his senses.\p"
  .string "Perhaps I'm naive.$"


postgiovannilevelscript_Text_14::
  .string "{COLOR BLUE}But anyway, thank you for assisting\n"
  .string "me today.\p"
  .string "Here, I have this to offer you.$"


postgiovannilevelscript_Text_15::
  .string "{COLOR BLUE}And he did mention the name {COLOR GREEN}Silver{COLOR BLUE}...\p"
  .string "I've actually ran into that kid\n"
  .string "a couple of times!\p"
  .string "He was once a snotty brat, but he's\n"
  .string "turned into a formidable trainer.\p"
  .string "He does resemble his father quite\n"
  .string "a bit.\p"
  .string "Anyway, take care {COLOR GREEN}{PLAYER}{COLOR BLUE}.\n"
  .string "I'll see you in the Pokémon\l"
  .string "League soon.$"


route3carepackage_Text::
  .string "{COLOR BLUE}Whew... I better take a rest...\n"
  .string "Groan...\p"
  .string "That tunnel from {COLOR GREEN}Cerulean{COLOR BLUE} takes a\n"
  .string "lot out of you!$"


route3careaskcare_Text::
  .string "{COLOR BLUE}Ah, would you like a care\n"
  .string "package?$"


Daycare_Text_Eevee1::
  .string "{COLOR BLUE}Ah, hello there trainer.\p"
  .string "Back in my younger days, I\n"
  .string "was quite the talented trainer,\l"
  .string "travelling across all regions\l"
  .string "and taking on many formidable\l"
  .string "opponents.\p"
  .string "Now, I simply help out here at the\n"
  .string "daycare.\p"
  .string "But, I want a feeling of that rush\n"
  .string "again!\p"
  .string "I have some powerful Pokémon\n"
  .string "I'll let you borrow if you'd like\l"
  .string "to entertain me for a bit.\p"
  .string "Shall we?$"


Daycare_Text_EeveeDontFight::
  .string "{COLOR BLUE}I know I know, you kiddos\n"
  .string "always have something to do...$"


Daycare_Text_Eevee2::
  .string "{COLOR BLUE}I can already feel the thrill\n"
  .string "coming back!$"


DaycareLoseBattle_Text::
  .string "Whoo! I still got it!$"


DaycareWinBattle_Text::
  .string "Hah, well played.$"


Daycare_Text_Eevee2_Lose::
  .string "Thank you for the opportunity\n"
  .string "young one.\p"
  .string "If you show you can beat me,\n"
  .string "I have a prize ready.$"


Daycare_Text_Eevee3::
  .string "What a wonderful fight.\p"
  .string "It definitely brought back\n"
  .string "some memories, good and\l"
  .string "bad...\p"
  .string "Those Pokémon I have are\n"
  .string "Hisuian Pokémon.\p"
  .string "They are fairly rare in the\n"
  .string "Kanto Region, but I've heard\l"
  .string "reports of them on the Sevii\l"
  .string "Islands.\p"
  .string "Anywho, I'd like you to have\n"
  .string "this for defeating me.$"


Daycare_Text_ReceivedEevee::
  .string "{COLOR BLACK}You received an {COLOR GREEN}Eevee!$"


Daycare_Text_Eevee4::
  .string "Continue travelling and find-\n"
  .string "ing new unique strategies.\p"
  .string "This is how I became a\n"
  .string "stronger trainer.$"


