Route8_Text_AceTrainer1::
  .string "Hello there! I'm a strong trainer\n"
  .string "who hasn't found anyone to match\l"
  .string "my skills on this route.\p"
  .string "I'll be willing to fight you if you\n"
  .string "have a {COLOR GREEN}Mega Ring!\p"
  .string "{COLOR BLUE}Then, it'll be a fair fight.$"


Route8_Text_AceTrainerReject::
  .string "Hmm, you still don't have a {COLOR GREEN}Mega\n"
  .string "Ring{COLOR BLUE}.$"


Route8_Text_AceTrainer2::
  .string "Ah, it seems like you've got it!\n"
  .string "Well, are you ready? I'll warn ya,\l"
  .string "I can be a bit of a thorn in your side.$"


Route8_Text_AceTrainerPreBattle::
  .string "Alright, let's begin!$"


Route8_Text_AceTrainerLater::
  .string "No worries. Whenever you're ready!$"


Route8_Text_AceTrainerLoss::
  .string "Heh, perhaps my thorns weren't\n"
  .string "sharp enough!$"


Route8_Text_AceTrainer3::
  .string "That was fun! Please, have my sig-\n"
  .string "nature item.$"


Route8_Text_AceTrainer4::
  .string "If your Pokémon holds that item,\n"
  .string "they'll be able to inflict minor\l"
  .string "chip damage to the enemy when they\l"
  .string "make contact.\p"
  .string "Have this too!$"


Route8_Text_AceTrainer5::
  .string "{COLOR GREEN}Mega Centiskorch{COLOR BLUE} gains the ability\n"
  .string "{COLOR GREEN}Mountaineer, {COLOR BLUE}which gives it an immunity\l"
  .string "to Rock, one of its biggest weak-\l"
  .string "nesses!\p"
  .string "Pretty neat right?$"


