sharpedonite_Text_1::
  .string "I found this stone one day\n"
  .string "fishing, although I'm not sure what\l"
  .string "it does.\p"
  .string "Perhaps if you show me the right\n"
  .string "Pokémon, it might cause this stone\l"
  .string "to react.$"


sharpedonite_Text_2::
  .string "Hm...\p"
  .string "I don't think this is it...$"


sharpedonite_Text_3::
  .string "I hope your {COLOR GREEN}Sharpedo{COLOR BLUE} is well!$"


sharpedonite_Text_4::
  .string "{STR_VAR_1}...$"


sharpedonite_Text_5::
  .string "Hm...\p"
  .string "Oh?$"


sharpedonite_Text_6::
  .string "{COLOR BLUE}W-wait! It looks like this\n"
  .string "stone is reacting to your {COLOR GREEN}Sharpedo!$"


sharpedonite_Text_7::
  .string "{COLOR BLUE}Woah! Incredible!\n"
  .string "I've never seen a {COLOR GREEN}Mega Sharpedo\l"
  .string "{COLOR BLUE}in person before.\p"
  .string "Here, please take it!\n"
  .string "It's better off in your hands.$"


snorlaxencounter_Text_Pokeflute::
  .string "Want to use the Poké Flute?$"


snorlaxencounter_Text_ComfySlumber::
  .string "A Pokémon is sprawled out in\n"
  .string "a deep and comfortable slumber.$"


snorlaxencounter_Text_playflute::
  .string "{PLAYER} played the Poké Flute.$"


snorlaxencounter_Text_Wokeup::
  .string "Snorlax woke up!\p"
  .string "It attacked in a grumpy rage!$"


snorlaxencounter_Text_CalmedDown::
  .string "Snorlax calmed down.\n"
  .string "It gave a huge yawn...\l"
  .string "And returned to the mountains.$"


Route12Trainer1_Text_EncounterText ::
  .string "There are optimal strategies in\n"
  .string "rainy weather.$"


Route12Trainer1_Text_DefeatText::
  .string "Hmm, weather-centric strategies\n"
  .string "still have weaknesses.$"


Route12Trainer1_Text_AfterBattle ::
  .string "Some Pokémon receive benefits\n"
  .string "under different weathers$"


