bugsy_Text_1::
  .string "Just going to conveniently sit\n"
  .string "here in weather that benefits\l"
  .string "my team until some random\l"
  .string "trainer decides to challenge me...$"


bugsy_Text_2::
  .string "Oh, didn't see you there. I hope you\n"
  .string "can disregard what I just said...\p"
  .string "The name's {COLOR GREEN}Bugsy.{COLOR BLUE}\p"
  .string "...Oh? You've met my colleague\n"
  .string "{COLOR GREEN}Falkner{COLOR BLUE} too?\p"
  .string "Yeah, the Johto gym leaders decided\n"
  .string "to pay Kanto a visit, as there have\l"
  .string "been talks of a lot of new cutting-\l"
  .string "edge technology being researched here.$"


bugsy_Text_3::
  .string "Well, since you're here, I'm assuming\n"
  .string "you want a battle?$"


bugsy_Text_4::
  .string "Suit yourself. I'll be here in case\n"
  .string "you change your mind.$"


bugsy_Text_5::
  .string "Don't consider me weak just because I\n"
  .string "use Bug types, I'll show you how\l"
  .string "fearsome they can be!$"


bugsy_Text_Defeat::
  .string "Gah...Now I'm not just single, I'm a\n"
  .string "fricken loser too!$"


bugsy_Text_6::
  .string "Frankly, I'm a bit disappointed in\n"
  .string "myself.\p"
  .string "I've been feeling lonely, so my\n"
  .string "mood's down.\p"
  .string "...Hey! Don't look at me like that!\p"
  .string "Well, I'll give you my signature TM,\n"
  .string "perhaps that'll give you a higher op-\l"
  .string "inion of me.$"


bugsy_Text_7::
  .string "Maybe you need to bail, so rather\n"
  .string "than just switching you can pop a U-\l"
  .string "turn.\p"
  .string "It's great for keeping momentum too!\p"
  .string "I'm feeling generous today, so have\n"
  .string "these extra freebies too.$"


bugsy_Text_8::
  .string "Anywho, it's nice meeting you, but I\n"
  .string "can't handle more of this\l"
  .string "romantic scenery.\p"
  .string "I'll be taking my leave.$"


nuggetbridge_Text_1::
  .string "Congratulations! You beat our\n"
  .string "five contest trainers!$"


nuggetbridge_Text_2::
  .string "By the way, how would you like to\n"
  .string "join Team Rocket?\p"
  .string "We're a group of professional\n"
  .string "criminals specializing in Pokemon!\p"
  .string "Want to join?\p"
  .string "Are you sure?\p"
  .string "Come on, join us!\p"
  .string "I'm telling you to join!\p"
  .string "...Okay, you need convincing!\p"
  .string "I'll make you an offer you can't\n"
  .string "refuse!$"


nuggetbridge_Text_3::
  .string "Arrgh!\n"
  .string "You are good!$"


nuggetbridge_Text_4::
  .string "Fine, here's your Nugget.$"


nuggetbridge_Text_5::
  .string "With your ability, you'd become\n"
  .string "a top leader in Team Rocket.\p"
  .string "Come on, think of the opportunity!\n"
  .string "Don't let this chance go to waste.$"


nuggetbridge_Text_6::
  .string "{COLOR BLACK}There is quite the loot sitting\n"
  .string "around on the floor...\p"
  .string "Would you like to pick them up?$"


