garypree4top_Text_GaryMsg1::
  .string "{COLOR GREEN}{RIVAL}{COLOR BLUE}: What? {COLOR GREEN}{PLAYER}{COLOR BLUE}!\n"
  .string "What a surprise to see you here!\p"
  .string "So you're going to the Pokémon\n"
  .string "League?\p"
  .string "You collected all the Badges, too?\n"
  .string "That's cool!\p"
  .string "Then I'll whip you, {COLOR GREEN}{PLAYER}{COLOR BLUE}, as a\n"
  .string "warm-up for the Pokémon League!\p"
  .string "Come on!$"


garypree4top_Text_GaryLossMsg::
  .string "That loosened me up.\n"
  .string "I'm ready for the Pokémon League!\p"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}, you need more practice.\p"
  .string "But hey, you know that!\n"
  .string "I'm out of here. Smell ya!$"


garypree4top_Text_MsgJustCareless::
  .string "What!?\p"
  .string "I was just careless, you$"


