Saffron_Text_Nerd::
  .string "Hi, I can swap to a Pokémon's\n"
  .string "hidden ability and vice versa.\p"
  .string "I'll need a {COLOR GREEN}Bottle Cap{COLOR BLUE} though.\p"
  .string "How about it?$"


Saffron_Text_NerdGiveItem::
  .string "{COLOR BLACK}{PLAYER} handed over a Bottle Cap.{COLOR BLUE}$"


Saffron_Text_NerdAfter::
  .string "Thank you!\p"
  .string "Abilities have been swapped.$"


Saffron_Text_NerdReject::
  .string "Uh, you don't have a {COLOR GREEN}Bottle Cap{COLOR BLUE}.$"


Saffron_Text_Nerd2::
  .string "I can change a Pokémon's ability.\p"
  .string "You in?$"


Saffron_Text_Nerd2_Hidden::
  .string "That Pokémon has its Hidden\n"
  .string "Ability. You'll have to talk to\l"
  .string "my other friend here to get that\l"
  .string "swapped.$"


SaffronNerd2_Text_NoDiff::
  .string "...That Pokémon doesn't have an\n"
  .string "ability to swap to.$"


SaffronNerd_Text_NoHidden::
  .string "...That Pokémon doesn't have a\n"
  .string "Hidden Ability.$"


RandomEgg_Text_1::
  .string "Hi, I hand out Starter eggs!\p"
  .string "I'm also a shard collector.\p"
  .string "Give me a Red, Blue, or Green\n"
  .string "Shard, and I'll give a random egg\l"
  .string "corresponding to that type.$"


RandomEgg_Text_2::
  .string "Ah! You have a Shard!\p"
  .string "Would you like to exchange it\n"
  .string "for an egg?$"


RandomEgg_Text_GiveRedMsg::
  .string "A Red Shard!\p"
  .string "I can give a Fire starter for that!\p"
  .string "Sound good?$"


RandomEgg_Text_GiveBlueMsg::
  .string "A Blue Shard!\p"
  .string "I can give a Water starter for that!\p"
  .string "Sound good?$"


RandomEgg_Text_GiveGreenMsg::
  .string "A Green Shard!\p"
  .string "I can give a Grass starter for that!\p"
  .string "Sound good?$"


RandomEgg_Text_AwOkayThen::
  .string "Aw, okay then.$"


RandomEgg_Text_NoRoom::
  .string "You have no room for this.\p"
  .string "Come back when you do!$"


RandomEgg_Text_GiveShard::
  .string "{COLOR BLACK}{PLAYER} handed over the Shard.{COLOR BLUE}$"


RandomEgg_Text_ReceivedEgg::
  .string "{COLOR BLACK}{PLAYER} received an Egg!{COLOR BLUE}$"


RandomEgg_Text_ThankYou::
  .string "{COLOR BLUE}Thank you!\p"
  .string "Here it is.$"


RandomEgg_Text_WhichShard ::
  .string "Which Shard are you exchanging?$"


RandomEgg_Text_YouDontHave::
  .string "Erm.\p"
  .string "You don't have that Shard.$"


RandomEgg_Text_Red ::
  .string "{COLOR RED}Red Shard$"


RandomEgg_Text_Blue ::
  .string "{COLOR BLUE}Blue Shard$"


RandomEgg_Text_LearnMore::
  .string "Learn More$"


RandomEgg_Text_LearnMoreMsg ::
  .string "The pool for Fire Starters are\n"
  .string "Cyndaquil, Chimchar, Tepig,\l"
  .string "Fennekin, Litten, and Scorbunny.\p"
  .string "The pool for Grass Starters are\n"
  .string "Chikorita, Turtwig, Chespin, \l"
  .string "Rowlet, and Grookey.\p"
  .string "The pool for Water starters are\n"
  .string "Totodile, Piplup, Oshawott,\l"
  .string "Popplio, and Sobble.$"


RandomEgg_Text_Green ::
  .string "{COLOR GREEN}Green Shard$"


DumbassKid_Text_1::
  .string "i Herd U Liek Mudkipz$"


DumbassKid_Text_Good::
  .string "Mud! Kip!$"


DumbassKid_Text_Battle::
  .string "no??? NO???????\p"
  .string "I HERD U LIEK MUDKIPZ????$"


DumbassKid_Text_Battle2 ::
  .string "YOU...\p"
  .string "YOU WILL PAY!!!!!!!!!$"


DumbassKidLoss_Text::
  .string "mud... kip...\p"
  .string ":($"


DumbassKid_Text_EQInfo::
  .string "eq is an extremely pog move\n"
  .string "on swampy...$"


DumbassKid_Text_PostLoss::
  .string "Well...\p"
  .string "Mudkips are still cool...\p"
  .string "I will share sum love XD$"


DumbassKid_Text_GetMudkip::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Mudkip{COLOR BLACK}!$"


DumbassKid_Text_LastMsg::
  .string "THIS GAME WON'T LET ME OVERLEVEL\n"
  .string "WHAT THE FRIIIIIIIIIIICK!$"


DumbassKid_Text_Rematch::
  .string "ohohoh... you have z-power-ring now!\n"
  .string "OwO...\p"
  .string "u seem stwonger...\n"
  .string "can we battle again??$"


DumbassKid_Text_GetHim::
  .string "let's freaking go...\n"
  .string "let's get him swampy!!!!$"


DumbassKid_Text_Rematch2::
  .string "aw man... i'm sadge again...\p"
  .string "but i will admit...\n"
  .string "u are seriously too good!\p"
  .string "maybe you are interested in another\n"
  .string "cool pokemons.\p"
  .string "{COLOR GREEN}cosmog...{COLOR BLUE}\n"
  .string "it can evolve into either {COLOR GREEN}solgaleo{COLOR BLUE}\l"
  .string "or {COLOR GREEN}lunala!{COLOR BLUE}\p"
  .string "it's kinda poggers.\n"
  .string "here u go.$"


DumbassKid_Text_ReceiveCosmog::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Cosmog!$"


DumbassKid_Text_Stronger::
  .string "{COLOR BLUE}when i grow older i want to\n"
  .string "become stwonger than u...$"


DumbassKid_Text_Gren::
  .string "{COLOR BLUE}how i get pretransformed ash\n"
  .string "greninja?\p"
  .string "cheating obviously!\n"
  .string "lolz.$"


DumbassKid_Text_SisterBully::
  .string "{COLOR BLUE}my sister is big meanie...\n"
  .string "she bully me with riwwaboom...\p"
  .string "most op pokémon vs swampy...$"


DumbassKid_Text_YouGotSwamp::
  .string "oh my GOSH!\n"
  .string "did u get urself a swampert???\p"
  .string "...$"


DumbassKid_Text_ThatsPog::
  .string "that's FREAKING POG!!!!!!\n"
  .string "you have good taste xD$"


DumbassKid_Text_HaveThis::
  .string "pls, take this. friend.$"


DumbassKid_Text_LastMsg_2::
  .string "i heckin luv mudkipz...$"


SilphCo_Text_TeamAlert1::
  .string "{COLOR BLACK}Just a small warning from\n"
  .string "the creator himself...\p"
  .string "There's an upcoming tag battle,\n"
  .string "so I've healed your team in\l"
  .string "preparation.$"


Saffron_Text_ManyTutors1 ::
  .string "Hiya, I got a whole slew of\n"
  .string "useful moves!\p"
  .string "They cost \$7500.$"


Saffron_Text_ManyTutors2 ::
  .string "Hm, that's not enough money.$"


Saffron_Text_ManyTutors3 ::
  .string "Nice doing business with ya!$"


Saffron_Text_ManyTutors4::
  .string "...$"


Saffron_Text_ManyTutors5::
  .string "Well, alright then.$"


Saffron_Text_ManyTutors6::
  .string "Which move would you like?$"


Saffron_Text_ManyTutors7::
  .string "Who wants it?$"


Saffron_Text_ManyTutors8::
  .string "Need more options eh?$"


HydroPump_Text::
  .string "Hydro Pump$"


DrillRun_Text::
  .string "Drill Run$"


BlazeKick_Text::
  .string "Blaze Kick$"


PSplit_Text::
  .string "Pain Split$"


ZenHeadbutt_Text::
  .string "Zen Headbutt$"


WeatherBall_Text::
  .string "Weather Ball$"


AirSlash_Text::
  .string "Air Slash$"


Hex_Text::
  .string "Hex$"


MysticalFire_Text::
  .string "Mystic Fire$"


SeedBomb_Text::
  .string "Seed Bomb$"


LeafBlade_Text::
  .string "Leaf Blade$"


KnockOff_Text::
  .string "Knock Off$"


ViewMore_Text::
  .string "View More$"


Back _Text::
  .string "Back$"


liquidation_Text_1::
  .string "Need to liquidate some money?\p"
  .string "Do it easily by teaching your Poké-\n"
  .string "mon Liquidation!\p"
  .string "How about it?$"


liquidation_Text_2::
  .string "It's going to cost ya \$7500 though.$"


liquidation_Text_3::
  .string "Which Pokémon should I teach\n"
  .string "Liquidation to?$"


liquidation_Text_4::
  .string "Water em down...$"


liquidation_Text_No::
  .string "Aw, well. I hope to see you again.$"


liquidation_Text_Wait::
  .string "...$"


liquidation_Text_Poor::
  .string "...You don't have enough money.$"


EVSubtracter_Text_Msg::
  .string "Hi, I can subtract EVs from a\n"
  .string "Pokémon. You in?$"


EVSubtracter_Text_1::
  .string "Your {STR_VAR_1}...\n"
  .string "Which stat should I subtract?$"


EVSubtracter_Text_2::
  .string "Feel free to come back if you\n"
  .string "need my assistance.$"


EVSubtracter_Text_4::
  .string "Shall I do another Pokémon?$"


EVSubtracter_Text_Reduceby::
  .string "Reduce by 10, 50, 100, or 252?$"


EVSubtracter_Text_None::
  .string "The EVs in that stat are at 0.$"


EVSubtracter_Text_HP::
  .string "HP$"


EVSubtracter_Text_Attack::
  .string "Attack$"


EVSubtracter_Text_Defense::
  .string "Defense$"


EVSubtracter_Text_SpA::
  .string "Sp. Attack$"


EVSubtracter_Text_SpDef::
  .string "Sp. Def$"


EVSubtracter_Text_Speed::
  .string "Speed$"


EVSubtracter_Text_AllStats::
  .string "All Stats$"


EVSubtracter_Text_Ten::
  .string "10$"


EVSubtracter_Text_Fifty::
  .string "50$"


EVSubtracter_Text_Hundred::
  .string "100$"


EVSubtracter_Text_All::
  .string "252$"


EVSubtracter_Text_By10::
  .string "Succesfully reduced by 10!$"


EVSubtracter_Text_By50::
  .string "Succesfully reduced by 50!$"


EVSubtracter_Text_By100::
  .string "Succesfully reduced by 100!$"


EVSubtracter_Text_ByAll::
  .string "Succesfully reduced by 252!$"


EVSubtracter_Text_DoAllDone::
  .string "Sucessfully reset {STR_VAR_1}'s\n"
  .string "EVs!$"


EVSubtracter_Text_DoAll ::
  .string "Shall I reduce all of\n"
  .string "{STR_VAR_1}'s EVs?$"


EVSubtracter_Text_Currently::
  .string "It currently has {STR_VAR_2} EVs in that\n"
  .string "stat.$"


EVSubtracter_Text_NowHas::
  .string "It now has {STR_VAR_2} EVs in that\n"
  .string "stat.$"


EvChecker_Text_Msg::
  .string "Hi, I'm a gigantic nerd.\p"
  .string "I can check your Pokémon's EVs at a\n"
  .string "glance. Interested?$"


EvChecker_Text_1::
  .string "Your {STR_VAR_1} has...$"


EvChecker_Text_2::
  .string "Well, just here to help.$"


EvChecker_Text_3::
  .string "{STR_VAR_1} HP EVs, {STR_VAR_2} Atk EVs, [BUFFER3] Def EVs...$"


EvChecker_Text_4::
  .string "Shall I check another one?$"


EvChecker_Text_5::
  .string "{STR_VAR_1} SpAtk EVs, {STR_VAR_2} SpDef EVs,\n"
  .string "[BUFFER3] Speed EVs.$"


chuck_Text_1::
  .string "{COLOR BLUE}Hello there little chump!\p"
  .string "I'm {COLOR GREEN}Chuck{COLOR BLUE}, and I've taken over\n"
  .string "as the Karate Master of this dojo!\p"
  .string "I can put you in a choke-hold in\n"
  .string "a matter of seconds if I wanted to!\p"
  .string "What?\p"
  .string "It has nothing to do with Pokémon?\p"
  .string "Haha! A challenger long ago once\n"
  .string "said the same thing!\p"
  .string "Come on, we shall do battle!$"


chuck_Text_Defeat::
  .string "Wha! I lost?!\n"
  .string "Incredible!$"


chuck_Text_6::
  .string "What a crushing defeat!\p"
  .string "It's back to 24-hour training for\n"
  .string "me!\p"
  .string "But, I'm impressed, challenger.\p"
  .string "Have this!$"


chuck_Text_8::
  .string "These could help your warriors fight\n"
  .string "better as well!$"


chuck_Text_Take::
  .string "If you'd like, you can have one of\n"
  .string "the Fighting Pokémon over here as a\l"
  .string "trophy.$"


chuck_Text_9::
  .string "Hey there!\n"
  .string "Hope the lifting's going well.$"


chuck_Text_10::
  .string "...I see you have your own {COLOR GREEN}Mega\n"
  .string "Ring{COLOR BLUE}.\p"
  .string "If you show me a Pokémon you've invested\n"
  .string "in Attack, I might just give you a\l"
  .string "{COLOR GREEN}Galladite!{COLOR BLUE}$"


chuck_Text_10_minGrinding::
  .string "...I see you have your own {COLOR GREEN}Mega\n"
  .string "Ring{COLOR BLUE}.\p"
  .string "If you show me a Pokémon with strong\n"
  .string "Attack, I might just give you a\l"
  .string "{COLOR GREEN}Galladite!{COLOR BLUE}$"


chuck_Text_11::
  .string "Your {STR_VAR_1}...$"


chuck_Text_12::
  .string "Woah, this thing's ripped!\p"
  .string "Admirable!\p"
  .string "Wahaha, here you go!$"


chuck_Text_14::
  .string "Take this one as well.$"


chuck_Text_13::
  .string "Eh... it could still hit the Gym...$"


taurospfire_Text_Received::
  .string "You received the Blaze Breed {COLOR GREEN}Tauros{COLOR BLACK}\n"
  .string "from {COLOR GREEN}Chuck{COLOR BLACK}!$"


clobbopus_Text_Msggreedy::
  .string "Better not get greedy...$"


taurospfire_Text_Uwant::
  .string "You want the Blaze Breed {COLOR GREEN}Tauros{COLOR BLACK}?$"


taurospwater_Text_Received::
  .string "You received the Aqua Breed {COLOR GREEN}Tauros{COLOR BLACK}\n"
  .string "from {COLOR GREEN}Chuck{COLOR BLACK}!$"


crabrawler_Text_Msggreedy::
  .string "Better not get greedy...$"


taurospwater_Text_Uwant::
  .string "You want the Aqua Breed {COLOR GREEN}Tauros{COLOR BLACK}?$"


sabrina_Text_EncounterText::
  .string "{COLOR RED}I had a vision of your arrival.\p"
  .string "I have had psychic powers since\n"
  .string "I was a child.\p"
  .string "It started when a spoon I\n"
  .string "carelessly tossed, bent.\p"
  .string "I dislike battling, but if you wish,\n"
  .string "I will show you my powers.\p"
  .string "I prefer fighting in the Doubles\n"
  .string "style, are you ready?$"


sabrina_Text_DefeatText::
  .string "This loss shocks me!\n"
  .string "But, a loss is a loss.\p"
  .string "I admit, I didn't work hard enough\n"
  .string "to win.\p"
  .string "Your victory has earned you the\n"
  .string "Marsh Badge.$"


sabrina_Text_Givetm::
  .string "TM116 is Trick Room.\p"
  .string "It flips dimensions to allow\n"
  .string "slower Pokémon to go first.\p"
  .string "It's quite a potent strategy\n"
  .string "in Doubles.$"


sabrina_Text_GivetmHard::
  .string "TM104 is Psyshock.\p"
  .string "It's a special move that hits\n"
  .string "the target's Defense.\p"
  .string "It's a unique move that can\n"
  .string "catch the opponent off guard.$"


sabrina_Text_Shinypokemon::
  .string "If you show me a shiny Pokémon,\n"
  .string "I'll reward you handsomely.$"


sabrina_Text_TMInfomsg::
  .string "Before you go, please,\n"
  .string "take this TM with you.$"


sabrina_Text_Helloagain::
  .string "...Perhaps you're looking for a\n"
  .string "{COLOR GREEN}Gardevoirite{COLOR RED}?$"


sabrina_Text_HelloagainHard::
  .string "...Perhaps you're looking for a\n"
  .string "{COLOR GREEN}Cameruptite{COLOR RED}?$"


sabrina_Text_Perfectpokemon::
  .string "If you show me a perfect Pokémon,\n"
  .string "I'll reward you handsomely.$"


sabrina_Text_Thepokemon::
  .string "Your {STR_VAR_1}...$"


sabrina_Text_Notquite::
  .string "It's not quite what I'm looking\n"
  .string "for...$"


sabrina_Text_Perfect::
  .string "Ah, yes.\p"
  .string "This Pokémon is clearly flawless.\p"
  .string "Here, take it.$"


sabrina_Text_Shiny::
  .string "Ah, yes.\p"
  .string "This Pokémon is clearly a Shiny.\p"
  .string "Here, take it.$"


sabrina_Text_Donemsg::
  .string "Psychic power isn't something that\n"
  .string "only a few people have.\p"
  .string "Everyone has it to some degree.\n"
  .string "They just haven't realized it yet.$"


sabrina_Text_Charmmsg::
  .string "I've carried this around for a while,\n"
  .string "but I have no idea if it actually\l"
  .string "does anything.\p"
  .string "You might like it, though.$"


silphcoteambattle_Text_1::
  .string "{COLOR RED}Looks like we found our intruder.$"


silphcoteambattle_Text_2::
  .string "{COLOR BLUE}Wait a sec...\p"
  .string "This is the punk I ran into at\n"
  .string "{COLOR GREEN}Mt. Moon!$"


silphcoteambattle_Text_3::
  .string "{COLOR RED}Wow, you lost to this loser?\p"
  .string "{COLOR BLUE}Quiet, I'm sure my {COLOR GREEN}Mightyena{COLOR BLUE} gave\n"
  .string "this punk a scare.$"


silphcoteambattle_Text_4::
  .string "{COLOR RED}Your {COLOR GREEN}Mightyena{COLOR RED} doesn't even have\n"
  .string "Intimidate.$"


silphcoteambattle_Text_5::
  .string "{COLOR BLUE}Would you SHUT UP {COLOR GREEN}Ari{COLOR BLUE}?!\p"
  .string "We've got things to deal with here.$"


silphcoteambattle_Text_6::
  .string "{COLOR RED}Fine...\p"
  .string "Sorry kid, looks like your fun ends\n"
  .string "here.$"


silphcoteambattle_Text_7::
  .string "{COLOR GREEN}???{COLOR BLUE}: Wait a moment!$"


silphcoteambattle_Text_8::
  .string "{COLOR GREEN}Brendan:{COLOR BLUE} Don't you think two against\n"
  .string "one is a little unfair?$"


silphcoteambattle_Text_9::
  .string "{COLOR BLUE}Heh, sorry I'm late to the party\n"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}.\p"
  .string "Let me give you a hand!$"


silphcoteambattle_Text_10::
  .string "{COLOR BLUE}Who the hell...?\p"
  .string "{COLOR RED}The more the merrier I guess.\p"
  .string "{COLOR BLUE}Whatever, neither of you will be\n"
  .string "reaching the boss.$"


silphcoteambattle_Text_11::
  .string "{COLOR BLUE}Damn it...\p"
  .string "I really hate them kids...\p"
  .string "{COLOR RED}I... I'm shocked...\n"
  .string "Boss won't be happy about this.$"


silphcoteambattle_Text_12::
  .string "{COLOR BLUE}Of course he won't.\n"
  .string "We ought to scram.$"


silphcoteambattle_Text_13::
  .string "{COLOR BLUE}Pray you don't meet me again,\n"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}.$"


silphcoteambattle_Text_ArianaDefeat::
  .string "I... I fought hard...\n"
  .string "But I still lost...$"


silphcoteambattle_Text_ArcherDefeatText::
  .string "Again?!\n"
  .string "This is infuriating!$"


silphcoteambattle_Text_14::
  .string "{COLOR BLUE}Whew...\p"
  .string "To be honest, I was quite scared!\p"
  .string "But, I knew they stood no chance\n"
  .string "with you on my side.\p"
  .string "You're simply incredible!$"


silphcoteambattle_Text_15::
  .string "{COLOR BLUE}Hm...$"


silphcoteambattle_Text_16::
  .string "{COLOR BLUE}Sorry looks like I have a text\n"
  .string "message on my Pokénav...\p"
  .string "...\p"
  .string "Agh! I'm sorry!\p"
  .string "I'd love to help you further, but\n"
  .string "I have something urgent to attend...\p"
  .string "Here, let me heal your Pokémon.$"


silphcoteambattle_Text_17::
  .string "{COLOR BLUE}Again, I apologize for needing to\n"
  .string "leave so abruptly...\p"
  .string "Please, take yet another parting gift.$"


silphcoteambattle_Text_18::
  .string "{COLOR BLUE}Good luck, friend.$"


megaring_Text_1::
  .string "Wait!$"


megaring_Text_2::
  .string "The President forgot to give you\n"
  .string "this.\p"
  .string "A lot of trainers have already\n"
  .string "gotten their hands on it, as you may\l"
  .string "have already noticed.\p"
  .string "But we're sure this will be of use\n"
  .string "for you.$"


megaring_Text_3::
  .string "I also thought this would be worth\n"
  .string "mentioning...\p"
  .string "Many Gym Leaders have been looking\n"
  .string "for rematches.\p"
  .string "Perhaps you ought to pay them a\n"
  .string "visit?\p"
  .string "Anyways, take care!\p"
  .string "And once again, thank you.$"


stopchuck_Text_1::
  .string "Hey!\p"
  .string "You're gonna have to fight me for\n"
  .string "those!$"


sabrina_Text_Whenever::
  .string "Whenever you're ready...$"


sabrina_Text_LetsBegin::
  .string "Let's begin!$"


IvChecker_Text_Msg::
  .string "I can check your Pokémon's IVs at a\n"
  .string "glance. Interested?$"


IvChecker_Text_3::
  .string "{STR_VAR_1} HP IVs, {STR_VAR_2} Atk IVs, [BUFFER3] Def IVs...$"


IvChecker_Text_5::
  .string "{STR_VAR_1} SpAtk IVs, {STR_VAR_2} SpDef IVs,\n"
  .string "[BUFFER3] Speed IVs.$"


IVSubtracter_Text_Msg::
  .string "Hi, I can set the IV of a\n"
  .string "specific stat to 0.\p"
  .string "This is mainly useful for getting\n"
  .string "minimum speed for Trick Room.\p"
  .string "Interested?$"


IVSubtracter_Text_HP::
  .string "Shall I reduce HP to 0 IVs?\n"
  .string "This can't be undone.$"


IVSubtracter_Text_Attack::
  .string "Shall I reduce Attack to\n"
  .string "0 IVs? This can't be undone.$"


IVSubtracter_Text_Defense::
  .string "Shall I reduce Defense to 0\n"
  .string "IVs? This can't be undone.$"


IVSubtracter_Text_SpA::
  .string "Shall I reduce SpA to 0\n"
  .string "IVs? This can't be undone.$"


IVSubtracter_Text_SpDef::
  .string "Shall I reduce SpDef to 0\n"
  .string "IVs? This can't be undone.$"


IVSubtracter_Text_Speed::
  .string "Shall I reduce Speed to 0\n"
  .string "IVs? This can't be undone.$"


IVSubtracter_Text_1::
  .string "Your {STR_VAR_1}...\n"
  .string "Which stat should I set to 0?$"


IVSetterDone _Text::
  .string "...Okay, it's done!\n"
  .string "Come back if you need more!$"


SetBalls1 _Text::
  .string "Hi, I can switch the Poké Ball\n"
  .string "of your Pokémon.\p"
  .string "Interested?$"


SetBallsMaster _Text::
  .string "Master Ball$"


SetBallsUltra_Text::
  .string "Ultra Ball$"


SetBallsGreat_Text::
  .string "Great Ball$"


SetBallsPoke_Text::
  .string "Poké Ball$"


SetBallsSafari_Text::
  .string "Safari Ball$"


SetBallsNet_Text::
  .string "Net Ball$"


SetBallsDive_Text::
  .string "Dive Ball$"


SetBallsNest_Text::
  .string "Nest Ball$"


SetBallsRepeat_Text::
  .string "Repeat Ball$"


SetBallsTimer_Text::
  .string "Timer Ball$"


SetBallsLuxury_Text::
  .string "Luxury Ball$"


SetBallsPremier_Text::
  .string "Premier Ball$"


SetBallsDusk_Text::
  .string "Dusk Ball$"


SetBallsHeal_Text::
  .string "Heal Ball$"


SetBallsQuick_Text::
  .string "Quick Ball$"


SetBallsCherish_Text::
  .string "Cherish Ball$"


SetBallsPark _Text::
  .string "Park Ball$"


SetBallsFast_Text::
  .string "Fast Ball$"


SetBallsLevel_Text::
  .string "Level Ball$"


SetBallsLure_Text::
  .string "Lure Ball$"


SetBallsHeavy_Text::
  .string "Heavy Ball$"


SetBallsLove_Text::
  .string "Love Ball$"


SetBallsFriend_Text::
  .string "Friend Ball$"


SetBallsMoon_Text::
  .string "Moon Ball$"


SetBallsSport_Text::
  .string "Hisui PokéBall$"


SetBallsBeast_Text::
  .string "Beast Ball$"


SetBallsDream_Text::
  .string "Dream Ball$"


SetBallsHisuian_Text::
  .string "Hisuian Ball$"


SetBallsExit_Text::
  .string "Exit$"


PokeBall_Text_Which::
  .string "Which Ball would you like?$"


POkeBall_Text_Done::
  .string "Aaaaand...\n"
  .string "Done! Enjoy.$"


Saffron_Text_HPChanger_1::
  .string "Hi! I can configure your Pokémon's\n"
  .string "IVs for a specific Hidden Power\l"
  .string "Type!\p"
  .string "The catch is each of its IVs\n"
  .string "must be at least 30.\p"
  .string "Are you interested?$"


Saffron_Text_HpChanger_Which::
  .string "Which Hidden Power type would\n"
  .string "you like?$"


SettingIVs_Text::
  .string "For this Hidden Power, I need\n"
  .string "to set your IVs to...\p"
  .string "{STR_VAR_1} HP IVs, {STR_VAR_2} Atk IVs, [BUFFER3] Def IVs,\n"
  .string "[BUFFER4] SpA IVs, [BUFFER5] SpD IVs, [BUFFER6] Speed IVs.$"


SettingIVs_Text_2::
  .string "Is that okay?$"


HPChanger_Text_Done::
  .string "...And all done!\n"
  .string "Enjoy!$"


SaffronHPChanger_Text_No::
  .string "Hm...\n"
  .string "I don't think this Pokémon follows\l"
  .string "the critera I requested. Sorry.$"


SaffronCake1_Text::
  .string "Hm... I need some ingredients\n"
  .string "for this cake I'm making.$"


SaffronCake2_Text::
  .string "Oh! Hello there! Would you be\n"
  .string "willing to help me with some\l"
  .string "cake ingredients?\p"
  .string "I'll need 2 {COLOR GREEN}Moomoo Milks, a Rawst Berry,\n"
  .string "{COLOR RED}and an {COLOR GREEN}Aspear Berry.$"


SaffronCake3_Text::
  .string "{COLOR RED}Ah yes! That would be a great\n"
  .string "help! Thank you so much!\p"
  .string "Please, have this!$"


SaffronCake4_Text::
  .string "{COLOR GREEN}Mega Alcremie{COLOR RED} looks like a delicious\n"
  .string "cake, but it's actually quite a bulky\l"
  .string "Pokémon too!$"


SaffronCake5_Text::
  .string "You can have this too. I needed\n"
  .string "this back when I was a musician,\l"
  .string "but those days are long gone.$"


SaffronCakeDontHave_Text::
  .string "Eh... you don't have all the ingredients...$"


SaffronCakeImprovise_Text::
  .string "Perhaps I'll just improvise with\n"
  .string "what I have...$"


SaffronStaraptor_Text::
  .string "{COLOR GREEN}Staraptor: {COLOR RED}Star star!$"


Saffron_Text_Corvknight::
  .string "{COLOR GREEN}Corviknight: {COLOR RED}Corv.$"


SaffronStaraptorTrainer_Text::
  .string "I flew here on my{COLOR GREEN} Staraptor{COLOR BLUE} when\n"
  .string "I read about Silph.\p"
  .string "It's already over?\n"
  .string "I missed the media action...$"


SaffronMudkip_Text::
  .string "Mudkip!$"


SaffronMarshtomp_Text::
  .string "Marshtomp!$"


SaffronSwampert_Text::
  .string "Swampert!$"


SaffronMimikyu_Text::
  .string "Mimikyu!$"


SaffronRillaboom_Text::
  .string "Rillaboom!$"


