SeafoamIslands_Text_1::
  .string "{COLOR BLACK}An exceedingly powerful force\n"
  .string "approaches...$"


SeafoamIslands_Text_2 ::
  .string "{COLOR BLACK}...$"


SeafoamIslands_Text_3::
  .string "{COLOR BLACK}It's a {COLOR GREEN}Keldeo{COLOR BLACK}!$"


SeafoamIslands_Text_4::
  .string "{COLOR BLACK}Do you confront it?$"


pryce_Text_1::
  .string "{COLOR BLUE}Why, hello there.\p"
  .string "The {COLOR GREEN}Seafoam Islands{COLOR BLUE} is a very\n"
  .string "nostalgic spot for me...\p"
  .string "Ah, I haven't introduced myself.\p"
  .string "I'm {COLOR GREEN}Pryce{COLOR BLUE}.\p"
  .string "I was once a fearsome Gym Leader,\n"
  .string "but age has taken its toll.\p"
  .string "However, as an elder, I have\n"
  .string "many lessons to teach.\p"
  .string "Perhaps a challenge is what you\n"
  .string "seek?$"


pryce_Text_2::
  .string "Ah, well, I shall continue training\n"
  .string "here.$"


pryce_Text_3::
  .string "Very well.\p"
  .string "Hopefully I can demonstrate my\n"
  .string "power!$"


pryce_Text_Defeat::
  .string "Impressive... It appears you've\n"
  .string "overcome many obstacles as well.$"


pryce_Text_6::
  .string "I haven't felt that young in ages.\p"
  .string "Thank you, challenger.\p"
  .string "I don't have much to give anymore,\n"
  .string "but perhaps you'd like this.$"


pryce_Text_7::
  .string "This keeps me warm during the\n"
  .string "winter, but it is a useful hold item\l"
  .string "for Pokémon as well.$"


pryce_Text_Take::
  .string "It's common knowledge that {COLOR GREEN}Articuno{COLOR BLUE}\n"
  .string "reigns in{COLOR GREEN} Seafoam Islands{COLOR BLUE}, but rumors\l"
  .string "are an additional mythical Pokémon\l"
  .string "has made its stay here.\p"
  .string "Perhaps someone capable like you\n"
  .string "would like to check it out...\p"
  .string "As for me, I'll be heading home.\p"
  .string "These old bones can't take it\n"
  .string "anymore.\p"
  .string "So long, challenger.$"


keldeo_Text_12::
  .string "Kawwooo!$"


SeafoamIslands_Text_Articuno_1::
  .string "Gyaoo!$"


Seafoam_Text_ASandhrew_1::
  .string "...$"


Seafoam_Text_ASandshrew_2::
  .string "{COLOR BLACK}This Sandshrew says it'll show\n"
  .string "you a secret path if you beat it in\l"
  .string "a race.\p"
  .string "Would you like to try?$"


SeafoamIslands_Text_Race_1::
  .string "Ready...$"


SeafoamIslands_Text_Race_2::
  .string "Go!$"


Seafoam_Text_YouLose::
  .string "It seems Sandshrew beat you.\p"
  .string "It'll escort you back to the\n"
  .string "start in case you want to try\l"
  .string "again.$"


OhNoFailedRace_Text::
  .string "It seems you've failed the race.$"


ReturnToTryAgain_Text::
  .string "Would you like to try again?$"


Seafoam_Text_YouWin::
  .string "You beat the Sandshrew!$"


KyogrePrimalOrb_Text::
  .string "{COLOR BLACK}There seems to be an item here...$"


Seafoam_Text_ASandshrew_3::
  .string "The Sandshrew wishes you good luck.$"


Seafoam_Text_Pryce1::
  .string "Ah, good to see you here,\n"
  .string "Champion. I see you made it past\l"
  .string "{COLOR GREEN}Sandshrew the Swift.{COLOR BLUE}\p"
  .string "I've revisited this area off the hunch\n"
  .string "of that {COLOR GREEN}Sandshrew.{COLOR BLUE}\p"
  .string "Another powerful legendary has found\n"
  .string "its place here, one far more\l"
  .string "powerful than Articuno and even\l"
  .string "Keldeo that are found here.\p"
  .string "How it got here, I'm not sure...\p"
  .string "But I've stood watch ensuring it does\n"
  .string "not fall in the wrong hands.\p"
  .string "If you would like to seek this Pokémon,\n"
  .string "you'll have to get through me,\l"
  .string "child.\p"
  .string "Are you ready?$"


Seafoam_Text_Pryce2::
  .string "Huh, not interested in the\n"
  .string "legendary?\p"
  .string "I'll continue standing guard, then.$"


pryce_Text_Defeat2::
  .string "Heh, another cold defeat.$"


Seafoam_Text_Pryce3::
  .string "It was an honor to fight the champion\n"
  .string "once more.\p"
  .string "Even in my old age I can stand my\n"
  .string "ground against a majority of Poké-\l"
  .string "mon trainers.\p"
  .string "Fine, the legendary here is yours.\p"
  .string "And please, take this from me.$"


Seafoam_Text_Pryce4::
  .string "{COLOR BLUE}Take care.$"


Seafoam_Text_MonsAreFrozen::
  .string "Pryce's cold demeanor froze some\n"
  .string "of your Pokémon!$"


