silphcoelevatorthatworks_Text_Floor1::
  .string "1F$"


silphcoelevatorthatworks_Text_Floor2::
  .string "2F$"


silphcoelevatorthatworks_Text_Floor3::
  .string "3F$"


silphcoelevatorthatworks_Text_Floor4::
  .string "4F$"


silphcoelevatorthatworks_Text_Floor5::
  .string "5F$"


silphcoelevatorthatworks_Text_Floor6::
  .string "6F$"


silphcoelevatorthatworks2_Text_Floor7::
  .string "7F$"


silphcoelevatorthatworks2_Text_Floor8::
  .string "8F$"


silphcoelevatorthatworks2_Text_Floor9::
  .string "9F$"


silphcoelevatorthatworks2_Text_Floor10::
  .string "10F$"


silphcoelevatorthatworks2_Text_Floor11::
  .string "11F$"


twave_Text_3::
  .string "Eeek!\n"
  .string "No! Stop! Help!\p"
  .string "Oh, you're not with Team Rocket.\n"
  .string "I'm sorry, I thought...\p"
  .string "Will you forgive me if I teach\n"
  .string "you the Thunder Wave technique?$"


twave_Text_4::
  .string "Well, here you go.$"


twave_Text_5::
  .string "Thunder Wave causes paralysis in\n"
  .string "the target Pokémon.\p"
  .string "A paralyzed Pokémon may be unable\n"
  .string "to move in battle.\p"
  .string "It's an Electric-type move, so it\n"
  .string "won't work on some Pokémon.$"


twave_Text_6::
  .string "Oh...\n"
  .string "But Thunder Wave is convenient...$"


silphcogioleft_Text_Giomsg1::
  .string "Ah, {COLOR GREEN}{PLAYER}!{COLOR BLUE}\n"
  .string "So we meet again!\p"
  .string "The President and I are discussing\n"
  .string "a vital business proposition.\p"
  .string "Keep your nose out of grown-up\n"
  .string "matters...\p"
  .string "Or, experience a world of pain!$"


silphcogioleft_Text_Giolose::
  .string "Arrgh!!\n"
  .string "I lost again!?$"


silphcogioleft_Text_Giopostlosemsg::
  .string "Blast it all!\n"
  .string "You ruined our plans for Silph!\p"
  .string "But, Team Rocket will never fall!\p"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}! Never forget that all\n"
  .string "Pokémon exist for Team Rocket!\p"
  .string "I must go, but I shall return!$"


