ssanne_Text_sailor1PreBattle::
  .string "Ahoy, there!\n"
  .string "Are you seasick?$"


ssanne_Text_sailor1Lose::
  .string "I was just careless!$"


ssanne_Text_sailor1postbattle::
  .string "My pa said there are 100 kinds of\n"
  .string "Pokémon. I think there are more.$"


ssanne_Text_sailor1cantbattle::
  .string "Hmm...\n"
  .string "You're going to need more\l"
  .string "Pokémon to battle us.$"


ssanne_Text_sailor2PreBattle::
  .string "Hey, matey!\p"
  .string "Let's do a little jig!$"


ssanne_Text_sailor2Lose::
  .string "You're impressive!$"


ssanne_Text_sailor2postbattle::
  .string "How many kinds of Pokémon do you\n"
  .string "think there are in this big world?$"


ssanne_Text_PreBattle::
  .string "I collected these Pokémon\n"
  .string "from all around the world!$"


ssanne_Text_trainer1_lose::
  .string "Oh, no!\n"
  .string "I went around the world for these!$"


ssanne_Text_trainer1_postbattle::
  .string "You hurt my poor Pokémon!\p"
  .string "I demand that you heal them at a\n"
  .string "Pokémon Center!$"


ssanne_Text_trainer2_prebattle::
  .string "Competing against the young keeps\n"
  .string "me youthful.$"


ssanne_Text_trainer2_lose::
  .string "Good match!\n"
  .string "Ah, I feel young again!$"


ssanne_Text_trainer2_postbattle::
  .string "Fifteen years ago, I would\n"
  .string "have won!$"


Vermillion_Text_Gardevoir::
  .string "Vooir!$"


Vermillion_Text_GardevoirTrainer::
  .string "I always travel with {COLOR GREEN}Gardevoir.\n"
  .string "{COLOR RED}I never leave home without it.$"


Ssanne_Text_ChesnTrainer::
  .string "My buddy {COLOR GREEN}Chesnaught{COLOR BLUE} is so strong!\p"
  .string "He has enough Strength to move\n"
  .string "big rocks!$"


Ssanne_Text_Chesnaught::
  .string "Chesnaught ches!$"


