startersmegastone_Text_Msg::
  .string "Hi! I study Mega Evolution.\p"
  .string "If you show me a fully evolved Kanto\n"
  .string "starter capable of Mega Evolution,\l"
  .string "I'll give you its corresponding\l"
  .string "Mega Stone.$"


startersmegastone_Text_2::
  .string "I already gave you a Mega Stone\n"
  .string "for that.$"


startersmegastone_Text_3::
  .string "Yes!\p"
  .string "That can Mega Evolve!\p"
  .string "Please take this.$"


startersmegastone_Text_4::
  .string "Your {STR_VAR_1}...$"


startersmegastone_Text_5::
  .string "It's not what I'm looking for.$"


startersmegastone_Text_6::
  .string "Well, I'll be here if you need me.$"


startersmegastone_Text_7::
  .string "Wow, you've got all the Starter\n"
  .string "Mega Stones!\p"
  .string "I'm impressed!\p"
  .string "You're deserving of this.$"


startersmegastone_Text_8::
  .string "Among one of the best Megas,\n"
  .string "use him wisely!$"


startersmegastone_Text_Milked::
  .string "Dude, you already milked me good\n"
  .string "for free shit.\p"
  .string "What more do you want?$"


