ThreeIsland_Text_WingullBoy::
  .string "I'm going to train my {COLOR GREEN}Wingull{COLOR BLUE} in the\n"
  .string "{COLOR GREEN}Berry Forest.{COLOR BLUE}\p"
  .string "When it evolves, I'm going to de-\n"
  .string "stroy the Elite Four with my rain\l"
  .string "team!$"


ThreeIsland_Text_Wingull::
  .string "{COLOR BLUE}Wingull!$"


threeislandguy_Text_Impressive::
  .string "You've got seriously impressive\n"
  .string "Pokémon with you.$"


threeislandguy_Text_Thanks::
  .string "Thank you! Those goons were\n"
  .string "nothing but bad trouble.\p"
  .string "Please, take this as part\n"
  .string "of my gratitude.$"


threeislandguy_Text_Noneed::
  .string "We don't need you people bringing\n"
  .string "your noise and trouble here!\p"
  .string "We're asking you to go back to\n"
  .string "Kanto!$"


threeislandguy_Text_Gocry::
  .string "Hey, go cry somewhere else.\n"
  .string "Our boss is on his way.\p"
  .string "When he gets here, we'll give you\n"
  .string "a k-rad motorbike show you won't\l"
  .string "soon forget!$"


threeislandguy_Text_GetOut::
  .string "W-what!? Not on your life!\n"
  .string "Get off the island now!$"


threeislandguy_Text_WhoGonnaMakeMe::
  .string "Who's gonna make me?$"


ThreeIsland_Text_Gatekeeper1::
  .string "{COLOR BLUE}Hello there trainer.\n"
  .string "{COLOR GREEN}Berry Forest{COLOR BLUE} is an interesting\l"
  .string "challenge for trainers that are\l"
  .string "looking for some practice.\p"
  .string "It's a small maze of sorts with\n"
  .string "potent foes.\p"
  .string "There may be a prize at the end.\n"
  .string "Or maybe not.\p"
  .string "Are you interested?$"


BerryForest_Text_GateKeeperRules::
  .string "{COLOR BLUE}Your Start menu and other functions\n"
  .string "have been disabled. So, you won't\l"
  .string "be able to heal.\p"
  .string "There are various trainers here\n"
  .string "that will open up paths if you\l"
  .string "defeat them.\p"
  .string "I'll be here if you want me to\n"
  .string "escort you out.\p"
  .string "Best of luck.$"


BerryForest_Text_GateKeeperEscort::
  .string "Would you like me to escort you\n"
  .string "out?$"


BerryForest_Text_AceTrainer1_1::
  .string "Ah, someone finally found me!\p"
  .string "You know, it's said a Legendary Poké-\n"
  .string "mon is known to roam this forest,\l"
  .string "but I've been working here for quite\l"
  .string "some time and have never seen\l"
  .string "such a thing at all.\p"
  .string "Anywho, you ready to fight?$"


BerryForest_Text_AceTrainer1_2::
  .string "I'm gonna give it my all!$"


BerryForest_Text_AceTrainer1_3::
  .string "It's never enough eh...$"


BerryForest_Text_AceTrainer1_4::
  .string "I can heal two Pokémon.\n"
  .string "Shall I heal the first?$"


BerryForest_Text_AceTrainer1_4_2::
  .string "{COLOR BLUE}Your {COLOR GREEN}{STR_VAR_1}{COLOR BLUE} has been healed.$"


BerryForest_Text_AceTrainer1_4_3::
  .string "Shall I heal the second?$"


BerryForest_Text_AceTrainer1_5::
  .string "Hm... Well, suit yourself.$"


BerryForest_Text_AceTrainer1_6::
  .string "I've opened up a path for you.\p"
  .string "Have fun trainer.$"


BerryForest_Text_AceTrainer2_1::
  .string "Carnivine-S is a useful Pokémon,\n"
  .string "especially when compared to its\l"
  .string "lackluster Sinnoh form.\p"
  .string "You can find plenty of those\n"
  .string "in this forest.\p"
  .string "Of course, you can't encounter Poké-\n"
  .string "mon until your bag is enabled\l"
  .string "again.\p"
  .string "Well, are you ready to face\n"
  .string "off, trainer?$"


BerryForest_Text_AceTrainer2_2::
  .string "Okay, let's go!$"


BerryForest_Text_AceTrainer2_3::
  .string "Sheesh...$"


BerryForest_Text_AceTrainer2_4::
  .string "Okay well, I can heal two\n"
  .string "Pokémon. Shall I heal the first?$"


BerryForest_Text_AceTrainer2_4_2::
  .string "{COLOR RED}Your {COLOR GREEN}{STR_VAR_1}{COLOR RED} has been healed.$"


BerryForest_Text_AceTrainer2_4_3::
  .string "Do you want me to heal another?$"


BerryForest_Text_AceTrainer2_5::
  .string "Well, okay then.$"


BerryForest_Text_AceTrainer2_6::
  .string "Another path has been opened.\n"
  .string "Have fun.$"


BerryForest_Text_AceTrainer3_1::
  .string "Traditionally, Fire Red doesn't keep\n"
  .string "track of time, so the hidden berries in this\l"
  .string "forest regenerate after 1500 steps.\p"
  .string "Of course, that's been changed\n"
  .string "in Radical Red, but the original\l"
  .string "functionality still remains.\p"
  .string "Anyway, would you like to begin?$"


BerryForest_Text_AceTrainer3_2::
  .string "Whoo, I'm pumped up!$"


BerryForest_Text_AceTrainer3_3::
  .string "Too easy eh...$"


BerryForest_Text_AceTrainer3_4::
  .string "As usual, I can heal two Pokémon.\p"
  .string "Shall I heal the first?$"


BerryForest_Text_AceTrainer3_4_2::
  .string "{COLOR BLUE}Your {COLOR GREEN}{STR_VAR_1}{COLOR BLUE} has been healed.$"


BerryForest_Text_AceTrainer3_4_3::
  .string "Do you want me to heal another?$"


BerryForest_Text_AceTrainer3_5::
  .string "Huh, you do you.$"


BerryForest_Text_AceTrainer3_6::
  .string "I've opened up a path for ya.\n"
  .string "Bye bye!$"


BerryForest_Text_AceTrainer4_1::
  .string "Ah hello! I'm the final hurdle!\p"
  .string "Y'know, it's been so long since some-\n"
  .string "one's reached the end, I'm not even\l"
  .string "sure anything's present at the\l"
  .string "end.\p"
  .string "But legends have said a cute pink\n"
  .string "Pokémon awaits...\p"
  .string "Sounds like a {COLOR GREEN}Jigglypuff{COLOR RED} eh!\p"
  .string "Wouldn't that be disappointing!\n"
  .string "Hahaha...\p"
  .string "Well, shall we begin, trainer?$"


BerryForest_Text_AceTrainer4_2::
  .string "Good luck.$"


BerryForest_Text_AceTrainer4_3::
  .string "Wow, you really want that Jigglypuff!$"


BerryForest_Text_AceTrainer4_4::
  .string "Okay well, I won't touch your party.\p"
  .string "I doubt they need help against\n"
  .string "the pink menace.$"


BerryForest_Text_AceTrainer4_4_2::
  .string "{COLOR RED}Your {COLOR GREEN}{STR_VAR_1}{COLOR RED} has been healed.$"


BerryForest_Text_AceTrainer4_4_3::
  .string "Do you want me to heal another?$"


BerryForest_Text_AceTrainer4_5::
  .string "Well, okay then.$"


BerryForest_Text_AceTrainer4_6::
  .string "I've opened the final path.\p"
  .string "I hope you find something useful.$"


ThreeIslandLostelle_Text_LostelleOne::
  .string "{COLOR GREEN}Lostelle:{COLOR RED} Whimper... Sniff...\n"
  .string "Oh! Please, help!\p"
  .string "I used the walk through walls cheat\n"
  .string "and somehow ended up here.\p"
  .string "Now my games bugged and I can't find\n"
  .string "a way out of here!\p"
  .string "This made {COLOR GREEN}Lostelle{COLOR RED} scared.\p"
  .string "I'm too scared to move!\n"
  .string "But I want to go home...$"


ThreeIslandLostelle_Text_LostelleTwo::
  .string "Oh! Is this a Pokémon?!\n"
  .string "No! Go away! It's scaring me!\p"
  .string "Waaaaaaah!\n"
  .string "I want my daddy!$"


ThreeIslandLostelle_Text_LostelleThree::
  .string "Ohh! That Pokémon was cute, actually!\n"
  .string "I shouldn't have been so scared.\p"
  .string "Thank you!\p"
  .string "{COLOR GREEN}Lostelle{COLOR RED} came to pick some\n"
  .string "Berries.\p"
  .string "...Oh, you don't need berries?\p"
  .string "Well, you can have this instead.$"


ThreeIslandLostelle_Text_LostelleFour::
  .string "What's your name?\p"
  .string "{COLOR GREEN}Lostelle's{COLOR RED} scared, so can I go\n"
  .string "with you to my daddy's house?\p"
  .string "Okay!\n"
  .string "Let's go home!$"


ThreeIsland_Text_CaveGuyDonege::
  .string "That's Groundium Z.\n"
  .string "I found one of those mining here.\p"
  .string "Unfortunately, I'm not strong enough\n"
  .string "to make use of it.$"


ThreeIsland_Text_CaveGuy1::
  .string "Hey, there! How's it going?\n"
  .string "I've struck gold!\p"
  .string "You can't begin to imagine just\n"
  .string "how happy I am.\p"
  .string "So, I'll show you!\n"
  .string "This is for you!\p"
  .string "...Huh? You don't want gold?\p"
  .string "Hmm... that's a new one.\n"
  .string "Perhaps you'd like this instead.$"


BerryForest_Text_MewGotAway::
  .string "The Mew got away...$"


BerryForest_Text_GatekeeperMew::
  .string "{COLOR BLUE}Huh, is that {COLOR GREEN}Mewtwo?!$"


BerryForest_Text_GatekeeperMew_1::
  .string "{COLOR BLUE}It was truly puzzling...\p"
  .string "I am the gatekeeper that allowed you\n"
  .string "entry to {COLOR GREEN}Berry Forest{COLOR BLUE} earlier.\p"
  .string "My duty has been protecting {COLOR GREEN}Mew.{COLOR BLUE}\p"
  .string "{COLOR GREEN}Mew{COLOR BLUE} here was always a kind Poké-\n"
  .string "mon, who would travel far and wide\l"
  .string "providing assistance to strangers in\l"
  .string "need.\p"
  .string "{COLOR GREEN}Berry Forest{COLOR BLUE} was its true home,\n"
  .string "where it'd stop occasionally to bless\l"
  .string "trainers with its presence...\p"
  .string "However, its recent attack on the\n"
  .string "poor {COLOR GREEN}Lostelle{COLOR BLUE} was truly out of\l"
  .string "character!\p"
  .string "But, now it makes sense...\p"
  .string "{COLOR GREEN}Mew{COLOR BLUE} has been angsty knowing {COLOR GREEN}Mewtwo{COLOR BLUE}\n"
  .string "has awoken in the cave it resided\l"
  .string "in...$"


BerryForest_Text_GatekeeperMewtwo::
  .string "{COLOR GREEN}Mewtwo: {COLOR BLUE}I admit, I was once\n"
  .string "an apathetic machine...\p"
  .string "But ever since I've been under\n"
  .string "the wing of {COLOR GREEN}{PLAYER}{COLOR BLUE},\l"
  .string "I've become far less belligerent...\p"
  .string "I've come simply so I could\n"
  .string "witness the power of my original.$"


BerryForest_Text_GatekeeperMew_2::
  .string "{COLOR BLUE}Mm... I've heard tales of your potential\n"
  .string "to communicate.\p"
  .string "It seems they are true.\p"
  .string "Fine, if it's a battle you seek, I will\n"
  .string "do my best to deliver.\p"
  .string "It may help {COLOR GREEN}Mew{COLOR BLUE} loosen up.$"


BerryForest_Text_GateKeeperMewCry::
  .string "{COLOR RED}Mew!$"


BerryForest_Text_GatekeeperMew_3::
  .string "{COLOR BLUE}Well then. {COLOR GREEN}Mew{COLOR BLUE} has spoken.\n"
  .string "Let us begin.$"


BerryForest_Text_DotDotdot::
  .string "...$"


BerryForest_Text_Gatekeeper_Loss::
  .string "Mm...\n"
  .string "That is most impressive.$"


BerryForest_Text_GatekeeperMew_4::
  .string "{COLOR BLUE}Yes...\n"
  .string "From this fight, I can attest that\l"
  .string "{COLOR GREEN}Mewtwo{COLOR BLUE} is under good hands.$"


BerryForest_Text_GatekeeperMew_5::
  .string "{COLOR BLUE}What do you think, {COLOR GREEN}Mew?$"


BerryForest_Text_GatekeeperMew_6::
  .string "{COLOR BLUE}How interesting...\p"
  .string "It appears {COLOR GREEN}Mew{COLOR BLUE} would like to\n"
  .string "join your party.$"


BerryForest_Text_GatekeeperMew_7::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Mew!$"


BerryForest_Text_GatekeeperMew_7_2::
  .string "{COLOR BLACK}It was holding an item...$"


BerryForest_Text_GatekeeperMew_8::
  .string "{COLOR BLUE}Well, it seems my life-long duty\n"
  .string "here is finished.\p"
  .string "It may be time for me to enjoy\n"
  .string "retirement...\p"
  .string "What a strange day.\n"
  .string "Good bye, {COLOR GREEN}{PLAYER}.\p"
  .string "{COLOR BLUE}Please take good care of {COLOR GREEN}Mew.$"


BerryForest_Text_MewtwoPost::
  .string "{COLOR BLUE}Hmm, how peculiar.\n"
  .string "It seems {COLOR GREEN}Mew's {COLOR BLUE}stats are significantly\l"
  .string "inferior to mine.\p"
  .string "However, it has the capability of\n"
  .string "learning nearly every single technique.\p"
  .string "I wonder how I lost such a skill\n"
  .string "in my birth...\p"
  .string "Regardless, I am thankful that you've\n"
  .string "given me this opportunity,\l"
  .string "{COLOR GREEN}{PLAYER}.\p"
  .string "{COLOR BLUE}I am forever grateful.$"


