Viridian_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "Natures can be a big difference maker!\n"
  .string "The stats colored in {COLOR RED}red{COLOR BLACK} are in-\l"
  .string "creased by 10% while the stats co-\l"
  .string "lored in {COLOR BLUE}blue{COLOR BLACK} are decreased by 10%.\p"
  .string "Take advantage of the Nature Changer\n"
  .string "in the Pokémon Center to optimize\l"
  .string "your Pokémon!$"


Viridian_Text_TrainerTips2 ::
  .string "Trainer Tips\p"
  .string "Consumable held items are automati-\n"
  .string "cally retrieved at the end of each\l"
  .string "trainer battle!\p"
  .string "{COLOR GREEN}Focus Sash{COLOR BLACK} is returned after wild\n"
  .string "battles too.$"


Pewter_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "Press {R_BUTTON} on a Pokémon in the Dex\n"
  .string "Nav menu to register it!\p"
  .string "Pressing {R_BUTTON} again in the overworld\n"
  .string "will quickly search for that Pokémon.$"


ViridianForest_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "For your convinience, the abilities\n"
  .string "{COLOR GREEN}Static, Effect Spore, and Flame Body{COLOR BLACK}\l"
  .string "do not proc in Wild Battles.$"


ViridianForest_Text_TrainerTips2::
  .string "Trainer Tips\p"
  .string "A significant amount of changes have\n"
  .string "been made to many Pokémon's stats,\l"
  .string "typing, learnsets, and more.\p"
  .string "It is highly recommended to check the\n"
  .string "documentation online for more info!$"


ViridianForest_Text_TrainerTips3::
  .string "Trainer Tips\p"
  .string "A higher search level on the Dex Nav\n"
  .string "can give a better chance of one\l"
  .string "or more of the following:\l"
  .string "Egg Moves, perfect IVs in 1-3 stats,\l"
  .string "Hidden Ability, and higher shiny\l"
  .string "odds.$"


LugiaCode_Text::
  .string "qNubjEQuZki$"


ViridianForest_Text_TrainerTips4::
  .string "Trainer Tips\p"
  .string "Night-time ranges from 8:00 PM\n"
  .string "to 4:00 AM.$"


Cerulean_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "Raid Dens can be fought multiple times!\n"
  .string "They reset at midnight.$"


Celadon_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "Press {R_BUTTON} on the in-battle move\n"
  .string "menu to pull up a screen that dis-\l"
  .string "plays turns left for Weather,\l"
  .string "Terrain, Trick Room, and Screens!$"


Celadon_Text_TrainerTips2::
  .string "Trainer Tips\p"
  .string "Although item usage is not permitted\n"
  .string "in boss battles, held items are!\p"
  .string "When used properly, they can be a\n"
  .string "huge difference maker.$"


Saffron_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "All Pokémon present in the party\n"
  .string "earn EVs if the Exp. Share is en-\l"
  .string "abled, even if they didn't partipate\l"
  .string "in battle.$"


Saffron_Text_TrainerTips2::
  .string "Trainer Tips\p"
  .string "{COLOR GREEN}Bottle Caps{COLOR BLACK} are held by wild {COLOR GREEN}Trubbish,\n"
  .string "Sandygast{COLOR BLACK} and their respective\l"
  .string "evolutions, along with {COLOR GREEN}Delibird.$"


Route13_Text_TrainerTips1::
  .string "Trainer Tips\p"
  .string "Pokemon holding EV Training Gear\n"
  .string "automatically receive 24 respective\l"
  .string "EVs at the end of a battle.$"


Route17_Text_TrainerTips1::
  .string "Trainer Tips\p$"


pallettown_Text_trainertips::
  .string "Trainer Tips\p"
  .string "This game is incompatible with Eclipse\n"
  .string "emulator!\p"
  .string "Please use Delta or GBA4Ios\n"
  .string "instead.$"


