TwoIsland_Text_SteelBeam1::
  .string "I'm quite the PokéManiac!\n"
  .string "I teach a very special move.\p"
  .string "Ah, for the Champion I'll teach it\n"
  .string "for free!\p"
  .string "The move is Steel Beam!\n"
  .string "How about it?$"


TwoIsland_Text_SteelBeam2::
  .string "This takes a lot out of your Pokémon,\n"
  .string "but in exchange its effect can be\l"
  .string "devastating.$"


TwoIsland_Text_SteelBeam3::
  .string "Well, it is a risky move after all.$"


HoOhCode_Text::
  .string "RXIIqgh29$"


TwoIsland_Text_Whitney1::
  .string "{COLOR RED}Hmm... a sort of cheeky way to\n"
  .string "make my Miltank great again...$"


TwoIsland_Text_WhitneyDot::
  .string "{COLOR RED}...$"


TwoIsland_Text_Whitney2::
  .string "{COLOR RED}Oh hey {COLOR GREEN}{PLAYER}!{COLOR RED}\p"
  .string "I've been looking into how to make\n"
  .string "my Normal types more viable.\p"
  .string "Although branching into Fairy types\n"
  .string "has helped, I really just wanted to\l"
  .string "be able to use my Miltank again.\p"
  .string "And I think I finally figured it out!\n"
  .string "Inverse battles!\p"
  .string "Here, Normal types are offensive\n"
  .string "menaces!\p"
  .string "Care to face off in one of these with\n"
  .string "me?$"


TwoIsland_Text_Whitney2_2::
  .string "Hey {COLOR GREEN}{PLAYER}{COLOR RED}!\p"
  .string "Care to face off in an inverse battle\n"
  .string "with me?$"


TwoIsland_Text_WhitneyYes::
  .string "{COLOR RED}Woohoo! Miltank let's play!$"


TwoIsland_Text_WhitneyNo::
  .string "{COLOR RED}Ah well.$"


TwoIsland_Text_Whitney3::
  .string "{COLOR RED}It's just been a struggle for me\n"
  .string "staying afloat in quarantine.\p"
  .string "I had to auction off my Miltank online\n"
  .string "to some complete creeps...\p"
  .string "And I'm already back to being broke.\p"
  .string "I can't even imagine what they're\n"
  .string "doing to my Miltank either.\p"
  .string "The buyer wouldn't stop talking\n"
  .string "about my Miltank's Milkie Wilkies...\p"
  .string "What have I done...$"


TwoIsland_Text_Whitney3_2::
  .string "{COLOR RED}I'm sorry {COLOR GREEN}{PLAYER}{COLOR RED}.\n"
  .string "I know you'd like a battle but I'm\l"
  .string "just not in the mood.$"


TwoIslandWhitney4_Text::
  .string "{COLOR RED}...Huh?\n"
  .string "That shiny ray of hope...\p"
  .string "Is it for me?!$"


TwoIslandWhitneyGive_Text::
  .string "{COLOR BLACK}Give Whitney a Big Nugget?$"


TwoIslandWhitney5_Text::
  .string "{COLOR RED}Ah. It was silly of me to get my\n"
  .string "hopes up. Sorry about that.$"


TwoIslandWhitney6_Text::
  .string "{COLOR RED}Oh my! That's so sweet of you!\n"
  .string "I seriously could cry...\p"
  .string "Thank you so much!\p"
  .string "If you're looking for a battle, I will\n"
  .string "say I don't have money to give...\p"
  .string "But I'm definitely up for it!$"


TwoIslandWhitney7_Text::
  .string "{COLOR RED}Anytime champ!$"


TwoIslandWhitney8_Text::
  .string "{COLOR RED}Okay, let's get it!$"


Whitney2_Text_Defeat::
  .string "I wouldn't expect any less from you!$"


TwoIslandWhitney9_Text::
  .string "{COLOR RED}Agh, even in Inverse Battles\n"
  .string "my Miltank can't put a dent!\p"
  .string "I don't really mean to give up\n"
  .string "on my best buddy...\p"
  .string "But power creep is a real thing.\p"
  .string "Back in the day my Miltank made\n"
  .string "kids cower! You better\l"
  .string "believe it!\p"
  .string "But, I feel blessed to fight against\n"
  .string "you again.\p"
  .string "Please, have this!$"


TwoIslandWhitney10_Text::
  .string "{COLOR RED}What sort of buff could make\n"
  .string "you great again, Miltank...$"


TwoIslandWhitney11_Text::
  .string "{COLOR RED}Miltank... your sacrifice won't be\n"
  .string "in vain...\p"
  .string "I'm so sorry...$"


OfficerJenny_Text_1::
  .string "{COLOR RED}Hi, there's no walk in visitations at\n"
  .string "the moment, you need an appointment...$"


OfficerJenny_Text_2::
  .string "{COLOR RED}Wait a sec! You're the Champion!\n"
  .string "Aren't you?$"


OfficerJenny_Text_2_2::
  .string "{COLOR RED}I so knew it!\p"
  .string "This is exciting, we don't see folk\n"
  .string "like you around here often.$"


OfficerJenny_Text_CantFool::
  .string "{COLOR RED}Haha, you can't fool me!\n"
  .string "I know who you are, {COLOR GREEN}{PLAYER}!$"


OfficerJenny_Text_3::
  .string "{COLOR RED}Look, we could use some help crackin\n"
  .string "down on criminals. I'm sure you've\l"
  .string "had your run in with some sketchy\l"
  .string "individuals.\p"
  .string "We really could use some help!\n"
  .string "We'd reward you handsomely, of\n"
  .string "course.$"


OfficerJenny_Text_3_2::
  .string "{COLOR RED}Help us catch some thugs, yeah?$"


OfficerJenny_Text_3_3::
  .string "{COLOR RED}Great, I knew you'd be willing to help!\n"
  .string "Here's a tracker you can use to ping\l"
  .string "us if you witness any illegal activity.$"


OfficerJenny_Text_Cmon::
  .string "{COLOR RED}C'mon now, don't be like that!$"


OfficerJenny_Text_4::
  .string "{COLOR RED}Go do your thang!\n"
  .string "We appreciate you!$"


TwoIslandJail_Text_NPC_1::
  .string "I'm waiting to see my son.\n"
  .string "His crime? Oh boy...\p"
  .string "He brought a Stall team to the Elite\n"
  .string "Four...$"


TwoIslandJail_Text_NPC_2::
  .string "I don't think I'd ever forgive him\n"
  .string "for such a treacherous crime, but he\l"
  .string "is still my son. So, I'm here.$"


TwoIslandJail_Text_Sign::
  .string "Two Island Jail\n"
  .string "Opress those who deserve it least!$"


TwoIslandPC_Text_NPC_1::
  .string "Have you visited the Two Island jail\n"
  .string "already?\p"
  .string "Officer Jenny's pretty damn annoying.\p"
  .string "I hear it's easy to break into,\n"
  .string "for what it's worth.$"


TwoIsland_Text_GC_Owner1::
  .string "This used to be a Game Corner\n"
  .string "that allowed people to play special\l"
  .string "mini-games so long they brought\l"
  .string "a friend.\p"
  .string "Turns out, people who play Radical\n"
  .string "Red don't really have friends.\p"
  .string "So it was a business model doomed to\n"
  .string "fail.\p"
  .string "Now it's just become a tiny hangout\n"
  .string "spot.$"


TwoIsland_Text_GC_StarterGuy1::
  .string "Yo! I heckin love Starter Pokémon!\p"
  .string "In fact, I got some pretty nifty\n"
  .string "move tutors specifically for\l"
  .string "starters.\p"
  .string "I'll teach them to you if you\n"
  .string "beat me in a Starter only duel.\p"
  .string "How about it?$"


TwoIsland_Text_GC_StarterGuyNotEligible::
  .string "Hmm, your team needs to be\n"
  .string "only starter Pokémon.\p"
  .string "I thought we had a deal!$"


TwoIsland_Text_GC_StarterGuyBeginBattle::
  .string "Ohohoh! I like what I see!\n"
  .string "Let's get it!$"


TwoIsland_Text_GC_StarterGuyLoss::
  .string "Woah. I got totally outclassed!$"


TwoIsland_Text_GC_StarterGuy2::
  .string "Alright alright. So here are the moves.\p"
  .string "Frenzy Plant, Hydro Cannon, and\n"
  .string "Blast Burn. I'm sure you've\l"
  .string "heard of them.\p"
  .string "...$"


TwoIsland_Text_GC_StarterGuy3::
  .string "...What? Those moves blow?\n"
  .string "No way man. They're a curated version\l"
  .string "I've developed that don't need to\l"
  .string "recharge if they kill the targetted\l"
  .string "Pokémon.\p"
  .string "Some real nostalgic stuff!\p"
  .string "Plus, they even have a high chance of\n"
  .string "inflicting status if they live.\p"
  .string "Although... they only have 4 PP.\p"
  .string "Still, they are pretty fun moves to\n"
  .string "use.$"


TwoIsland_Text_GC_StarterGuy4::
  .string "Which move are you interested in?$"


TwoIsland_Text_GC_StarterGuy5::
  .string "Hope the moves come in handy.$"


HydroCannon_Text::
  .string "Hydro Cannon$"


FrenzyPlant_Text::
  .string "Frenzy Plant$"


BlastBurn_Text::
  .string "Blast Burn$"


JoyfulGameCorner_woIsland_Text_YouRescuedLostelle::
  .string "{COLOR BLUE}So you rescued {COLOR GREEN}Lostelle?{COLOR BLUE}\n"
  .string "How can I thank you?\p"
  .string "{COLOR GREEN}Lostelle{COLOR BLUE}, darling, forgive me!\p"
  .string "Daddy didn't know you were scared\n"
  .string "and in trouble!$"


JoyfulGameCorner_woIsland_Text_LostelleItsOkayDaddy::
  .string "{COLOR GREEN}Lostelle:{COLOR RED} It's okay, Daddy.\n"
  .string "I got to be friends with {COLOR GREEN}{PLAYER}!{COLOR RED}$"


twoislandgcguy_Text_Msgone::
  .string "Hey, but listen! I'm begging you,\n"
  .string "you have to go to Three Island.\p"
  .string "If anything were to happen to my\n"
  .string "{COLOR GREEN}Lostelle...\p"
  .string "{COLOR BLUE}My place is the house with the red\n"
  .string "roof on Three Island.\p"
  .string "She may just show up late here,\n"
  .string "so I can't run off anywhere.\p"
  .string "That's why I have to get you to do\n"
  .string "me this big favor.$"


twoislandgcguy_Text_GText_MsgTwo::
  .string "Thank you for saving {COLOR GREEN}Lostelle!\p"
  .string "{COLOR BLUE}Hm, there's a Mew in the forest\n"
  .string "that ran away?\p"
  .string "I'm sure if you brought a Poké-\n"
  .string "mon like {COLOR GREEN}Mewtwo{COLOR BLUE} to {COLOR GREEN}Berry Forest,{COLOR BLUE}\l"
  .string "it could track it down...$"


twoislandgcguy_Text_GText_MsgThree::
  .string "Oh?! Did you catch the {COLOR GREEN}Mew!\p"
  .string "{COLOR BLUE}That's amazing {COLOR GREEN}{PLAYER}!{COLOR BLUE}$"


TwoIslandWhitney9_Text_2::
  .string "As an Inverse Battle specialist,\n"
  .string "I don't have use for this special\l"
  .string "{COLOR GREEN}Clefable{COLOR RED} anymore...\p"
  .string "I insist you take it!\n"
  .string "It's a special {COLOR GREEN}Clef{COLOR RED} with {COLOR GREEN}Light\l"
  .string "Of Ruin,{COLOR RED} which is an insane combo with\l"
  .string "Magic Guard.$"


TwoIslandWhitney9_Text_3::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Clefable!{COLOR BLACK}$"


