punchtutor_Text_1::
  .string "I teach Elemental Punches and Fangs,\n"
  .string "but it's going to cost ya \$2500.\p"
  .string "Interested?$"


punchtutor_Text_Text1::
  .string "Fire Punch$"


punchtutor_Text_Text2::
  .string "Ice Punch$"


punchtutor_Text_Text3::
  .string "Thunder Punch$"


punchtutor_Text_Text4::
  .string "Fire Fang$"


punchtutor_Text_Text5::
  .string "Ice Fang$"


punchtutor_Text_Text6::
  .string "Thunder Fang$"


punchTutor_Text_psychicfang::
  .string "Psychic Fangs$"


punchtutor_Text_Msg::
  .string "Which move shall I teach?$"


punchtutor_Text_3::
  .string "Cool. Who shall I teach it to?$"


punchtutor_Text_4::
  .string "Thank you come again.$"


punchtutor_Text_Wait::
  .string "...$"


ltsurge_Text_EncounterText::
  .string "{COLOR BLUE}Hey, kid! What do you think you're\n"
  .string "doing here?\p"
  .string "You won't live long in combat!\n"
  .string "Not with your puny power!\p"
  .string "I tell you, kid, electric Pokémon\n"
  .string "saved me during the war!\p"
  .string "They zapped my enemies into\n"
  .string "paralysis!\p"
  .string "The same as I'll do to you!$"


ltsurge_Text_DefeatText::
  .string "Now that's a shocker!\p"
  .string "You're the real deal, kid!\p"
  .string "Fine, then, take the Thunder Badge!$"


ltsurge_Text_Givetm::
  .string "{COLOR BLUE}You're special, kid!\n"
  .string "Take this!$"


ltsurge_Text_TMInfomsg::
  .string "{COLOR BLUE}TM92 contains Volt Switch!\p"
  .string "Teach it to an Electric Pokémon!$"


ltsurge_Text_Helloagain::
  .string "Kid! I was hoping to see you again.\p"
  .string "My Pokémon and I haven't forgotten\n"
  .string "that crazy ride we had with you.\p"
  .string "We're raring to get another shot at\n"
  .string "ya!$"


ltsurge_Text_Comeback::
  .string "Boo... Well, whenever you're ready.$"


ltsurge_Text_Battle::
  .string "I'm letting my beasts out!\p"
  .string "Here we go!$"


ltsurge_Text_Seconddefeat::
  .string "Another electrifying defeat!$"


ltsurge_Text_Won2text::
  .string "Heh, my Pokémon aren't keen on losing,\n"
  .string "but I can tell they're having a blast\l"
  .string "with you! You can have these.$"


ltsurge_Text_InfoHard::
  .string "{COLOR GREEN}Mega Manectric{COLOR BLUE} is a literal beast.\p"
  .string "It frightens foes with Intimidate,\n"
  .string "and threatens them out with its Speed\l"
  .string "and Special Attack.\p"
  .string "He's one of my favorites for a\n"
  .string "reason!$"


SSAnne_Text_CantForget1::
  .string "HM Cut is used to cut small trees.$"


Vermilion_Text_NewTruant::
  .string "Did you know {COLOR GREEN}Slaking{COLOR RED} can use Slack\n"
  .string "Off on turns it loafs around?\p"
  .string "It's quite powerful, don't you\n"
  .string "think?!$"


Vermilion_Text_NewHM::
  .string "Hidden Machines, like Cut, don't\n"
  .string "need to be taught anymore.\n"
  .string "How convenient!$"


Vermillion_Text_Infernape1::
  .string "...$"


Vermillion_Text_Infernape2::
  .string "{COLOR BLACK}It's an Infernape hard at work.$"


FanClub_Text_Girl1::
  .string "I just adore my {COLOR GREEN}Yamper!\n"
  .string "{COLOR RED}It's so lovable!\p"
  .string "It squeals when I hug it!$"


FanClub_Text_Girl2::
  .string "Oh, my!!\p"
  .string "Look at our {COLOR GREEN}Yampers{COLOR RED} playing!$"


FanClub_Text_Girl3::
  .string "How cute!\n"
  .string "Here, let me share these with\l"
  .string "you.$"


Vermillion_Text_Yamper::
  .string "{COLOR BLUE}{COLOR GREEN}Yamper:{COLOR BLUE} Yap yap!$"


Vermillion_Text_MailGuy::
  .string "I want to exchange Mail with all\n"
  .string "sorts of people.\p"
  .string "I send my {COLOR GREEN}Corviknight{COLOR BLUE} to a Union Room\n"
  .string "to exchange Mail for me.$"


Vermillion_Text_Corviknight::
  .string "Corv!$"


Vermillion_Text_MailGuy2::
  .string "I'm getting my {COLOR GREEN}Corviknight{COLOR BLUE} to fly a\n"
  .string "letter to Saffron in the north$"


