VRBrendanBattle_Text_1::
  .string "Oi, wait up!$"


VRBrendanBattle_Text_2::
  .string "Hey, it's me again...\p"
  .string "Sorry I couldn't help you further\n"
  .string "in {COLOR GREEN}Cerulean Cave{COLOR BLUE}.\p"
  .string "I got destroyed by {COLOR GREEN}Archer{COLOR BLUE} and ran\n"
  .string "away in shame...$"


VRBrendanBattle_Text_3 ::
  .string "You know recently...\p"
  .string "I don't know, I know I'm not a\n"
  .string "bad trainer by any means.\p"
  .string "I can snag Gym badges sure, \n"
  .string "but I've always wanted to be an\l"
  .string "incredible trainer like my Dad.\p"
  .string "And I really thought that as long\n"
  .string "as I put in the effort and work,\l"
  .string "I could be one of the best.\p"
  .string "But, I could never put a dent\n"
  .string "in you.\p"
  .string "Even trainers like {COLOR GREEN}Archer{COLOR BLUE} have\n"
  .string "shown me how far the gap between\l"
  .string "us has become.\p"
  .string "It's becoming clear to me that I'm\n"
  .string "just not very strong,\l"
  .string "let alone talented.$"


VRBrendanBattle_Text_4::
  .string "Is that what I'm missing?\p"
  .string "An innate trait that some are just\n"
  .string "gifted with?\p"
  .string "I just can't accept that...\p$"


VRBrendanBattle_Text_5::
  .string "Agh! I'm not sure what\n"
  .string "I'm trying to say.$"


VRBrendanBattle_Text_6::
  .string "I don't care.\n"
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}!\p"
  .string "We're battling.\p"
  .string "I won't take no for an answer!$"


VRBrendanLoss_Text::
  .string "Not sure what I was\n"
  .string "expecting...$"


VRBrendanBattle_Text_7::
  .string "I... I don't know.\p"
  .string "I'm discouraged. I know I shouldn't\n"
  .string "have shot for the stars, but...$"


VRBrendanBattle_Text_8::
  .string "The bottom line is I have a lot\n"
  .string "to learn.\p"
  .string "I'll be returning to Hoenn to train\n"
  .string "with my Dad.\p"
  .string "Maybe I'll come back sometime.\p"
  .string "Or you could come visit,\n"
  .string "if you'd like.\p"
  .string "I know, somehow, our paths will\n"
  .string "cross again.\p"
  .string "I still must thank you for always\n"
  .string "pushing me to my limit.\p"
  .string "In case I never see you again,\n"
  .string "take this.$"


VRBrendanBattle_Text_9::
  .string "The Mega Stone for my favorite\n"
  .string "Pokémon...\p"
  .string "It really needs no introduction.\p"
  .string "I don't need to stick around to\n"
  .string "see you win it all,\l"
  .string "you already ooze Champion status.\p"
  .string "Don't disappoint me!$"


VRBrendanBattle_Text_10::
  .string "So long, friend.$"


dada_Text_MartGreetingMsg ::
  .string "Welcome!\p"
  .string "How may I help you?$"


dada_Text_MartLeavingMsg::
  .string "Please come again!$"


FinalCreatorBattle_Text_1::
  .string "Well well, thought you could\n"
  .string "waltz into the Pokémon League\l"
  .string "without another boss battle?\p"
  .string "...Who the hell am I?\p"
  .string "I'm {COLOR GREEN}soupercell{COLOR BLUE}, the creator of\n"
  .string "this hack, dumbass!\p"
  .string "Anyway, I can't let any scrubs\n"
  .string "complete my game, so I'll need\l"
  .string "to give you an ass-whooping.$"


FinalCreatorBattle_Text_Loss::
  .string "W-what?! You...\n"
  .string "You beat my invincible strat?!$"


FinalCreatorBattle_Text_2::
  .string "Hot damn!\p"
  .string "I don't know why I doubted you!\p"
  .string "You're certainly ready.\p"
  .string "I've reserved this item for you,\n"
  .string "it's among one of the most\l"
  .string "bonkers Mega Evos so, you know,\l"
  .string "save the best for last.$"


FinalCreatorBattle_Text_3::
  .string "I will warn that I've dropped\n"
  .string "{COLOR GREEN}{RIVAL}{COLOR BLUE} some sick Pokémon on his\l"
  .string "way to the League.\p"
  .string "His team won't resemble the one\n"
  .string "you just faced. Have fun!\p"
  .string "Anyway, thanks for playing my ROM\n"
  .string "hack {COLOR GREEN}{PLAYER}{COLOR BLUE}, even if you didn't enjoy\l"
  .string "it.\p"
  .string "Have a good one, friend!$"


VictoryRoad_Text_Moltres1::
  .string "Gyaoo!$"


SelectThree_Text::
  .string "{COLOR BLACK}Select three Pokémon to take into\n"
  .string "battle.$"


StartRaidBattle_Text::
  .string "{COLOR BLACK}This strange den exuberates\n"
  .string "powerful energy.\p"
  .string "Would you like to look inside it?$"


RaidTeamUp_Text::
  .string "A powerful wild Pokémon came\n"
  .string "out!$"


StartRaidBattle2_Text::
  .string "It's an empty den.$"


Adamant_Text::
  .string "Adamant {COLOR RED}+Atk {COLOR BLUE}-SpA$"


Modest _Text::
  .string "Modest  {COLOR RED}+SpA {COLOR BLUE}-Atk$"


Timid _Text::
  .string "Timid    {COLOR RED}+Speed {COLOR BLUE}-Atk$"


Jolly _Text::
  .string "Jolly   {COLOR RED}+Speed {COLOR BLUE}-SpA$"


Hasty _Text::
  .string "Hasty   {COLOR RED}+Speed {COLOR BLUE}-Def$"


Naive _Text::
  .string "Naive   {COLOR RED}+Speed {COLOR BLUE}-SpD$"


Mild _Text::
  .string "Mild    {COLOR RED}+SpA {COLOR BLUE}-Def$"


Naughty_Text::
  .string "Naughty {COLOR RED}+Atk {COLOR BLUE}-SpD$"


Rash _Text::
  .string "Rash     {COLOR RED}+SpA {COLOR BLUE}-SpDef$"


Lonely _Text::
  .string "Lonely   {COLOR RED}+Atk {COLOR BLUE}-Def$"


Brave _Text::
  .string "Brave    {COLOR RED}+Atk {COLOR BLUE}-Speed$"


Quiet _Text::
  .string "Quiet    {COLOR RED}+SpA {COLOR BLUE}-Speed$"


Calm_Text::
  .string "Calm    {COLOR RED}+SpD {COLOR BLUE}-Atk$"


Impish_Text::
  .string "Impish  {COLOR RED}+Def {COLOR BLUE}-SpA$"


Sassy_Text::
  .string "Sassy   {COLOR RED}+SpD {COLOR BLUE}-Speed$"


Careful_Text::
  .string "Careful {COLOR RED}+SpD {COLOR BLUE}-SpA$"


Relaxed_Text::
  .string "Relaxed {COLOR RED}+Def {COLOR BLUE}-Speed$"


Bold _Text::
  .string "Bold     {COLOR RED}+Def {COLOR BLUE}-Atk$"


Bashful_Text::
  .string "Bashful     Neutral$"


Lax_Text::
  .string "Lax        {COLOR RED}+Def {COLOR BLUE}-SpD$"


Gentle_Text::
  .string "Gentle   {COLOR RED}+SpD {COLOR BLUE}-Def$"


Exit _Text::
  .string "Exit$"


NatureChanger1_Text::
  .string "We can change a Pokémon's nature\n"
  .string "free of charge! Interested?$"


NatureChanger2 _Text::
  .string "Which nature would you like?$"


NatureChanger3 _Text::
  .string "Sure thing!$"


NatureChanger3_Text_2::
  .string "One second...$"


NatureChanger4_Text::
  .string "Thank you, the nature has been\n"
  .string "changed!\p"
  .string "We hope to see you again!$"


nurse_Text_1::
  .string "You look tired.\n"
  .string "Take a rest.$"


nurse_Text_2::
  .string "Take care!$"


closecombat_Text_1::
  .string "You should be proud of yourself,\n"
  .string "having battled your way through\l"
  .string "Victory Road so courageously.\p"
  .string "In recognition of your feat,\n"
  .string "I'll teach you Close Combat.\p"
  .string "Would you like me to teach that\n"
  .string "technique?$"


closecombat_Text_2::
  .string "It'll cost \$25000 now.$"


closecombat_Text_3::
  .string "Which Pokémon should I teach\n"
  .string "Close Combat to?$"


closecombat_Text_4::
  .string "Keep that drive going for the\n"
  .string "Pokémon League!\p"
  .string "Take a run at them and knock 'em\n"
  .string "out!$"


closecombat_Text_No::
  .string "I'll teach you the technique\n"
  .string "anytime.$"


closecombat_Text_Wait::
  .string "...$"


closecombat_Text_Poor::
  .string "...You don't have enough money.$"


ShitsHard1 _Text::
  .string "Mate... the Elite Four here is\n"
  .string "on some wack shit.\p"
  .string "Thankfully the AI can act like some\n"
  .string "doodoo, use that to your advantage.$"


ShitsHard2_Text::
  .string "Yo... get the fuck outta here.\p"
  .string "You beat the game already lmao\p"
  .string "But forreal, the Elite Four\n"
  .string "rematch will be available eventually.$"


whitneytesttxt_Text::
  .string "I will warn that I've dropped\n"
  .string "{COLOR GREEN}{RIVAL}{COLOR BLUE} some sick Pokémon on his\l"
  .string "way to the League.\p"
  .string "His team won't resemble the one\n"
  .string "you just faced. Have fun!$"


GuardTopFloorDisappearBanned_Text::
  .string "Greetings. Unfortunately, the top floor\n"
  .string "is restricted for those playing on {COLOR GREEN}Minimal\l"
  .string "Grinding Mode.$"


GuardTopFloorDisappear1_Text::
  .string "Greetings. The top floor is mainly\n"
  .string "if you'd like to trade to yourself\l"
  .string "for whatever reason.\p"
  .string "Take care.$"


Route23_Text_CanOnlyPass::
  .string "{COLOR BLUE}You can pass here only if you have\n"
  .string "the Rising Badge.\p"
  .string "You don't have the Rising\n"
  .string "Badge yet.\p"
  .string "You have to have it to get to\n"
  .string "the Pokémon League.$"


Route23_Text_YouCanPass::
  .string "{COLOR BLUE}You can pass here only if you have\n"
  .string "the Rising Badge.\p"
  .string "Oh!\n"
  .string "That is the Rising Badge!\p"
  .string "Okay, then.\n"
  .string "Please, go right ahead.$"


EliteFour_Text_LoreleiForecast1::
  .string "Yo!\n"
  .string "Champ in the making!$"


EliteFour_Text_LoreleiForecastRain::
  .string "I think I saw {COLOR GREEN}Lorelei{COLOR BLUE} with a\n"
  .string "{COLOR GREEN}Swampert{COLOR BLUE} today.$"


EliteFour_Text_LoreleiForecastHail::
  .string "I think I saw {COLOR GREEN}Lorelei{COLOR BLUE} with an\n"
  .string "{COLOR GREEN}Abomasnow{COLOR BLUE} today.$"


EliteFour_Text_LoreleiForecast2::
  .string "Never mind, you're an actual Champ\n"
  .string "now.\p"
  .string "You're an inspiration$"


