Viridian_Text_WiseGlasses1::
  .string "Jeez...\p"
  .string "My friends said these glasses\n"
  .string "make you smarter, but it's not\l"
  .string "having much of an effect.\p"
  .string "You can take them.$"


Viridian_Text_WiseGlasses2::
  .string "...Oh? Those are for Pokémon?\p"
  .string "My friends must have been pulling\n"
  .string "a prank.\p"
  .string "Gr...$"


aidoranberry_Text_1 ::
  .string "Oh, you must be {COLOR GREEN}{PLAYER}{COLOR BLUE}!$"


aidoranberry_Text_2::
  .string "Sorry, I almost didn't recognize\n"
  .string "you!\p"
  .string "I'm one of {COLOR GREEN}Oak's {COLOR BLUE}aides. I was just\n"
  .string "picking up some packages for the\l"
  .string "professor.\p"
  .string "I think he wanted to give you this but\n"
  .string "didn't manage to get it on time.$"


aidoranberry_Text_3::
  .string "{COLOR BLUE}To access DexNav on the Start Menu,\n"
  .string "click the {ARROW_RIGHT} button.\p"
  .string "I've also upgraded your Pokédex to\n"
  .string "the National Dex.\p"
  .string "While I'm here, I may as well give\n"
  .string "you these too.$"


aidoranberry_Text_carepackage::
  .string "{COLOR BLUE}Ah, the care package cheat.\p"
  .string "Here then.$"


aidoranberry_Text_ifyouwant::
  .string "{COLOR BLUE}If you'd like a care package, please\n"
  .string "input the necessary password.$"


aidoranberry_Text_3_2::
  .string "{COLOR BLUE}Oh... You're playing {COLOR GREEN}Hardcore Mode{COLOR BLUE},\n"
  .string "are you?\p"
  .string "How brave of you!\p"
  .string "Here, take this too.$"


aidoranberry_Text_NiceHere::
  .string "Yup, that's it!\n"
  .string "Here's your first care package.$"


aidoranberry_Text_carepackageNo::
  .string "Hmm...\n"
  .string "That's not quite it.\p"
  .string "Would you like to try again?$"


aidoranberry_Text_4::
  .string "Take care!$"


aidoranberry_Text_Getnav::
  .string "You received the {COLOR GREEN}Dex Nav!$"


viridianforesttutor_Text_Forestmovetutor1::
  .string "Hello! My Bug type Pokémon LOVE\n"
  .string "{COLOR GREEN}Oran Berries!\p"
  .string "{COLOR BLUE}If you give me one, I can teach\n"
  .string "Bug Bite to one of your Pokémon.$"


viridianforesttutor_Text_Forestmovetutor2::
  .string "Oh! An Oran Berry! I can teach Bug\n"
  .string "Bite in exchange for one of those!$"


viridianforesttutor_Text_Forestmovetutor3::
  .string "Great! Who should I teach it to?$"


viridianforesttutor_Text_Forestmovetutor4::
  .string "My Weedle is pleased. Thanks!$"


viridianforesttutor_Text_Forestmovetutor5::
  .string "Aw okay...$"


brendanbattleleft_Text_1::
  .string "Hm... There should be a {COLOR GREEN}Joltik\n"
  .string "{COLOR BLUE}somewhere here...$"


brendanbattleleft_Text_2::
  .string "Oh hello!\p"
  .string "I'm just trying to catch some Poké-\n"
  .string "mon before I challenge {COLOR GREEN}Brock.$"


brendanbattleleft_Text_3::
  .string "...Oh? You're looking to challenge him\n"
  .string "as well?\p"
  .string "Why don't we have a battle then?$"


brendanbattleleft_Text_Defeat::
  .string "Oof, I'm missing something...$"


brendanbattleleft_Text_4::
  .string "I haven't had a loss like that in\n"
  .string "a while! But, that was rather fun. \p"
  .string "...{COLOR GREEN}{PLAYER}, {COLOR BLUE}huh...\p"
  .string "Here, I have an extra of these,\n"
  .string "they'll surely help you.$"


brendanbattleleft_Text_6::
  .string "Also, in case you didn't know...\p"
  .string "Pressing {A_BUTTON} on the stat section of\n"
  .string "the summary screen also brings you to\l"
  .string "the Stat Scanner.\p"
  .string "It shows information about EVs, IVs,\n"
  .string "and even evolution data.\p"
  .string "Anyway, I'm heading to Viridian to\n"
  .string "grab the PokéVial from the trainer\l"
  .string "school.\p"
  .string "You should check it out if you\n"
  .string "haven't already!\p"
  .string "Well, until we meet again,\n"
  .string "{COLOR GREEN}{PLAYER}!{COLOR BLUE}$"


brendantoceruleancave_Text_1::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}!$"


brendantoceruleancave_Text_2::
  .string "{COLOR BLUE}Oh my, I'm so glad to have found\n"
  .string "you.\p"
  .string "{COLOR GREEN}May{COLOR BLUE} told me she had just bumped\n"
  .string "into you here, so I hurried back\l"
  .string "over here.$"


brendantoceruleancave_Text_3::
  .string "{COLOR BLUE}I've come looking for your help!\p"
  .string "You're really the only one I\n"
  .string "know that could stop this...\p"
  .string "Team Rocket has occupied {COLOR GREEN}Cerulean\n"
  .string "Cave{COLOR BLUE}, it seems.\p"
  .string "There's rumors that a powerful\n"
  .string "legendary rests there...\p"
  .string "Could that be what they're looking\n"
  .string "for?!\p"
  .string "It sounds like bad news.\p"
  .string "Anywho, we need to put an end\n"
  .string "to it!\p"
  .string "Oh, you'd like a heal? Sure thing...$"


brendantoceruleancave_Text_4::
  .string "{COLOR BLUE}Okay, off we go.$"


giovannicheck_Text_1::
  .string "{COLOR BLACK}I ought to help Brendan in\n"
  .string "{COLOR GREEN}Cerulean Cave...$"


claire_Text_EncounterText::
  .string "{COLOR RED}Ah, a challenger finally arrives.\p"
  .string "I was about to take a nap.\p"
  .string "{COLOR RED}Although I'm the newly appointed\n"
  .string "Gym Leader of the Kanto region,\l"
  .string "I was once a leader in Johto.\p"
  .string "So, this is nothing new to me.\p"
  .string "{COLOR GREEN}Lance{COLOR RED} may be considered the world's\n"
  .string "dragon master, but I'm a close sec-\l"
  .string "ond!\p"
  .string "Do you still dare to take me on?\p"
  .string "Fine, let's do this!$"


Clair_Text_FairyOnly::
  .string "Though, I should mention I have a special\n"
  .string "rule in my Gym...\p"
  .string "You aren't allowed to bring Fairy\n"
  .string "types, including their Megas.$"


ClairFairyGood_Text::
  .string "...Seems like you're good,\n"
  .string "let's roll!$"


Clair_Text_TeamNotFit::
  .string "Seems like your team doesn't\n"
  .string "fit this criteria...\p"
  .string "Sorry, you'll have to come back\n"
  .string "without any Fairies...$"


claire_Text_DefeatText::
  .string "Oh, I see...\n"
  .string "Your skills are rather mysterious.\p"
  .string "Fine, have the Rising Badge.$"


claire_Text_Givetm::
  .string "{COLOR RED}TM59 contains Dragon Pulse.\n"
  .string "It's a huge blast of draconic\n"
  .string "energy.\p"
  .string "Teach it to a Dragon-type.\p"
  .string "Since you're off to the Pokémon\n"
  .string "League, this may help you.$"


claire_Text_TMInfomsg::
  .string "Years of being defeated as a Gym\n"
  .string "Leader have changed my perspect-\l"
  .string "ive, although I haven't been\l"
  .string "humbled like that in a while.\p"
  .string "Take this.$"


claire_Text_Altarianite::
  .string "Mega Duraludon becomes a non-\n"
  .string "stop barrage of Dracos.\p"
  .string "It is quite satisfying.$"


claire_Text_Helloagain::
  .string "Also...$"


claire_Text_Perfectpokemon::
  .string "If you show me a Dragon-type, I\n"
  .string "can teach it Draco Meteor.$"


claire_Text_Afterteaching::
  .string "Vanquish foes with the strongest\n"
  .string "Dragon-type move!$"


claire_Text_No::
  .string "This move strikes fear in its foes.\p"
  .string "You don't want to miss it.$"


Clair_Text_RematchAsk::
  .string "Ah, you are back.\n"
  .string "I see you've defeated my cousin\l"
  .string "{COLOR GREEN}Lance.{COLOR RED}\p"
  .string "I'm sure he still caused you some\n"
  .string "problems.\p"
  .string "Anyway, I've been itching for a battle.\p"
  .string "Would you be interested in a\n"
  .string "rematch? One caveat...\p"
  .string "No fairies. That pesky type brought\n"
  .string "me down from the peak of my\l"
  .string "prime.\p"
  .string "How about it?$"


Clair_Text_RematchBeforeBattle::
  .string "Let's see if I can relive\n"
  .string "my glory days.$"


Clair_Text_RematchDefeat::
  .string "Even with a handicap I've been\n"
  .string "doomed. Commendable.$"


Clair_Text_RematchAfterBattle::
  .string "I can clearly see the drive\n"
  .string "that crowned you Champion.\p"
  .string "For so long I had thought the\n"
  .string "introduction of Fairies was\l"
  .string "what made me weaker...\p"
  .string "I simply lacked the work ethic and\n"
  .string "determination I once had.\p"
  .string "Blaming Fairies was only an excuse.\p"
  .string "For helping me realize this,\n"
  .string "have my favorite TM.$"


Clair_Text_RematchAfterBattle2::
  .string "Draco Barrage is a perfect move\n"
  .string "for me as it bypasses the dread-\l"
  .string "ful Fairy immunity.\p"
  .string "Of course, I didn't need to use\n"
  .string "it that battle because of my\l"
  .string "handicap. Heh.\p"
  .string "Even as Champion, I'm sure you're\n"
  .string "grateful for gifts.\p"
  .string "Take one of my special\n"
  .string "{COLOR GREEN}Dragapults.$"


Clair_Text_RematchAfterBattle3::
  .string "{COLOR RED}Dragapult is a deadly mon, even\n"
  .string "though it's missing a physical\l"
  .string "Ghost STAB.\p"
  .string "However, I've trained mine to have\n"
  .string "{COLOR GREEN}Spirit Shackle.\p"
  .string "{COLOR RED}You may find your Dragon Dance\n"
  .string "sets far more potent accompanied\l"
  .string "by this.$"


Clair_Text_Dragapult::
  .string "{COLOR BLACK}You received a {COLOR GREEN}Dragapult!{COLOR BLACK}$"


Clair_Text_TeachDracoStill::
  .string "I'll still be here if you want\n"
  .string "me to teach {COLOR GREEN}Draco Meteor.{COLOR RED}$"


Clair_Text_SecretLance::
  .string "Hm...? You'd like to know how\n"
  .string "to get {COLOR GREEN}Primal Dialga?\p"
  .string "{COLOR RED}Hah... that may be a secret\n"
  .string "for another time.\p"
  .string "Anyway...$"


roamer_Text_1::
  .string "{COLOR GREEN}{PLAYER}{COLOR BLUE}!$"


roamer_Text_2::
  .string "{COLOR BLUE}Hi, I'm one of Oak's aids!\p"
  .string "We just wanted to congratulate you\n"
  .string "on obtaining all the badges!$"


roamer_Text_3::
  .string "{COLOR BLUE}Now that you're strong enough,\n"
  .string "this information would be helpful...\p"
  .string "Roaming legendaries have appeared!\p"
  .string "You can view them on your Town\n"
  .string "Map.$"


roamer_Text_4::
  .string "{COLOR BLUE}They're quite powerful mons,\n"
  .string "although they may be difficult to\l"
  .string "catch.\p"
  .string "That's all from me!\p"
  .string "Good luck!$"


virizion_Text_1::
  .string "Aeepraaa!$"


Viridian_Text_GirlTip ::
  .string "Here's a neat trick!\p"
  .string "Pressing {R_BUTTON} in the main fight menu\n"
  .string "allows you to instantly click the\l"
  .string "Run button!$"


viridian_Text_cheatiswrong::
  .string "Hmm... you really don't know\n"
  .string "what's up...$"


viridian_Text_doyoucheat::
  .string "Hmm... do you know what's up?$"


viridian_Text_youcheat::
  .string "I guess you're in the know.\n"
  .string "Take these.$"


oldmanrescript_Text_HadMyCoffeTxt::
  .string "Well, now, I've had my coffee, and\n"
  .string "that's what I need to get going!\p"
  .string "But I made it too strong.\n"
  .string "It gave me a headache...\p"
  .string "Incidentally, is my old Teachy TV\n"
  .string "helping you?$"


oldmanrescript_Text_GrandsonShowTxt::
  .string "Wahaha!\n"
  .string "It's my grandson on the show!\p"
  .string "Since he's the one doing the\n"
  .string "teaching, you're bound to learn.$"


oldmanrescript_Text_GetGoingTxt::
  .string "Well, now, I've had my coffee, and\n"
  .string "that's what I need to get going!\p"
  .string "But I made it too strong.\n"
  .string "It gave me a headache...\p"
  .string "Incidentally, are you filling your\n"
  .string "Pokédex?\p"
  .string "At first, focus on weakening the\n"
  .string "Pokémon before trying to catch it.$"


oldmanrescript_Text_PrivatePropertyTxt::
  .string "I absolutely forbid you from\n"
  .string "going through here!\p"
  .string "This is private property!$"


oldmanrescript_Text_TooBusyTxt::
  .string "Hm... You're too busy to not even\n"
  .string "have the time for Teachy TV...\p"
  .string "Time is money, and neither should\n"
  .string "be ill spent...$"


oldmanrescript_Text_CoffeeTextToo::
  .string "Well, now, I've had my coffee, and\n"
  .string "that's what I need to get going!\p"
  .string "Hm?\n"
  .string "What is that red box you have?\p"
  .string "Ah, so you're working on your\n"
  .string "Pokédex.\p"
  .string "Then let me give you a word of\n"
  .string "advice.\p"
  .string "Whenever you catch a Pokémon,\n"
  .string "the Pokédex automatically updates\l"
  .string "its data.$"


oldmanrescript_Text_EducationRight::
  .string "Here, take this, too.$"


oldmanrescript_Text_WatchThat::
  .string "That thing's worthless!$"


viridian_Text_levelcapdetails::
  .string "Just so you know, rare candies automa-\n"
  .string "tically stop working when you reach\l"
  .string "the level cap so you don't accident-\l"
  .string "ally overlevel.$"


Viridian_Text_FollowerPkmn1::
  .string "{COLOR BLUE}It appears your {COLOR GREEN}{STR_VAR_1}{COLOR BLUE}\n"
  .string "would like to come out of its ball.\p"
  .string "Would you like to bring it out?$"


Viridian_Text_FollowerPkmn2::
  .string "{COLOR BLUE}Aw, a lot of Pokémon do prefer\n"
  .string "being out of its ball.$"


Viridian_Text_FollowerPkmn3::
  .string "{COLOR BLUE}Ah, unfortunately, you don't have a\n"
  .string "Pokémon that wants to come out\l"
  .string "of its ball.$"


Viridian_Text_FollowerPkmnDisble::
  .string "{COLOR BLUE}Would you like to put your\n"
  .string "Pokémon back in its ball?$"


Viridian_Text_Arcanine1::
  .string "Iggy: Ruff ruff!$"


Viridian_Text_hisuianInfo::
  .string "Iggy's a {COLOR GREEN}Hisuian Growlithe.\p"
  .string "{COLOR RED}Supposedly Hisuians can't be found in\n"
  .string "Kanto, but can be seen in the Sevii\l"
  .string "Islands.\p"
  .string "However, I've heard there's an Egg\n"
  .string "Traveler here in Kanto who sells Eggs\l"
  .string "that hatch into Hisuian forms.$"


LassRepelEncounter_Text::
  .string "{COLOR RED}Eek, I hate bugs!$"


LassRepelDefeat_Text::
  .string "Picked a fight with the wrong trainer...$"


Viridian_Text_LassRepel1::
  .string "{COLOR RED}Sorry for being rude!\n"
  .string "I'm on edge...\p"
  .string "Using the new Infinite Repel{COLOR RED}\n"
  .string "I got from my father, I'm able to avoid\l"
  .string "these pesky insects...\p"
  .string "But I'm still a bit startled.$"


Viridian_Text_LassRepel1_2::
  .string "... Ah, perhaps you could put it to use\n"
  .string "too!\p"
  .string "Here, let me unlock that for you.$"


Viridian_Text_LassRepel2::
  .string "{COLOR BLACK}You unlocked the Infinite Repel!$"


Viridian_Text_LassRepel3::
  .string "Just hit the {L_BUTTON} to bring up\n"
  .string "the skills menu so you can\l"
  .string "enable or disable the Infinite Repel.\p"
  .string "Well, no more bugs for me!\p"
  .string "Bye bye.$"


ViridianCity_Text_FollowerNew1::
  .string "{COLOR BLUE}Hey, you're a new trainer aren't ya!\p"
  .string "Did you know you could take\n"
  .string "your Pokémon out of its ball?\p"
  .string "Sometimes it's nice to let them\n"
  .string "get some fresh air.$"


ViridianCity_Text_FollowerNew1_1::
  .string "{COLOR BLUE}Hey, you're an experienced\n"
  .string "trainer!\p"
  .string "Did you know you could take\n"
  .string "your Pokémon out of its ball?\p"
  .string "Sometimes it's nice to let them\n"
  .string "get some fresh air.$"


NatureChanger_Text_TurnedOffInstaHP::
  .string "...Instant HP option has been\n"
  .string "turned off!$"


NatureChanger_Text_TurnOnInstaHP::
  .string "Would you like to turn on the\n"
  .string "Instant HP Bar setting?$"


NatureChanger_Text_TurnedOnInstaHP::
  .string "...Instant HP option has been\n"
  .string "turned on!$"


NatureChanger_Text_TurnOffInstaHP::
  .string "Would you like to turn off\n"
  .string "the Instant HP Bar setting?$"


NatureChanger_Text_InstantHPInfo::
  .string "The Instant HP Bar setting allows\n"
  .string "the HP bar to move much\l"
  .string "quicker if toggled on.\p"
  .string "Some prefer it off since it can look\n"
  .string "jarring.$"


InstantHPBar_Text::
  .string "Instant HP Bar$"


ModeInfo_Text::
  .string "Mode Info$"


MsgAskToGoDownEasy_Text::
  .string "You are currently playing on {COLOR GREEN}Normal\n"
  .string "Mode.\p"
  .string "{COLOR RED}Would you like to go down to\n"
  .string "{COLOR GREEN}Easy Mode?$"


AreYouSureEasy_Text::
  .string "Are you sure you want to switch\n"
  .string "to {COLOR GREEN}Easy?{COLOR RED} You won't be able to\l"
  .string "switch back.$"


SwitchedToEasy_Text::
  .string "...You have switched to {COLOR GREEN}Easy Mode.{COLOR RED}$"


DisplayEasyMode_Text::
  .string "{COLOR GREEN}Easy Mode.{COLOR RED}$"


DisplayHCMode_Text::
  .string "{COLOR GREEN}Hardcore Mode...{COLOR RED}$"


ScaledRandomizer_Text::
  .string "{COLOR GREEN}Scaled Randomizer...{COLOR RED}$"


YouArePlayingOn_Text::
  .string "You are playing on...$"


SpeciesRandomizer_Text_PC::
  .string "{COLOR GREEN}Species Randomizer...{COLOR RED}$"


AbilityRandomizer_Text_Text::
  .string "{COLOR GREEN}Ability Randomizer...{COLOR RED}$"


LearnsetRandomizer_Text_Text::
  .string "{COLOR GREEN}Learnset Randomizer...{COLOR RED}$"


RestrictMode_Text::
  .string "{COLOR GREEN}Restricted Mode...{COLOR RED}$"


Viridian_Text_IggySign::
  .string "Hisuian Growlithe\n"
  .string "Name: Iggy$"


ViridianForest_Text_AceTrainerEncounter::
  .string "Did you know this area has different\n"
  .string "encounters?$"


ViridianForest_Text_AceTrainerDefeat::
  .string "What?! Gulpin couldn't do it?$"


ViridianForest_Text_AceTrainerAfter::
  .string "My intuiton tells me there's a rare\n"
  .string "Pokémon past the smashable rocks...$"


