RandomEgg_Text::
  .string "Hi there! You're a trainer, arent\n"
  .string "you?\p"
  .string "I have an egg sent to me by a\n"
  .string "friend.\p"
  .string "Even he doesn't know where it's\n"
  .string "from!\p"
  .string "Would you like it for \$5000?$"


RandomEgg2_Text::
  .string "Great! Here you go!$"


RandomEgg3 _Text::
  .string "As for the money...$"


RandomEggNoRoom_Text::
  .string "Ah, you don't have room.$"


RandomEgg4_Text::
  .string "Thanks for taking my egg!\p"
  .string "Take care of it please.$"


RandomEgg5_Text::
  .string "Take care of the Wonder Egg!$"


RandomEgg6_Text::
  .string "Take care of the Paldean Egg!$"


RandomEggNotEnough_Text::
  .string "Aw, that's not enough money.$"


GiratinaCode_Text::
  .string "h77XuRIDLXea$"


WouldYouLikePaldean_Text::
  .string "Alright traveler. I have two types\n"
  .string "of eggs. A Paldean Egg, which\l"
  .string "hatches into a Paldean Pokémon.\p"
  .string "Or, you can have a Wonder Egg\n"
  .string "that just contains a random\l"
  .string "first form Pokémon.\p"
  .string "Supposedly, even a {COLOR GREEN}Cosmog{COLOR BLUE} could\n"
  .string "be obtained from these.$"


Paldean_Text::
  .string "Paldean Egg$"


Wonder_Text::
  .string "Wonder Egg$"


WhichOne_Text::
  .string "Which one would you like?$"


