.set SPOKE_TO_WOMAN_LAST,   FLAG_TEMP_2
.set SPOKE_TO_FAT_MAN_LAST, FLAG_TEMP_3

VermilionCity_PokemonFanClub_Frlg_MapScripts::
	.byte 0

VermilionCity_PokemonFanClub_EventScript_Chairman::
	lock
	faceplayer
	goto_if_set FLAG_GOT_BIKE_VOUCHER, VermilionCity_PokemonFanClub_EventScript_AlreadyHeardStory
	msgbox VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, VermilionCity_PokemonFanClub_EventScript_ChairmanStory
	msgbox VermilionCity_PokemonFanClub_Text_ComeBackToHearStory
	release
	end

VermilionCity_PokemonFanClub_EventScript_AlreadyHeardStory::
	msgbox VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain
	release
	end

VermilionCity_PokemonFanClub_EventScript_ChairmanStory::
	msgbox VermilionCity_PokemonFanClub_Text_ChairmansStory
	checkitemspace ITEM_BIKE_VOUCHER
	goto_if_eq VAR_RESULT, FALSE, VermilionCity_PokemonFanClub_EventScript_NoRoomForBikeVoucher
	setflag FLAG_GOT_BIKE_VOUCHER
	giveitem_msg VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman, ITEM_BIKE_VOUCHER, 1, MUS_RG_OBTAIN_KEY_ITEM
	msgbox VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher
	release
	end

VermilionCity_PokemonFanClub_EventScript_NoRoomForBikeVoucher::
	msgbox VermilionCity_PokemonFanClub_Text_MakeRoomForThis
	release
	end

VermilionCity_PokemonFanClub_EventScript_WorkerF::
	lock
	faceplayer
	goto_if_set FLAG_SYS_GAME_CLEAR, VermilionCity_PokemonFanClub_EventScript_WorkerFGameClear
	msgbox VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon
	release
	end

VermilionCity_PokemonFanClub_EventScript_WorkerFGameClear::
	famechecker FAMECHECKER_DAISY, 1
	msgbox VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons
	release
	end

VermilionCity_PokemonFanClub_EventScript_Woman::
	lock
	faceplayer
	goto_if_set SPOKE_TO_FAT_MAN_LAST, VermilionCity_PokemonFanClub_EventScript_WomanSpokeToFatMan
	msgbox VermilionCity_PokemonFanClub_Text_AdoreMySeel
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_WOMAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	setflag SPOKE_TO_WOMAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_WomanSpokeToFatMan::
	msgbox VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_WOMAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	clearflag SPOKE_TO_FAT_MAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_FatMan::
	lock
	faceplayer
	goto_if_set SPOKE_TO_WOMAN_LAST, VermilionCity_PokemonFanClub_EventScript_FatManSpokeToWoman
	msgbox VermilionCity_PokemonFanClub_Text_AdmirePikachusTail
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_FAT_MAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	setflag SPOKE_TO_FAT_MAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_FatManSpokeToWoman::
	msgbox VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute
	closemessage
	applymovement LOCALID_POKEMON_FAN_CLUB_FAT_MAN, Common_Movement_FaceOriginalDirection
	waitmovement 0
	clearflag SPOKE_TO_WOMAN_LAST
	release
	end

VermilionCity_PokemonFanClub_EventScript_Pikachu::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PIKACHU, CRY_MODE_NORMAL
	msgbox VermilionCity_PokemonFanClub_Text_Pikachu
	waitmoncry
	release
	end

VermilionCity_PokemonFanClub_EventScript_Seel::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_SEEL, CRY_MODE_NORMAL
	msgbox VermilionCity_PokemonFanClub_Text_Seel
	waitmoncry
	release
	end

VermilionCity_PokemonFanClub_EventScript_RulesSign1::
	msgbox VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers, MSGBOX_SIGN
	end

VermilionCity_PokemonFanClub_EventScript_RulesSign2::
	msgbox VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack, MSGBOX_SIGN
	end


VermilionCity_PokemonFanClub_EventScript_TamerTutor::
	lock
	faceplayer
    goto_if_quest_complete QUEST_FAN_CLUB_TUTOR, VermilionCity_PokemonFanClub_EventScript_TeachBoostingMoves	
	goto_if_quest_active QUEST_FAN_CLUB_TUTOR, VermilionCity_PokemonFanClub_EventScript_CheckBoy
	msgbox VermilionCity_FanClubTutor_Text_LookingForOffensiveMon
    setflag FLAG_SYS_QUEST_MENU_GET
 	questmenu QUEST_MENU_SET_ACTIVE QUEST_FAN_CLUB_TUTOR
    openquestmenu
    startquest QUEST_FAN_CLUB_TUTOR
	release
	end

VermilionCity_PokemonFanClub_EventScript_CheckBoy:
	msgbox VermilionCity_FanClubTutor_Text_BringMeAGoodBoy
	callnative CheckFollowerPokemonIsPerfectOffenses
	goto_if_eq VAR_RESULT, NO, VermilionCity_PokemonFanClub_EventScript_ThatsNotPerfOffenses
	setvar 0x8004, 0
	special BufferMonNickname
	msgbox VermilionCity_FanClubTutor_Text_HesHim
	completequest QUEST_FAN_CLUB_TUTOR
    waitmessage
    release
    end
	
VermilionCity_PokemonFanClub_EventScript_ThatsNotPerfOffenses: 
	msgbox VermilionCity_FanClubTutor_Text_ThatsNotPerfOffenses
	release
	end

VermilionCity_PokemonFanClub_EventScript_TeachBoostingMoves:
	msgbox VermilionCity_FanClubTutor_Text_DoYouWantBoostingTutor, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, NO, VermilionCity_PokemonFanClub_EventScript_NoInterestInBoostingMoves
	msgbox VermilionCity_FanClubTutor_Text_WhatchaThinking
	dynmultichoice 25, 0, 0, 6, 0, DYN_MULTICHOICE_CB_NONE, PkmnCenterNurse_Text_FlameCharge, PkmnCenterNurse_Text_Trailblaze, PkmnCenterNurse_Text_PowerUpPunch, PkmnCenterNurse_Text_ChargeBeam, PkmnCenterNurse_Text_WorkUp, PkmnCenterNurse_Text_HoneClaws
	switch VAR_RESULT
	case MULTI, VermilionCity_PokemonFanClub_EventScript_NoInterestInBoostingMoves
	case 0, VermilionCity_PokemonFanClub_EventScript_TeachFlameCharge
	case 1, VermilionCity_PokemonFanClub_EventScript_TeachTrailblaze
	case 2, VermilionCity_PokemonFanClub_EventScript_TeachPowerUpPunch
	case 3, VermilionCity_PokemonFanClub_EventScript_TeachChargeBeam
	case 4, VermilionCity_PokemonFanClub_EventScript_TeachWorkUp
	case 5, VermilionCity_PokemonFanClub_EventScript_TeachHoneClaws
	end

VermilionCity_PokemonFanClub_EventScript_NoInterestInBoostingMoves::
	@ msgbox VermilionCity_FanClubTutor_Text_HopeToSeeYouAgain
	release
	end

VermilionCity_PokemonFanClub_EventScript_TeachFlameCharge:
	setvar VAR_0x8005, MOVE_FLAME_CHARGE
	goto VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves

VermilionCity_PokemonFanClub_EventScript_TeachTrailblaze:
	setvar VAR_0x8005, MOVE_TRAILBLAZE
	goto VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves

VermilionCity_PokemonFanClub_EventScript_TeachPowerUpPunch:
	setvar VAR_0x8005, MOVE_POWER_UP_PUNCH
	goto VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves

VermilionCity_PokemonFanClub_EventScript_TeachChargeBeam:
	setvar VAR_0x8005, MOVE_CHARGE_BEAM
	goto VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves

VermilionCity_PokemonFanClub_EventScript_TeachWorkUp:
	setvar VAR_0x8005, MOVE_WORK_UP
	goto VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves

VermilionCity_PokemonFanClub_EventScript_TeachHoneClaws:
	setvar VAR_0x8005, MOVE_HONE_CLAWS
	goto VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves

VermilionCity_PokemonFanClub_EventScript_FinishBoostingMoves:
	call EventScript_ChooseMoveTutorMon
	goto_if_eq VAR_RESULT, FALSE, VermilionCity_PokemonFanClub_EventScript_NoInterestInBoostingMoves
	msgbox VermilionCity_FanClubTutor_Text_TaughtBoostingMoves
	release
	end


VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Won't you admire my PIKACHU's\n"
    .string "adorable tail?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "Humph!\p"
    .string "My PIKACHU is twice as cute as\n"
    .string "that one!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "I just adore my SEEL!\n"
    .string "It's so lovable!\p"
    .string "It squeals, “Kyuuuh,” when I\n"
    .string "hug it!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Oh, dear!\p"
    .string "My SEEL is far more attractive.\n"
    .string "By double, I would say.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEEL: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "I chair the Pokémon Fan Club!\p"
    .string "I raise more than a hundred\n"
    .string "Pokémon!\p"
    .string "I'm very fussy when it comes to\n"
    .string "Pokémon! I surely am!\p"
    .string "So…\p"
    .string "Did you come visit to hear about\n"
    .string "my Pokémon?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Good!\n"
    .string "Then listen up!\p"
    .string "My favorite RAPIDASH…\p"
    .string "It's…cute…lovely…smart… \n"
    .string "plus…amazing…you think so?…\l"
    .string "oh yes…it's…stunning…\l"
    .string "kindly…love it!\p"
    .string "Hug it…when…sleeping…warm\n"
    .string "and cuddly…spectacular…\l"
    .string "ravishing…\l"
    .string "…Oops! Look at the time!\l"
    .string "I kept you too long!\p"
    .string "Thanks for hearing me out!\n"
    .string "I want you to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in Cerulean City.\p"
    .string "Exchange that for a BICYCLE\n"
    .string "free of charge!\p"
    .string "Don't worry, my favorite FEAROW\n"
    .string "will FLY me anywhere I need to go.\p"
    .string "So, I have no need for a BICYCLE.\p"
    .string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about my\n"
    .string "Pokémon again?\p"
    .string "No?\n"
    .string "Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Our CHAIRMAN is very vocal about\n"
    .string "Pokémon.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Let's all listen politely to other\n"
    .string "TRAINERS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Our CHAIRMAN really does adore his\n"
    .string "Pokémon.\p"
    .string "But the person who is most liked by\n"
    .string "Pokémon is DAISY, I think.$"

VermilionCity_FanClubTutor_Text_LookingForOffensiveMon:
	.string "{COLOR BLUE}Ooh, you look like a good trainer!\n"
	.string "Tell you what - I love when Pokémon\l"
	.string "hit hard and fast!\p"
	.string "{PAUSE 200}.{PAUSE 200}.{PAUSE 200}.Uhh yeah, pause.\p"
	.string "What I mean is, I'd like to see a\n"
	.string "Pokémon you've perfected in its\l"
	.string "speed and offenses.\p"
	.string "Show me that and I can teach you some\n"
	.string "cool moves.$"

VermilionCity_FanClubTutor_Text_BringMeAGoodBoy:
	.string "I'd like to see a Pokémon you've\n"
	.string "perfected in its speed and offenses.\p"
	.string "Show me that and I can teach you some\n"
	.string "cool moves.$"

VermilionCity_FanClubTutor_Text_ThatsNotPerfOffenses:
	.string "Hmm… that's not quite it.$"

VermilionCity_FanClubTutor_Text_DoYouWantBoostingTutor:
	.string "Hey buddy! You want to learn some\n"
	.string "boosting moves?$"

VermilionCity_FanClubTutor_Text_HesHim:
	.string "Oh yup.{PAUSE 200}.{PAUSE 200}.{PAUSE 200}\n"
	.string "That {STR_VAR_1}, yo that {STR_VAR_1}\l"
	.string "kinda nice.\p"
	.string "Alright, as agreed I can teach you\n"
	.string "some boosting moves now. The Nurse's\l"
	.string "Aide should be able to teach you them\l"
	.string "as well.$"

VermilionCity_FanClubTutor_Text_WhatchaThinking:
	.string "Whatcha thinking?$"

VermilionCity_FanClubTutor_Text_TaughtBoostingMoves:
	.string "Faster and stronger!\n"
	.string "I hope you dig it!$"