SilphCo_Extra2_Text_MdeIntro::
    .string "Hey. New face.\p"
    .string "You here for a meeting, or for a\n"
    .string "job application?\p"
    .string "The old man? He knows exactly how\n"
    .string "this business goes.\p"
    .string "He had the whole Kanto market\n"
    .string "locked up for decades.\p"
    .string "It wouldn't kill him to share a bit.\p"
    .string "Or to step up his game now that\n"
    .string "there's finally a contender.$"

SilphCo_Extra2_Text_MdeTheDeal::
    .string "Look, I've got places to be and\n"
    .string "calls to make.\p"
    .string "But I'm somewhat in the mood for it.\p"
    .string "Beat me in a battle and I'll leave\n"
    .string "the old man alone. Plus something\l"
    .string "worth your time.\p"
    .string "The pres will just hand you a Master\n"
    .string "Ball, and you've got EZCatch, so it\l"
    .string "doesn't matter. Deal?$"

SilphCo_Extra2_Text_MdeDeclined::
    .string "Sure.\p"
    .string "Now shoo. I have an important call\n"
    .string "to make.$"

SilphCo_Extra2_Text_MdeAccepted::
    .string "Okay. Don't disappoint me.\p"
    .string "Bring me some inspiration for my\n"
    .string "next ideas.$"

SilphCo_Extra2_Text_MdeDefeat::
    .string "What a shame you won't join my\n"
    .string "company.\p"
    .string "You got guts, and you got skill.$"

SilphCo_Extra2_Text_MdeDealIsADeal::
    .string "Welp. A deal is a deal.\p"
    .string "I'll leave the old man alone.\p"
    .string "And since I happen to have two of\n"
    .string "these little guys…\p"
    .string "Why not let one ride along with you?\n"
    .string "It'll most likely help.$"

SilphCo_Extra2_Text_MdeFiredUp::
    .string "Anyway. You got me fired up with\n"
    .string "ideas for my next projects.\p"
    .string "So I have to take my leave.\n"
    .string "Bye!$"

SilphCo_Extra2_Text_MdeNoRoom::
    .string "…Your Bag is stuffed.\p"
    .string "Clear some space and come see me.\n"
    .string "I'm not going anywhere. Yet.$"

SilphCo_Extra2_Text_MdeAfterBattle::
    .string "Still here? I'm on a call.\p"
    .string "Tell the old man the market's his\n"
    .string "for now. I've got bigger projects.$"
